'use client';
import {proxyAuditText} from '@/lib/admin/proxy-audit';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import AdminNavigation from './AdminNavigation';
import RecoveryOverview from './RecoveryOverview';
import DocumentQueue from './DocumentQueue';
import ProxyControl from './ProxyControl';
import CollectionPace from './CollectionPace';
import ProcessingOverview from './ProcessingOverview';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {CollectionStatus} from '@/lib/admin/collection';
const fmt=(n:unknown)=>new Intl.NumberFormat('ro-RO').format(Number(n??0));
const time=(s:unknown)=>s?new Date(String(s)).toLocaleTimeString('ro-RO',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Europe/Bucharest'}):'—';
const date=(s:unknown)=>s?new Date(String(s)).toLocaleDateString('ro-RO',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Bucharest'}):'—';
const streamLabels:Record<string,string>={da:'Achiziții directe',tenders:'Anunțuri de participare',awards:'Anunțuri de atribuire',documents:'Documente',catalogue:'Catalogul instituțiilor'};
function Icon({kind}:{kind:'pause'|'play'|'down'|'settings'|'download'|'shield'}){const paths={pause:'M8 5v14M16 5v14',play:'m8 5 11 7-11 7Z',down:'m6 9 6 6 6-6',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',download:'M12 3v12m-5-5 5 5 5-5M5 16v4h14v-4',shield:'M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7l-9-4Zm-4 9 3 3 5-6'};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[kind]}/></svg>;}
interface Form {min:string;max:string;daily:boolean;limit:string;at:string;enabled:boolean;riskDay:number;revision:number}
const formOf=(c:Record<string,any>):Form=>({min:String(c.min_seconds),max:String(c.max_seconds),daily:c.daily_limit!==null,limit:String(c.daily_limit??1000),at:c.processing_time,enabled:!!c.processing_enabled,riskDay:c.risk_weekday??0,revision:c.revision});
export default function CollectionDashboard({children}:{children:React.ReactNode}){
 const path=usePathname(),collection=path==='/admin',processing=path==='/admin/procesare';
 const [data,setData]=useState<CollectionStatus|null>(null),[form,setForm]=useState<Form|null>(null),[stale,setStale]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState('all'),[expanded,setExpanded]=useState<string|null>(null),[ack,setAck]=useState(false),[now,setNow]=useState(Date.now()),[showRecovery,setShowRecovery]=useState(false);
 const [proxyDirty,setProxyDirty]=useState(false);
 const [journalPage,setJournalPage]=useState(1),[journalSnapshot,setJournalSnapshot]=useState<Array<CollectionStatus['requests'][number]>|null>(null);
 const dirtyRef=useRef(false),refreshing=useRef(false),controller=useRef<AbortController|null>(null),offset=useRef(0),mounted=useRef(true);
 const refresh=useCallback(async(force=false,resetForm=force)=>{if(refreshing.current){if(!force)return;controller.current?.abort();}refreshing.current=true;const ac=new AbortController();controller.current=ac;const timeout=setTimeout(()=>ac.abort(),30000);
  try{const res=await fetch('/api/admin/collection',{cache:'no-store',signal:ac.signal});if(!res.ok)throw Error();const next:CollectionStatus=await res.json();if(!mounted.current||controller.current!==ac)return;offset.current=new Date(next.control!.server_now).getTime()-Date.now();setNow(Date.now()+offset.current);setData(next);setStale(false);if(!dirtyRef.current||resetForm){setForm(formOf(next.control!));dirtyRef.current=false;}}
  catch{if(mounted.current&&controller.current===ac)setStale(true);}finally{clearTimeout(timeout);if(controller.current===ac)refreshing.current=false;}
 },[]);
 useEffect(()=>{mounted.current=true;void refresh();const id=setInterval(()=>{if(!document.hidden)void refresh();},60000),clock=setInterval(()=>setNow(Date.now()+offset.current),1000);const focus=()=>{void refresh();};window.addEventListener('focus',focus);return()=>{mounted.current=false;controller.current?.abort();clearInterval(id);clearInterval(clock);window.removeEventListener('focus',focus);};},[refresh]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirtyRef.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function change(body:Record<string,unknown>){if(!data||stale||saving)return;setSaving(true);setError('');setMessage('');try{const res=await fetch('/api/admin/collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const r=await res.json();if(!res.ok)throw Error(r.error??'Modificarea nu a fost salvată.');if(body.action==='settings')dirtyRef.current=false;else setForm(current=>current&&current.revision===body.revision?{...current,revision:r.revision}:current);setAck(false);setShowRecovery(false);setMessage('Modificarea a fost salvată. Pauza deja începută se păstrează.');await refresh(true,body.action==='settings');return true;}catch(e){setError(e instanceof Error?e.message:'Modificarea nu a fost salvată.');void refresh();return false;}finally{setSaving(false);}}
 if(!data||!form)return <div className="collection-admin"><AdminNavigation data={data} stale={stale} dirty={false}/><div id="admin-content" tabIndex={-1}>{(path==='/admin/conturi'||path==='/admin/feedback')?children:<><div className="empty-state" role="status">{stale?'Statusul nu poate fi citit. Verifică conexiunea și migrațiile aplicației.':'Se citește statusul colectării…'}</div>{stale&&<button className="button" onClick={()=>void refresh()}>Reîncearcă</button>}</>}</div></div>;
 const c=data.control!,dailyReached=c.daily_limit!==null&&Number(data.today.attempts)>=Number(c.daily_limit),workers=data.workers.filter(w=>w.alive),active=data.requests.find(r=>r.outcome==='running'),paused=!!c.paused,maintenance=!!c.maintenance,blocked=!!c.blocked_reason,alive=workers.some(w=>['documents','ingestion'].includes(w.kind));
 const quiet=!!data.quietWindow?.active,retry=data.timeoutRetry;
 const running=!quiet&&!stale&&!paused&&!maintenance&&!blocked&&!dailyReached&&alive;
 const next=Math.max(0,Math.ceil((Math.max(new Date(c.next_allowed_at??0).getTime(),new Date(retry?.retry_at??0).getTime())-now)/1000));
 const title=stale?'Nu mai primim statusul serverului.':maintenance?'Site-ul este în mentenanță.':blocked?'Colectarea așteaptă verificarea sursei.':paused?'Colectarea este pe pauză.':dailyReached?'Limita zilnică a fost atinsă.':quiet?'Pauză SEAP programată până la '+time(data.quietWindow.resumes_at)+'.':retry?(active?'Reîncercăm cererea după timeout.':'Timeout SEAP · reîncercare programată.'):active?(data.requests.filter(r=>r.outcome==='running').length>1?`Preluăm ${data.requests.filter(r=>r.outcome==='running').length} răspunsuri din SEAP.`:'Preluăm un răspuns din SEAP.'):alive?'Coada SEAP este pregătită.':'Colectorul nu este pornit.';
 const description=stale?'Valorile sunt ultima stare cunoscută. Colectarea poate continua pe server.':blocked?String(c.blocked_reason):quiet?'Nu pornesc cereri noi. Coada se reia automat după pauză, dacă nu există o oprire manuală sau o eroare.':retry?(active?`Încercarea ${Number(retry.timeouts)+1}/3 este în curs. Reluăm aceeași cerere; restul traficului SEAP așteaptă.`:`Încercarea ${Number(retry.timeouts)+1}/3, cel mai devreme la ${time(retry.retry_at)}. Reluăm aceeași cerere; întregul trafic SEAP așteaptă. Pauzele și limitele rămân active.`):!alive&&!paused?'Setările sunt salvate. Nu există un worker cu semnal recent.':`Un singur buget pentru date și documente. ${data.proxies.settings.enabled&&Number(data.proxies.settings.max_in_flight)>1?`Maximum ${data.proxies.settings.max_in_flight} cereri simultane, pe IP-uri diferite.`:'O singură cerere în curs.'}`;
 const dirty=Number(form.min)!==c.min_seconds||Number(form.max)!==c.max_seconds||form.daily!==(c.daily_limit!==null)||form.daily&&Number(form.limit)!==c.daily_limit||form.at!==c.processing_time||form.enabled!==c.processing_enabled||form.riskDay!==c.risk_weekday;
 dirtyRef.current=dirty;
 const valid=Number.isInteger(Number(form.min))&&Number.isInteger(Number(form.max))&&Number(form.min)>=1&&Number(form.max)<=3600&&Number(form.min)<=Number(form.max)&&(!form.daily||Number.isSafeInteger(Number(form.limit))&&Number(form.limit)>=1)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(form.at);
 const conflict=dirty&&form.revision!==c.revision;
 const edit=(patch:Partial<Form>)=>{dirtyRef.current=true;setForm({...form,...patch});setMessage('');};
 const liveRows=(filter==='errors'?data.failures:data.requests).filter(r=>filter==='all'||filter==='errors'&&['failed','interrupted'].includes(r.outcome)||r.stream===filter);
 const rows=journalSnapshot??liveRows,pageCount=Math.max(1,Math.ceil(rows.length/10)),page=Math.min(journalPage,pageCount);
 const visibleRows=rows.slice((page-1)*10,page*10);
 const turnPage=(next:number)=>{setJournalPage(next);setJournalSnapshot(next===1?null:journalSnapshot??liveRows);setExpanded(null);};
 return <div className="collection-admin">
 <AdminNavigation data={data} stale={stale} dirty={dirty} proxyDirty={proxyDirty}/>
 <div id="admin-content" tabIndex={-1}>
 <div hidden={!collection}><div className="admin-view-heading"><h2>Colectarea datelor</h2><p>Cât am preluat și ce urmează din SEAP.</p></div><RecoveryOverview data={data} stale={stale}/>
 <section className="live-band" id="collection" data-state={stale?'offline':blocked?'blocked':paused||quiet||retry?'paused':'live'} aria-labelledby="state-title"><div className="live-copy"><div className="state-line"><span className="live-dot"/><h2 id="state-title">{title}</h2></div><p>{description}</p><div className="current-task"><span>{active?'În curs':'Workers conectați'}</span><strong>{active?data.requests.filter(r=>r.outcome==='running').map(r=>`${streamLabels[r.stream]??r.stream} · ${r.proxy_id??'direct'}`).join(' / '):workers.length?workers.map(w=>w.kind==='documents'?'Documente':w.kind==='processor'?'Procesare':w.kind==='scheduler'?'Programare':'Colectare').filter((v,i,a)=>a.indexOf(v)===i).join(', '):'Niciun semnal în ultimele 30 secunde'}</strong></div></div><div className="next-request"><span>{stale?'Stare necunoscută':running?(retry?'Reîncercarea, cel mai devreme în':'Următoarea cerere, cel mai devreme în'):'Cereri noi'}</span><strong id="countdown">{running?(active?'În curs':next>0?<>{next}<span> sec</span></>:retry?'Se pregătește':'La cerere'):stale?'—':'Oprite'}</strong><div className="countdown-track"><div id="countdown-fill" style={{transform:`scaleX(${running?Math.min(1,next/(retry?(Number(retry.timeouts)===1?300:600):c.max_seconds)):0})`}}/></div><small>{retry?`Pauză după timeout: ${Number(retry.timeouts)===1?5:10} minute`:data.proxies.settings.enabled?`${data.proxies.endpoints.filter(p=>p.enabled).length} proxy-uri activate · plafon ${data.proxies.settings.requests_per_minute}/min`:`Interval aleator: ${c.min_seconds}–${c.max_seconds} sec`}</small></div><div className="live-actions"><button id="pause" className="button band-button" disabled={stale||saving||maintenance} onClick={()=>blocked?setShowRecovery(!showRecovery):void change({action:'pause',paused:!paused,revision:c.revision})}><Icon kind={paused||blocked?'play':'pause'}/><span>{blocked?'Verifică și reia':paused?'Reia coada SEAP':'Pune pe pauză'}</span></button><small>Progresul se păstrează.</small></div></section>
 {!!data.proxyRetries?.length&&<p className="policy-note" role="status">{data.proxyRetries.length} cereri așteaptă reîncercarea. Celelalte proxy-uri continuă colectarea. Următoarea reîncercare: {time(data.proxyRetries[0]!.retry_at)}. <Link href="/admin/conexiune">Vezi conexiunile</Link></p>}
 {stale&&<p className="status-notice" role="status">Conexiunea de raportare este întreruptă. Comenzile sunt indisponibile. Încercăm reconectarea automat.</p>}
 {showRecovery&&blocked&&<div className="recovery"><p>{c.blocked_reason}{c.blocked_until&&<> Așteptare obligatorie până la {date(c.blocked_until)}, {time(c.blocked_until)}.</>}</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Am verificat răspunsul SEAP și cauza opririi. Pot relua cererile.</label><button className="button primary" disabled={!ack||saving||stale||c.blocked_until&&new Date(c.blocked_until).getTime()>now} onClick={()=>void change({action:'unblock',acknowledged:true,revision:c.revision})}>Confirmă reluarea</button></div>}
 </div>
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="policy-note" role="status">{message}</p>}
 <div className="stats" hidden={!collection}><div><span>Cereri astăzi <small>toate încercările</small></span><strong>{fmt(data.today.attempts)}</strong><p>{fmt(data.today.succeeded)} reușite · {fmt(data.today.failed)} eșuate</p></div><div><span>Înregistrări primite astăzi</span><strong>{fmt(data.today.received)}</strong><p>Din liste; pot include versiuni repetate</p></div><div><span>Înregistrări noi în arhivă astăzi</span><strong>{fmt(data.raw.archived)}</strong><p>Răspunsuri păstrate, după deduplicare</p></div><div><span>Fișiere de descărcat</span><strong>{fmt(data.documents.awaiting_download)}</strong><p><Link href="/admin/fisiere">Vezi coada</Link> · {fmt(data.documents.running)} operațiuni în lucru</p></div></div>
 <div className="proxy-view" hidden={path!=='/admin/conexiune'}><ProxyControl data={data} now={now} stale={stale} saving={saving} change={change} onDirtyChange={setProxyDirty}/></div>
 <div className="workspace admin-workspace" hidden={!collection&&!processing}><div className="main-column"><section className="streams" hidden={!collection}><div className="section-heading"><h2>Unde am ajuns</h2><span className="subtle">Recuperare 2026</span></div><p className="section-description">Raportare activă din {date(c.created_at)}. Istoricul vechi nu este declarat complet.</p>
 {(['da','tenders','awards'] as const).map(key=>{const s=data.streams.find(s=>s.stream===key),progress=data.recovery?.progress.find(s=>s.stream===key),stopped=(c.paused_streams as string[]).includes(key),run=data.runs.find(r=>r.source===`elicitatie:${key==='da'?'das':key}`);return <div className="stream" key={key}><div className="stream-heading"><h3>{streamLabels[key]}</h3><span className={`badge ${stopped?'warning':'neutral'}`}>{stopped?'Pe pauză':Number(progress?.failed)>0?'Erori de verificat':Number(progress?.deferred)>0?'Detalii nepreluate':Number(progress?.running)>0||run?.status==='running'?'În curs':Number(progress?.complete)>0?'Pași arhivați':s?'Cereri înregistrate':'Neînceput'}</span><button className="icon-button stream-toggle" disabled={stale||saving} aria-pressed={stopped} aria-label={`${stopped?'Reia':'Pune pe pauză'} ${streamLabels[key]}`} onClick={()=>void change({action:'stream',stream:key,paused:!stopped,revision:c.revision})}><Icon kind={stopped?'play':'pause'}/></button></div><p>De la {key==='da'?'1 iulie':'1 ianuarie'} 2026 <span>· {key==='da'?'după data finalizării':'după data publicării'}</span></p><div className="progress-label"><strong>{fmt(s?.attempts)} <span>cereri efectuate</span></strong><span>{fmt(s?.received)} înregistrări primite</span></div>{progress&&(()=>{const complete=Number(progress.complete)+Number(progress.split),total=complete+Number(progress.pending)+Number(progress.running)+Number(progress.failed)+Number(progress.deferred),percent=total?Math.min(Number(progress.pending)+Number(progress.running)+Number(progress.failed)+Number(progress.deferred)>0?99:100,Math.floor(complete/total*100)):0;return <div className="stream-meter"><progress max={100} value={percent} aria-label={`Pași încheiați din coada cunoscută — ${streamLabels[key]}`}/><span>{percent}% din pașii cunoscuți · {fmt(complete)} / {fmt(total)}</span></div>;})()}{progress&&<p>{fmt(progress.complete)} pași arhivați · {fmt(progress.pending)} cereri în așteptare{Number(progress.running)>0?' · o cerere în curs':''}{Number(progress.failed)>0?` · ${fmt(progress.failed)} erori de verificat`:''}{Number(progress.deferred)>0?` · ${fmt(progress.deferred)} detalii eForms încă nepreluate`:''}</p>}{run&&<p>Ultima rulare: {date(run.window_start)} – {date(run.window_end)} · {run.status==='completed'?'încheiată':run.status==='failed'?'întreruptă':'în lucru'}</p>}</div>;})}
 <p className="footnote">{data.recovery?`Lot până la ${date(data.recovery.batch.end_day)}. Coada include cererile descoperite până acum și poate crește prin paginare. Detaliile nepreluate rămân raportate separat.`:'Numărul total de cereri și progresul pe zile/instituții vor fi afișate după inventarierea lotului.'} Reluarea unui flux permite cererile deja programate; nu pornește o recuperare nouă.</p></section>
 <div hidden={!processing}><ProcessingOverview data={data}/></div></div>
 <aside className="settings"><form onSubmit={e=>{e.preventDefault();if(valid&&!conflict)void change({action:'settings',revision:form.revision,minSeconds:Number(form.min),maxSeconds:Number(form.max),dailyLimit:form.daily?Number(form.limit):null,processingTime:form.at,processingEnabled:form.enabled,riskWeekday:form.riskDay});}}><div className="section-heading"><h2>{processing?'Programul actualizărilor':'Ritmul colectării'}</h2><Icon kind="settings"/></div><p className="section-description">{processing?'Actualizarea zilnică și recalcularea săptămânală a riscului.':data.proxies.settings.enabled?<>Datele și documentele folosesc același buget de cereri.</>:'Se aplică tuturor cererilor SEAP, inclusiv documentelor cerute de utilizatori.'}</p><div hidden={!collection}><CollectionPace data={data} stale={stale} compact/>{data.proxies.settings.enabled?<p className="pace-link"><Link href="/admin/conexiune" scroll={false}>Ritm pe fiecare proxy și setări →</Link></p>:<fieldset><legend>Pauză în modul direct</legend><div className="delay-fields"><label>Minimum<div className="unit-input"><input id="delay-min" type="number" min="1" max="3600" step="1" required value={form.min} onChange={e=>edit({min:e.target.value})}/><span>sec</span></div></label><span className="range-dash">–</span><label>Maximum<div className="unit-input"><input id="delay-max" type="number" min="1" max="3600" step="1" required value={form.max} onChange={e=>edit({max:e.target.value})}/><span>sec</span></div></label></div><div className="presets">{[[50,70],[90,120],[120,180]].map(([min,max])=><button key={min} type="button" className={`preset ${Number(form.min)===min&&Number(form.max)===max?'selected':''}`} onClick={()=>edit({min:String(min),max:String(max)})}>{min}–{max} sec</button>)}</div><div className="rate-estimate"><strong>{valid?`≈ ${fmt(Math.round(7200/(Number(form.min)+Number(form.max))))} cereri / oră`:'Interval nevalid'}</strong><span>{Number(form.min)<50?'Mai rapid decât intervalul convenit de 50–70 sec.':'La ritm continuu, fără mentenanță.'}</span></div></fieldset>}
 <div className="setting-row"><label htmlFor="daily-enabled">Limită zilnică de cereri<small>Include încercările eșuate. Reset la 00:00.</small></label><input className="switch" role="switch" id="daily-enabled" type="checkbox" checked={form.daily} onChange={e=>edit({daily:e.target.checked})}/></div>{form.daily&&<label className="extra-field">Maximum de încercări pe zi<input id="daily-limit" type="number" min="1" max="10000000" step="1" required value={form.limit} onChange={e=>edit({limit:e.target.value})}/></label>}
 </div><fieldset hidden={!processing} disabled={maintenance}><legend>Programul procesării</legend><div className="setting-row"><label htmlFor="processing-enabled">Procesare automată<small>Backup și mentenanță înainte de actualizare.</small></label><input className="switch" role="switch" id="processing-enabled" type="checkbox" checked={form.enabled} onChange={e=>edit({enabled:e.target.checked})}/></div><div className="setting-row"><label htmlFor="maintenance-time">Ora actualizării zilnice<small>Ora României · inclusiv schimbarea orei.</small></label><input id="maintenance-time" type="time" required value={form.at} onChange={e=>edit({at:e.target.value})}/></div><label className="extra-field" htmlFor="risk-weekday">Recalculăm și riscul în fiecare<select id="risk-weekday" value={form.riskDay} onChange={e=>edit({riskDay:Number(e.target.value)})}>{['Duminică','Luni','Marți','Miercuri','Joi','Vineri','Sâmbătă'].map((day,i)=><option key={i} value={i}>{day}</option>)}</select></label><p className="save-hint">Activarea se aplică primei ore programate viitoare. Oprirea programului nu întrerupe o rulare deja începută.</p></fieldset><details className="guardrails"><summary>Reguli care rămân active</summary><ul><li>O singură cerere pe IP. Limita totală de cereri simultane se configurează în Conexiune SEAP.</li><li>Minimum 60 secunde între preluările de fișiere.</li><li>Pauză SEAP zilnică: 02:59–03:30, ora României. Reluare automată; opririle manuale și erorile se păstrează.</li><li>Oprire la 403, 429 sau verificare suplimentară.</li><li>Timeout în colectarea datelor: reîncercare după 5 minute, apoi după încă 10 minute. Prin proxy, așteaptă doar cererea afectată; celelalte continuă. Trei erori consecutive dezactivează doar proxy-ul afectat. În modul direct, trei timeouturi opresc colectarea. Fără PDF-uri preluate automat.</li></ul></details>
 {dirty&&<p className="settings-diff">{(Number(form.min)!==c.min_seconds||Number(form.max)!==c.max_seconds)&&`Interval direct: ${c.min_seconds}–${c.max_seconds} → ${form.min}–${form.max} sec. `}{(form.daily!==(c.daily_limit!==null)||form.daily&&Number(form.limit)!==c.daily_limit)&&`Limită zilnică: ${form.daily?`${fmt(form.limit)} cereri`:'fără limită'}. `}{form.at!==c.processing_time&&`Procesare: ${c.processing_time} → ${form.at}.`} {form.enabled!==c.processing_enabled&&`Program automat: ${form.enabled?'activare':'oprire'}.`} {form.riskDay!==c.risk_weekday&&`Ziua recalculării riscului se modifică.`}</p>}{conflict&&<p className="form-error" role="alert">Alt administrator a modificat setările. Reîncarcă valorile înainte de aplicare.</p>}{dirty&&!valid&&<p className="form-error" role="alert">Verifică intervalul, limita zilnică și ora procesării.</p>}
 <button id="apply" className="button primary apply" disabled={!dirty||!valid||conflict||saving||stale||maintenance}>{saving?'Se salvează…':dirty?'Aplică toate modificările':'Setările sunt la zi'}</button>{(dirty||conflict)&&<button type="button" className="text-button discard" onClick={()=>{dirtyRef.current=false;setForm(formOf(c));}}>Reîncarcă setările salvate</button>}<p className="save-hint">Modificările se aplică următoarelor cereri, fără a scurta pauza deja începută. Programul este executat de serviciul instalat pe server.</p></form></aside></div>
 <div hidden={path!=='/admin/fisiere'}><DocumentQueue enabled={path==='/admin/fisiere'} retryAt={retry?.retry_at?String(retry.retry_at):null} quiet={quiet} paused={paused} maintenance={maintenance} blocked={blocked}/></div>
 <div hidden={path!=='/admin/jurnal'}><section id="journal" className="journal"><div className="section-heading"><div><h2>Fiecare cerere, la vedere</h2><p className="section-description">Liste, detalii, documente și încercări eșuate — toate consumă același buget.</p></div><a className="button" href="/api/admin/collection?export=1" aria-disabled={stale}><Icon kind="download"/>Exportă jurnalul</a></div><div className="journal-filters" role="group" aria-label="Filtrează jurnalul">{[['all','Toate'],['da','Achiziții directe'],['tenders','Participare'],['awards','Atribuiri'],['documents','Documente'],['errors','Erori']].map(([value,label])=><button key={value} className={`filter ${filter===value?'active':''}`} aria-pressed={filter===value} onClick={()=>{setFilter(value!);setJournalPage(1);setJournalSnapshot(null);setExpanded(null);}}>{label}</button>)}</div>
 {!rows.length?<p className="empty-state">{filter==='all'?'Nu există încă cereri în noul jurnal. Datele istorice rămân disponibile în aplicație.':'Nicio cerere disponibilă pentru acest filtru.'}</p>:<div className="log-scroll"><table><thead><tr><th>Ora</th><th>Cererea</th><th>Rezultat</th><th>Durată</th><th><span className="sr-only">Detalii</span></th></tr></thead><tbody>{visibleRows.map(r=><RequestRows key={r.id} row={r} expanded={expanded===r.id} toggle={()=>setExpanded(expanded===r.id?null:r.id)}/>)}</tbody></table></div>}{rows.length>0&&<nav className="queue-pagination" aria-label="Paginile jurnalului de cereri"><span aria-live="polite">{fmt((page-1)*10+1)}–{fmt(Math.min(page*10,rows.length))} din {fmt(rows.length)} · Pagina {page} din {pageCount}</span><button className="button" disabled={page<=1} onClick={()=>turnPage(page-1)}>Înapoi</button><button className="button" disabled={page>=pageCount} onClick={()=>turnPage(page+1)}>Următoarele</button></nav>}{journalSnapshot&&<p className="footnote">Lista rămâne stabilă cât navighezi. <button className="text-button" onClick={()=>turnPage(1)}>Vezi cele mai noi cereri</button></p>}<p className="footnote">10 cereri pe pagină. Ultimele 100 de încercări; filtrul Erori păstrează separat ultimele 100 de eșecuri. Exportul include maximum 5.000. Orele sunt în Europe/Bucharest. Jurnalul nu conține cookie-uri, tokenuri sau linkuri temporare de fișiere.</p></section>
 <section className="changes"><h2>Ultimele 10 modificări de configurare</h2>{!data.audit.length?<p className="empty-state">Nicio modificare. Configurația inițială: 50–70 secunde, coada pe pauză.</p>:<ul>{data.audit.slice(0,10).map(a=><li key={a.id}><time dateTime={String(a.created_at)}>{date(a.created_at)} · {time(a.created_at)}</time><span>{a.actor_name} · {auditText(a)}</span></li>)}</ul>}</section>
 </div><div hidden={path!=='/admin/conturi'&&path!=='/admin/feedback'} className={path==='/admin/conturi'?'admin-accounts':undefined}>{children}</div></div>
 </div>;
}
function auditText(a:Record<string,any>){const b=a.before,n=a.after;if(a.action==='recovery-scope')return `Colectare extinsă până la ${n.endDay}: ${fmt(n.added??0)} cereri adăugate. Actualizare zilnică automată.`;if(a.action==='proxies')return proxyAuditText(n);if(a.action==='proxy-auto-disabled')return `${n.proxyId}: oprit după trei erori consecutive. Celelalte proxy-uri continuă.`;if(a.action==='settings')return `Interval ${b.minSeconds}–${b.maxSeconds} → ${n.minSeconds}–${n.maxSeconds} sec; procesare ${n.processingTime}; ${n.dailyLimit?`limită ${fmt(n.dailyLimit)}/zi`:'fără limită zilnică'}.${typeof n.processingEnabled==='boolean'?` Program ${n.processingEnabled?'activ':'oprit'}, risc în fiecare ${['duminică','luni','marți','miercuri','joi','vineri','sâmbătă'][n.riskWeekday]}.`:''}`;if(a.action==='pause')return n.paused?'Coada SEAP pusă pe pauză.':'Coada SEAP reluată.';if(a.action==='unblock')return 'Blocarea sursei verificată și reluare confirmată.';if(a.action==='retry-task')return `Reîncercare explicită a sarcinii ${b.taskId}; încercarea inițială rămâne în jurnal.`;if(a.action==='processing-start')return n.scope==='full'?'Actualizare săptămânală, inclusiv semnalele de risc.':'Actualizare zilnică, fără recalcularea riscului.';if(a.action==='processing-complete')return 'Datele și căutarea au fost verificate; site-ul a fost redeschis.';if(a.action==='processing-failed')return `Procesare oprită la etapa ${n.stage}; mentenanța se păstrează.`;if(a.action==='ted-repair-start')return 'Mentenanță și backup pentru refacerea istoricului TED.';if(a.action==='ted-repair-complete')return 'Istoricul TED a fost verificat; site-ul și colectarea au fost reluate.';if(a.action==='recalculation-pause')return 'Colectare oprită pentru recalcularea cronometrată.';if(a.action!=='stream')return a.action;return `Fluxuri pe pauză: ${n.pausedStreams?.length?n.pausedStreams.map((s:string)=>streamLabels[s]??s).join(', '):'niciunul'}.`;}
function RequestRows({row:r,expanded,toggle}:{row:Record<string,any>;expanded:boolean;toggle:()=>void}){return <><tr><td title={date(r.started_at)}>{time(r.started_at)}</td><td>{streamLabels[r.stream]??r.stream}<small>{r.proxy_id??'Direct / istoric'} · {r.method} · {r.endpoint.split('/').filter(Boolean).slice(-2).join('/')}</small></td><td><span className={`result ${['failed','interrupted'].includes(r.outcome)?'error':''}`}>{r.outcome==='running'?'În curs':`${r.status??'—'} · ${r.outcome==='success'?'reușit':r.outcome==='interrupted'?'întrerupt':'eșuat'}`}</span></td><td>{r.duration_ms!==null?`${(Number(r.duration_ms)/1000).toFixed(1)} s`:'—'}</td><td><button className="icon-button log-toggle" aria-expanded={expanded} aria-controls={`request-${r.id}`} aria-label={`Detalii cerere ${r.id}`} onClick={toggle}><Icon kind="down"/></button></td></tr>{expanded&&<tr className="log-detail" id={`request-${r.id}`}><td colSpan={5}><p><b>{r.method}</b> <code>{r.endpoint}</code></p><p>{date(r.started_at)} · {time(r.started_at)} · {r.bytes===null?'Dimensiune necunoscută':`${fmt(r.bytes)} octeți`}</p><pre>{JSON.stringify(r.parameters,null,2)}</pre>{r.error&&<p>{r.error}</p>}<a className="button" href={`/api/admin/collection?request=${r.id}`}><Icon kind="download"/>Descarcă detaliile cererii</a>{!r.has_diagnostics&&r.outcome!=="running"&&<p>Încercare mai veche: diagnosticul detaliat nu a fost înregistrat.</p>}</td></tr>}</>;}
