'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {CollectionStatus} from '@/lib/admin/collection';
const fmt=(n:unknown)=>new Intl.NumberFormat('ro-RO').format(Number(n??0));
const time=(s:unknown)=>s?new Date(String(s)).toLocaleTimeString('ro-RO',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Europe/Bucharest'}):'—';
const date=(s:unknown)=>s?new Date(String(s)).toLocaleDateString('ro-RO',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Bucharest'}):'—';
const streamLabels:Record<string,string>={da:'Achiziții directe',tenders:'Anunțuri de participare',awards:'Anunțuri de atribuire',documents:'Documente',catalogue:'Catalogul instituțiilor'};
function Icon({kind}:{kind:'pause'|'play'|'down'|'settings'|'download'|'shield'}){const paths={pause:'M8 5v14M16 5v14',play:'m8 5 11 7-11 7Z',down:'m6 9 6 6 6-6',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',download:'M12 3v12m-5-5 5 5 5-5M5 16v4h14v-4',shield:'M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7l-9-4Zm-4 9 3 3 5-6'};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[kind]}/></svg>;}
interface Form {min:string;max:string;daily:boolean;limit:string;at:string;revision:number}
const formOf=(c:Record<string,any>):Form=>({min:String(c.min_seconds),max:String(c.max_seconds),daily:c.daily_limit!==null,limit:String(c.daily_limit??1000),at:c.processing_time,revision:c.revision});
export default function CollectionDashboard(){
 const [data,setData]=useState<CollectionStatus|null>(null),[form,setForm]=useState<Form|null>(null),[stale,setStale]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState('all'),[expanded,setExpanded]=useState<string|null>(null),[ack,setAck]=useState(false),[now,setNow]=useState(Date.now()),[showRecovery,setShowRecovery]=useState(false);
 const dirtyRef=useRef(false),refreshing=useRef(false),controller=useRef<AbortController|null>(null),offset=useRef(0),mounted=useRef(true);
 const refresh=useCallback(async(force=false,resetForm=force)=>{if(refreshing.current){if(!force)return;controller.current?.abort();}refreshing.current=true;const ac=new AbortController();controller.current=ac;const timeout=setTimeout(()=>ac.abort(),8000);
  try{const res=await fetch('/api/admin/collection',{cache:'no-store',signal:ac.signal});if(!res.ok)throw Error();const next:CollectionStatus=await res.json();if(!mounted.current||controller.current!==ac)return;offset.current=new Date(next.control!.server_now).getTime()-Date.now();setNow(Date.now()+offset.current);setData(next);setStale(false);if(!dirtyRef.current||resetForm){setForm(formOf(next.control!));dirtyRef.current=false;}}
  catch{if(mounted.current&&controller.current===ac)setStale(true);}finally{clearTimeout(timeout);if(controller.current===ac)refreshing.current=false;}
 },[]);
 useEffect(()=>{mounted.current=true;void refresh();const id=setInterval(()=>{if(!document.hidden)void refresh();},5000),clock=setInterval(()=>setNow(Date.now()+offset.current),1000);const focus=()=>{void refresh();};window.addEventListener('focus',focus);return()=>{mounted.current=false;controller.current?.abort();clearInterval(id);clearInterval(clock);window.removeEventListener('focus',focus);};},[refresh]);
 async function change(body:Record<string,unknown>){if(!data||stale||saving)return;setSaving(true);setError('');setMessage('');try{const res=await fetch('/api/admin/collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const r=await res.json();if(!res.ok)throw Error(r.error??'Modificarea nu a fost salvată.');if(body.action==='settings')dirtyRef.current=false;else setForm(current=>current&&current.revision===body.revision?{...current,revision:r.revision}:current);setAck(false);setShowRecovery(false);setMessage('Modificarea a fost salvată. Pauza deja începută se păstrează.');await refresh(true,body.action==='settings');}catch(e){setError(e instanceof Error?e.message:'Modificarea nu a fost salvată.');void refresh();}finally{setSaving(false);}}
 if(!data||!form)return <div className="collection-admin"><div className="page-heading"><div><h1>Colectarea datelor</h1><p>Ce preluăm, în ce ritm și când ajunge în aplicație.</p></div><Link href="/admin/conturi">Administrare conturi</Link></div><div className="empty-state" role="status">{stale?'Statusul nu poate fi citit. Verifică conexiunea și migrațiile aplicației.':'Se citește statusul colectării…'}</div>{stale&&<button className="button" onClick={()=>void refresh()}>Reîncearcă</button>}</div>;
 const c=data.control!,dailyReached=c.daily_limit!==null&&Number(data.today.attempts)>=Number(c.daily_limit),workers=data.workers.filter(w=>w.alive),active=data.requests.find(r=>r.outcome==='running'),paused=!!c.paused,maintenance=!!c.maintenance,blocked=!!c.blocked_reason,alive=workers.some(w=>['documents','ingestion'].includes(w.kind));
 const running=!stale&&!paused&&!maintenance&&!blocked&&!dailyReached&&alive;
 const next=Math.max(0,Math.ceil((new Date(c.next_allowed_at??0).getTime()-now)/1000));
 const title=stale?'Nu mai primim statusul serverului.':maintenance?'Site-ul este în mentenanță.':blocked?'Colectarea așteaptă verificarea sursei.':paused?'Colectarea este pe pauză.':dailyReached?'Limita zilnică a fost atinsă.':active?'Preluăm un răspuns din SEAP.':alive?'Coada SEAP este pregătită.':'Colectorul nu este pornit.';
 const description=stale?'Valorile sunt ultima stare cunoscută. Colectarea poate continua pe server.':blocked?String(c.blocked_reason):!alive&&!paused?'Setările sunt salvate. Nu există un worker cu semnal recent.':'Un singur buget pentru date și documente. Nicio cerere în paralel.';
 const dirty=Number(form.min)!==c.min_seconds||Number(form.max)!==c.max_seconds||form.daily!==(c.daily_limit!==null)||form.daily&&Number(form.limit)!==c.daily_limit||form.at!==c.processing_time;
 dirtyRef.current=dirty;
 const valid=Number.isInteger(Number(form.min))&&Number.isInteger(Number(form.max))&&Number(form.min)>=1&&Number(form.max)<=3600&&Number(form.min)<=Number(form.max)&&(!form.daily||Number.isSafeInteger(Number(form.limit))&&Number(form.limit)>=1)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(form.at);
 const conflict=dirty&&form.revision!==c.revision;
 const edit=(patch:Partial<Form>)=>{dirtyRef.current=true;setForm({...form,...patch});setMessage('');};
 const rows=data.requests.filter(r=>filter==='all'||filter==='errors'&&['failed','interrupted'].includes(r.outcome)||r.stream===filter);
 const processingAlive=workers.some(w=>w.kind==='processor');
 return <div className="collection-admin">
 <div className="page-heading"><div><h1>Colectarea datelor</h1><p>Ce preluăm, în ce ritm și când ajunge în aplicație.</p></div><span className={`connection ${stale?'stale':''}`}><i/>{stale?'Status neactualizat':`Actualizat la ${time(c.server_now)}`}</span></div>
 <nav className="section-nav" aria-label="Administrare"><a href="#collection" aria-current="page">Colectare</a><a href="#publication">Publicare</a><a href="#journal">Jurnal de cereri</a><Link href="/admin/conturi">Conturi</Link><span>SEAP · buget comun</span></nav>
 <section className="live-band" id="collection" data-state={stale?'offline':blocked?'blocked':paused?'paused':'live'} aria-labelledby="state-title"><div className="live-copy"><div className="state-line"><span className="live-dot"/><h2 id="state-title">{title}</h2></div><p>{description}</p><div className="current-task"><span>{active?'În curs':'Workers conectați'}</span><strong>{active?`${streamLabels[active.stream]??active.stream} · ${active.method}`:workers.length?workers.map(w=>w.kind==='documents'?'Documente':w.kind==='processor'?'Procesare':'Colectare').filter((v,i,a)=>a.indexOf(v)===i).join(', '):'Niciun semnal în ultimele 30 secunde'}</strong></div></div><div className="next-request"><span>{stale?'Stare necunoscută':running?'Următoarea cerere, cel mai devreme în':'Cereri noi'}</span><strong id="countdown">{running?(active?'În curs':next>0?<>{next}<span> sec</span></>:'La cerere'):stale?'—':'Oprite'}</strong><div className="countdown-track"><div id="countdown-fill" style={{transform:`scaleX(${running?Math.min(1,next/c.max_seconds):0})`}}/></div><small>Interval aleator: {c.min_seconds}–{c.max_seconds} sec</small></div><div className="live-actions"><button id="pause" className="button band-button" disabled={stale||saving||maintenance} onClick={()=>blocked?setShowRecovery(!showRecovery):void change({action:'pause',paused:!paused,revision:c.revision})}><Icon kind={paused||blocked?'play':'pause'}/><span>{blocked?'Verifică și reia':paused?'Reia coada SEAP':'Pune pe pauză'}</span></button><small>Progresul se păstrează.</small></div></section>
 {stale&&<p className="status-notice" role="status">Conexiunea de raportare este întreruptă. Comenzile sunt indisponibile. Încercăm reconectarea automat.</p>}
 {showRecovery&&blocked&&<div className="recovery"><p>{c.blocked_reason}{c.blocked_until&&<> Așteptare obligatorie până la {date(c.blocked_until)}, {time(c.blocked_until)}.</>}</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Am verificat răspunsul SEAP și cauza opririi. Pot relua cererile.</label><button className="button primary" disabled={!ack||saving||stale||c.blocked_until&&new Date(c.blocked_until).getTime()>now} onClick={()=>void change({action:'unblock',acknowledged:true,revision:c.revision})}>Confirmă reluarea</button></div>}
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="policy-note" role="status">{message}</p>}
 <div className="stats"><div><span>Cereri astăzi <small>toate încercările</small></span><strong>{fmt(data.today.attempts)}</strong><p>{fmt(data.today.succeeded)} reușite · {fmt(data.today.failed)} eșuate</p></div><div><span>Înregistrări primite astăzi</span><strong>{fmt(data.today.received)}</strong><p>Din liste; pot include versiuni repetate</p></div><div><span>Înregistrări noi în arhivă astăzi</span><strong>{fmt(data.raw.archived)}</strong><p>Răspunsuri păstrate, după deduplicare</p></div><div><span>Documente în coada de lucru</span><strong>{fmt(data.documents.queued)}</strong><p>{fmt(data.documents.running)} în procesare · separat de coada de date</p></div></div>
 <div className="workspace"><div className="main-column"><section className="streams"><div className="section-heading"><h2>Unde am ajuns</h2><span className="subtle">Recuperare 2026</span></div><p className="section-description">Raportare activă din {date(c.created_at)}. Istoricul vechi nu este declarat complet.</p>
 {(['da','tenders','awards'] as const).map(key=>{const s=data.streams.find(s=>s.stream===key),stopped=(c.paused_streams as string[]).includes(key),run=data.runs.find(r=>r.source===`elicitatie:${key==='da'?'das':key}`);return <div className="stream" key={key}><div className="stream-heading"><h3>{streamLabels[key]}</h3><span className={`badge ${stopped?'warning':'neutral'}`}>{stopped?'Pe pauză':run?.status==='running'?'În curs':s?'Cereri înregistrate':'Neînceput'}</span><button className="icon-button stream-toggle" disabled={stale||saving} aria-pressed={stopped} aria-label={`${stopped?'Reia':'Pune pe pauză'} ${streamLabels[key]}`} onClick={()=>void change({action:'stream',stream:key,paused:!stopped,revision:c.revision})}><Icon kind={stopped?'play':'pause'}/></button></div><p>De la {key==='da'?'1 iulie':'1 ianuarie'} 2026 <span>· {key==='da'?'după data finalizării':'după data publicării'}</span></p><div className="progress-label"><strong>{fmt(s?.attempts)} <span>cereri efectuate</span></strong><span>{fmt(s?.received)} înregistrări primite</span></div>{run&&<p>Ultima rulare: {date(run.window_start)} – {date(run.window_end)} · {run.status==='completed'?'încheiată':run.status==='failed'?'întreruptă':'în lucru'}</p>}</div>;})}
 <p className="footnote">Numărul total de cereri și progresul pe zile/instituții vor fi afișate după inventarierea lotului. Reluarea unui flux permite cererile deja programate; nu pornește o recuperare nouă.</p></section>
 <section id="publication" className="publication"><div className="section-heading"><h2>Din arhivă, în aplicație</h2><span className={`badge ${maintenance?'warning':'neutral'}`}>{maintenance?'Mentenanță':processingAlive?'Procesor conectat':'Procesor zilnic nepornit'}</span></div><div className="schedule"><div><strong id="publish-time">{c.processing_time}</strong><span>ora salvată pentru procesare<br/>Europe/Bucharest</span></div><p>{processingAlive?'Procesorul zilnic este conectat.': 'Programarea este salvată. Procesarea automată trebuie activată pe server după verificarea procedurii de recuperare.'}</p></div><ol className="pipeline"><li className="done"><span/>Colectare</li><li><span/>Procesare</li><li><span/>Verificare</li><li><span/>Publicare</li></ol><div className="publication-note"><Icon kind="shield"/><p>În timpul procesării, paginile publice intră în mentenanță. Administrarea rămâne accesibilă. O eroare nu redeschide site-ul automat.</p></div>{data.publication&&<p className="footnote">Ultima verificare a datelor: {date(data.publication.completed_at??data.publication.started_at)} · {data.publication.status==='ready'?'validată':data.publication.status==='failed'?'nereușită':'în curs'}. Aceasta nu reprezintă data ultimei colectări.</p>}</section></div>
 <aside className="settings"><form onSubmit={e=>{e.preventDefault();if(valid&&!conflict)void change({action:'settings',revision:form.revision,minSeconds:Number(form.min),maxSeconds:Number(form.max),dailyLimit:form.daily?Number(form.limit):null,processingTime:form.at});}}><div className="section-heading"><h2>Ritmul colectării</h2><Icon kind="settings"/></div><p className="section-description">Se aplică tuturor cererilor SEAP, inclusiv documentelor cerute de utilizatori.</p><fieldset><legend>Pauză aleatoare între cereri</legend><div className="delay-fields"><label>Minimum<div className="unit-input"><input id="delay-min" type="number" min="1" max="3600" step="1" required value={form.min} onChange={e=>edit({min:e.target.value})}/><span>sec</span></div></label><span className="range-dash">–</span><label>Maximum<div className="unit-input"><input id="delay-max" type="number" min="1" max="3600" step="1" required value={form.max} onChange={e=>edit({max:e.target.value})}/><span>sec</span></div></label></div><div className="presets">{[[50,70],[90,120],[120,180]].map(([min,max])=><button key={min} type="button" className={`preset ${Number(form.min)===min&&Number(form.max)===max?'selected':''}`} onClick={()=>edit({min:String(min),max:String(max)})}>{min}–{max} sec</button>)}</div><div className="rate-estimate"><strong>{valid?`≈ ${fmt(Math.round(7200/(Number(form.min)+Number(form.max))))} cereri / oră`:'Interval nevalid'}</strong><span>{Number(form.min)<50?'Mai rapid decât intervalul convenit de 50–70 sec.':'La ritm continuu, fără mentenanță.'}</span></div></fieldset>
 <div className="setting-row"><label htmlFor="daily-enabled">Limită zilnică de cereri<small>Include încercările eșuate. Reset la 00:00.</small></label><input className="switch" role="switch" id="daily-enabled" type="checkbox" checked={form.daily} onChange={e=>edit({daily:e.target.checked})}/></div>{form.daily&&<label className="extra-field">Maximum de încercări pe zi<input id="daily-limit" type="number" min="1" max="10000000" step="1" required value={form.limit} onChange={e=>edit({limit:e.target.value})}/></label>}
 <div className="setting-row"><label htmlFor="maintenance-time">Procesarea zilnică<small>Ora locală, inclusiv schimbarea orei.</small></label><input id="maintenance-time" type="time" required value={form.at} onChange={e=>edit({at:e.target.value})}/></div><details className="guardrails"><summary>Reguli care rămân active</summary><ul><li>O singură cerere SEAP în fiecare moment.</li><li>Minimum 60 secunde între preluările de fișiere.</li><li>Oprire la 403, 429 sau verificare suplimentară.</li><li>Fără reîncercări automate și fără PDF-uri preluate automat.</li></ul></details>
 {dirty&&<p className="settings-diff">Interval: {c.min_seconds}–{c.max_seconds} → {form.min}–{form.max} sec. {form.at!==c.processing_time&&`Procesare: ${c.processing_time} → ${form.at}.`}</p>}{conflict&&<p className="form-error" role="alert">Alt administrator a modificat setările. Reîncarcă valorile înainte de aplicare.</p>}{dirty&&!valid&&<p className="form-error" role="alert">Verifică intervalul, limita zilnică și ora procesării.</p>}
 <button id="apply" className="button primary apply" disabled={!dirty||!valid||conflict||saving||stale}>{saving?'Se salvează…':dirty?'Aplică modificările':'Setările sunt la zi'}</button>{(dirty||conflict)&&<button type="button" className="text-button discard" onClick={()=>{dirtyRef.current=false;setForm(formOf(c));}}>Reîncarcă setările salvate</button>}<p className="save-hint">Modificările se aplică următoarelor cereri, fără a scurta pauza deja începută. Nu pornesc colectorul sau procesorul.</p></form></aside></div>
 <section id="journal" className="journal"><div className="section-heading"><div><h2>Fiecare cerere, la vedere</h2><p className="section-description">Liste, detalii, documente și încercări eșuate — toate consumă același buget.</p></div><a className="button" href="/api/admin/collection?export=1" aria-disabled={stale}><Icon kind="download"/>Exportă jurnalul</a></div><div className="journal-filters" role="group" aria-label="Filtrează jurnalul">{[['all','Toate'],['da','Achiziții directe'],['tenders','Participare'],['awards','Atribuiri'],['documents','Documente'],['errors','Erori']].map(([value,label])=><button key={value} className={`filter ${filter===value?'active':''}`} aria-pressed={filter===value} onClick={()=>{setFilter(value!);setExpanded(null);}}>{label}</button>)}</div>
 {!rows.length?<p className="empty-state">{filter==='all'?'Nu există încă cereri în noul jurnal. Datele istorice rămân disponibile în aplicație.':'Nicio cerere în ultimele 100 de încercări pentru acest filtru.'}</p>:<div className="log-scroll"><table><thead><tr><th>Ora</th><th>Cererea</th><th>Rezultat</th><th>Durată</th><th><span className="sr-only">Detalii</span></th></tr></thead><tbody>{rows.map(r=><RequestRows key={r.id} row={r} expanded={expanded===r.id} toggle={()=>setExpanded(expanded===r.id?null:r.id)}/>)}</tbody></table></div>}<p className="footnote">Ultimele 100 de încercări. Exportul include maximum 5.000. Orele sunt în Europe/Bucharest. Jurnalul nu conține cookie-uri, tokenuri sau linkuri temporare de fișiere.</p></section>
 <section className="changes"><h2>Ultimele modificări de configurare</h2>{!data.audit.length?<p className="empty-state">Nicio modificare. Configurația inițială: 50–70 secunde, coada pe pauză.</p>:<ul>{data.audit.map(a=><li key={a.id}><time dateTime={String(a.created_at)}>{date(a.created_at)} · {time(a.created_at)}</time><span>{a.actor_name} · {auditText(a)}</span></li>)}</ul>}</section>
 </div>;
}
function auditText(a:Record<string,any>){const b=a.before,n=a.after;if(a.action==='settings')return `Interval ${b.minSeconds}–${b.maxSeconds} → ${n.minSeconds}–${n.maxSeconds} sec; procesare ${n.processingTime}; ${n.dailyLimit?`limită ${fmt(n.dailyLimit)}/zi`:'fără limită zilnică'}.`;if(a.action==='pause')return n.paused?'Coada SEAP pusă pe pauză.':'Coada SEAP reluată.';if(a.action==='unblock')return 'Blocarea sursei verificată și reluare confirmată.';return `Fluxuri pe pauză: ${n.pausedStreams.length?n.pausedStreams.map((s:string)=>streamLabels[s]??s).join(', '):'niciunul'}.`;}
function RequestRows({row:r,expanded,toggle}:{row:Record<string,any>;expanded:boolean;toggle:()=>void}){return <><tr><td title={date(r.started_at)}>{time(r.started_at)}</td><td>{streamLabels[r.stream]??r.stream}<small>{r.method} · {r.endpoint.split('/').filter(Boolean).slice(-2).join('/')}</small></td><td><span className={`result ${['failed','interrupted'].includes(r.outcome)?'error':''}`}>{r.outcome==='running'?'În curs':`${r.status??'—'} · ${r.outcome==='success'?'reușit':r.outcome==='interrupted'?'întrerupt':'eșuat'}`}</span></td><td>{r.duration_ms!==null?`${(Number(r.duration_ms)/1000).toFixed(1)} s`:'—'}</td><td><button className="icon-button log-toggle" aria-expanded={expanded} aria-controls={`request-${r.id}`} aria-label={`Detalii cerere ${r.id}`} onClick={toggle}><Icon kind="down"/></button></td></tr>{expanded&&<tr className="log-detail" id={`request-${r.id}`}><td colSpan={5}><p><b>{r.method}</b> <code>{r.endpoint}</code></p><p>{date(r.started_at)} · {time(r.started_at)} · {r.bytes===null?'Dimensiune necunoscută':`${fmt(r.bytes)} octeți`}</p><pre>{JSON.stringify(r.parameters,null,2)}</pre>{r.error&&<p>{r.error}</p>}</td></tr>}</>;}
