import type {CollectionStatus} from '@/lib/admin/collection';
const timestamp=(value:unknown)=>value?new Date(String(value)).toLocaleString('ro-RO',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Bucharest'}):'—';
const count=(value:unknown)=>new Intl.NumberFormat('ro-RO').format(Number(value??0));
export default function ProcessingOverview({data}:{data:CollectionStatus}){
 const c=data.control!,latest=data.publication,verified=data.lastVerified;
 const active=data.workers.find(w=>w.alive&&w.kind==='processor'&&w.state!=='complete');
 const ted=Array.isArray(verified?.checks)?verified.checks.find((check:{check:string})=>check.check==='ted_normalization'):null;
 const actionLabels:Record<string,string>={'replay-ted':'Reprocesăm istoricul TED','seed-legal-eras':'Pregătim pragurile pentru calcul','monitoring-refresh':'Recalculăm și verificăm datele','index-search':'Actualizăm căutarea'};
 return <section className="publication" id="publication"><div className="section-heading"><h2>Procesare și publicare</h2><span className={`badge ${c.maintenance?'warning':'neutral'}`}>{c.maintenance?'Mentenanță':active?'Procesare în curs':'Site disponibil'}</span></div>
  {(c.maintenance||active)&&<p className="processing-current" role="status">{active?(actionLabels[active.state]??'Procesare în curs pe server'):'Actualizarea este în pregătire sau așteaptă verificarea operatorului.'} Site-ul se redeschide după verificări.</p>}
  <div className="processing-schedule"><div><strong>Zilnic <span>· {c.processing_time}</span></strong><p>Date noi, asocieri TED–SEAP, tabele statistice, Radiografie și căutare.</p></div><div><strong>Săptămânal</strong><p>Recalcularea completă a semnalelor de risc. Ziua de rulare urmează să fie stabilită.</p></div></div>
  <p className="processing-plan"><strong>Program convenit · automatizare neactivată</strong><span>Separarea rulărilor zilnice și săptămânale necesită încă implementare și validare. Ora salvată nu pornește singură procesarea.</span></p>
  <dl className="processing-freshness"><div><dt>Ultima recalculare completă verificată</dt><dd>{verified?timestamp(verified.completed_at):'Nicio publicare completă verificată înregistrată'}</dd></div><div><dt>Semnale de risc</dt><dd>{verified?`Incluse în verificarea din ${timestamp(verified.completed_at)}`:'Așteaptă o recalculare completă verificată'}</dd></div>{ted&&<div><dt>Istoric TED verificat</dt><dd>{count(ted.details.total)} anunțuri · {count(ted.details.pending)} în așteptarea normalizării</dd></div>}</dl>
  {latest&&latest.status==='failed'&&<p className="publication-note">{latest.kind==='manual'?'O etapă separată a modificat datele. Publicarea așteaptă recalcularea și verificarea completă.':'Ultima actualizare nu a trecut toate verificările. Publicarea așteaptă rezolvarea erorii.'}</p>}
  <details className="processing-decisions"><summary>Deciziile de colectare și protecție a datelor</summary><ul><li>Interval comun de {c.min_seconds}–{c.max_seconds} secunde pentru date și documente.</li><li>La o cerere eșuată, colectarea se oprește. Diagnosticul disponibil se păstrează în jurnal, cu datele de autentificare mascate.</li><li>Pauza SEAP din jurul orei 03:00 este o ipoteză în observație. Nu este programată o oprire automată la acea oră.</li><li>Înaintea publicării: oprirea colectării, backup, recalculare, verificări și actualizarea căutării. La eroare, mentenanța rămâne activă.</li><li>Data calculului de risc trebuie urmărită separat de data actualizării statisticilor. Programul săptămânal va păstra această distincție.</li></ul></details>
 </section>;
}
