import type {CollectionStatus} from '@/lib/admin/collection';
const timestamp=(value:unknown)=>value?new Date(String(value)).toLocaleString('ro-RO',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Bucharest'}):'—';
const count=(value:unknown)=>new Intl.NumberFormat('ro-RO').format(Number(value??0));
const duration=(start:unknown,end:unknown)=>{const seconds=Math.max(0,Math.round(((end?new Date(String(end)).getTime():Date.now())-new Date(String(start)).getTime())/1000));return seconds>=3600?`${Math.floor(seconds/3600)} h ${Math.floor(seconds%3600/60)} min`:`${Math.floor(seconds/60)} min ${seconds%60} s`;};
const days=['Duminică','Luni','Marți','Miercuri','Joi','Vineri','Sâmbătă'];
const stages:Record<string,string>={drain:'Încheiem cererile și fișierele în curs',backup:'Salvăm copia de siguranță',normalize:'Procesăm datele noi',reconcile:'Asociem TED cu SEAP','ted-mart':'Actualizăm datele TED',marts:'Refacem tabelele statistice',flags:'Recalculăm semnalele de risc','flag-marts':'Actualizăm profilurile de risc',transactions:'Actualizăm listele de achiziții și totalurile',radiografie:'Refacem Radiografia',coverage:'Verificăm acoperirea datelor',validation:'Verificăm consistența rezultatelor',search:'Actualizăm căutarea',restart:'Pregătim redeschiderea site-ului',reopen:'Redeschidem site-ul',complete:'Publicare încheiată'};
export default function ProcessingOverview({data}:{data:CollectionStatus}){
 const c=data.control!,latest=data.publication,verified=data.lastVerified;
 const runs=data.processing?.runs??[],run=runs[0],schedule=data.processing?.schedule;
 const current=run?.status==='running'?run:null;
 const active=data.workers.find(w=>w.alive&&w.kind==='processor'&&w.state!=='complete');
 const ted=Array.isArray(verified?.checks)?verified.checks.find((check:{check:string})=>check.check==='ted_normalization'):null;
 const actionLabels:Record<string,string>={'replay-ted':'Reprocesăm istoricul TED','seed-legal-eras':'Pregătim pragurile pentru calcul','monitoring-refresh':'Recalculăm și verificăm datele','index-search':'Actualizăm căutarea'};
 return <section className="publication" id="publication"><div className="section-heading"><h2>Procesare și publicare</h2><span className={`badge ${c.maintenance?'warning':'neutral'}`}>{c.maintenance?'Mentenanță':active?'Procesare în curs':'Site disponibil'}</span></div>
  {(c.maintenance||active||current)&&<p className="processing-current" role="status">{current?`${stages[current.stage]??current.stage} · ${duration(current.started_at,null)} de la pornire.`:active?(actionLabels[active.state]??'Procesare în curs pe server'):'Actualizarea este în pregătire sau așteaptă verificarea operatorului.'} Site-ul se redeschide după verificări.</p>}
  {current&&Date.now()-new Date(String(current.heartbeat_at)).getTime()>120000&&<p className="publication-note" role="alert">Nu mai primim semnal de la procesare. Verifică serverul; mentenanța rămâne activă.</p>}
  <div className="processing-schedule"><div><strong>Zilnic <span>· {c.processing_time}</span></strong><p>Date noi, asocieri TED–SEAP, tabele statistice, Radiografie și căutare.</p></div><div><strong>{days[c.risk_weekday??0]} <span>· {c.processing_time}</span></strong><p>Actualizarea zilnică include și recalcularea completă a semnalelor de risc.</p></div></div>
  <p className={`processing-plan ${c.processing_enabled&&data.processing?.schedulerAlive&&!c.maintenance?'is-enabled':''}`}><strong>{c.processing_enabled?current?'Rulare programată în curs':data.processing?.schedulerAlive?'Program automat activ':'Program activ · serviciu fără semnal recent':'Program automat oprit'}</strong><span>{c.processing_enabled?`Următoarea actualizare: ${timestamp(schedule?.next_at)}. Cu recalcularea riscului: ${timestamp(schedule?.next_risk_at)}. Orele sunt ale României.`:'Datele existente rămân disponibile. Activează programul din setări pentru rulările viitoare.'}{c.maintenance?' Nicio rulare nouă nu începe cât timp mentenanța este activă.':''}</span></p>
  <dl className="processing-freshness"><div><dt>Date și statistici verificate</dt><dd>{verified?timestamp(verified.completed_at):'Nicio publicare completă verificată înregistrată'}</dd></div><div><dt>Semnale de risc recalculate</dt><dd>{verified?timestamp(verified.risk?.calculatedAt??verified.completed_at):'Așteaptă o recalculare completă verificată'}</dd></div>{ted&&<div><dt>Istoric TED verificat</dt><dd>{count(ted.details.total)} anunțuri · {count(ted.details.pending)} în așteptarea normalizării</dd></div>}</dl>
  {run?.status==='failed'&&<p className="publication-note" role="alert">Procesarea s-a oprit: {stages[run.stage]??run.stage}. Mentenanța se păstrează. Verifică jurnalul de pe server înainte de recuperare; nu reîncercăm automat.</p>}
  {runs.length>0&&<details className="processing-decisions"><summary>Ultimele rulări și durata fiecărei etape</summary><ul>{runs.map(r=><li key={r.id}><strong>{timestamp(r.started_at)} · {r.scope==='full'?'Inclusiv risc':'Date și statistici'}</strong><p>{r.status==='ready'?'Publicată':r.status==='failed'?'Oprită la eroare':'În curs'} · {duration(r.started_at,r.completed_at)}</p><dl className="processing-stage-times">{Object.entries(r.stages??{}).map(([key,v])=><div key={key}><dt>{stages[key]??key}</dt><dd>{duration((v as any).startedAt,(v as any).completedAt)}</dd></div>)}</dl></li>)}</ul></details>}
  {latest&&latest.status==='failed'&&<p className="publication-note">{latest.kind==='manual'?'O etapă separată a modificat datele. Publicarea așteaptă recalcularea și verificarea completă.':'Ultima actualizare nu a trecut toate verificările. Publicarea așteaptă rezolvarea erorii.'}</p>}
  <details className="processing-decisions"><summary>Deciziile de colectare și protecție a datelor</summary><ul><li>Interval comun de {c.min_seconds}–{c.max_seconds} secunde pentru date și documente.</li><li>La o cerere eșuată, colectarea se oprește. Diagnosticul disponibil se păstrează în jurnal, cu datele de autentificare mascate.</li><li>Pauză preventivă SEAP zilnică: 02:59–03:30, ora României, pentru date și fișiere. Cererile deja începute pot încheia răspunsul; cele noi așteaptă. Reluarea automată păstrează pauzele manuale și blocajele de eroare.</li><li>Înaintea publicării: oprirea colectării, backup, recalculare, verificări și actualizarea căutării. La eroare, mentenanța rămâne activă.</li><li>Rularea zilnică păstrează data calculului de risc și reverifică dovezile existente. Dacă acestea nu mai corespund surselor, publicarea se oprește.</li></ul></details>
 </section>;
}
