'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {CollectionStatus} from '@/lib/admin/collection';

type Draft={enabled:boolean;min:string;max:string;cap:string;ids:string[];revision:number};
const initial=(data:CollectionStatus):Draft=>({enabled:!!data.proxies.settings.enabled,min:String(data.proxies.settings.min_seconds),max:String(data.proxies.settings.max_seconds),cap:String(data.proxies.settings.requests_per_minute),ids:data.proxies.endpoints.filter(p=>p.enabled).map(p=>String(p.id)),revision:Number(data.control.revision)});
const number=(v:unknown)=>new Intl.NumberFormat('ro-RO',{maximumFractionDigits:1}).format(Number(v??0));
export default function ProxyControl({data,now,stale,saving,change,onDirtyChange}:{data:CollectionStatus;now:number;stale:boolean;saving:boolean;change:(body:Record<string,unknown>)=>Promise<boolean|undefined>;onDirtyChange:(dirty:boolean)=>void}){
 const [draft,setDraft]=useState<Draft|null>(null),[page,setPage]=useState(1);
 useEffect(()=>{onDirtyChange(!!draft);},[!!draft,onDirtyChange]);
 const saved=initial(data),form=draft??saved,conflict=!!draft&&draft.revision!==Number(data.control.revision);
 const endpoints=data.proxies.endpoints,policy=data.proxies.settings;
 const active=endpoints.filter(p=>p.enabled).length;
 const editable=!!data.control.paused&&!data.control.maintenance&&!Number(data.documents.running)&&!data.requests.some(r=>r.outcome==='running')&&!stale&&!saving;
 const edit=(patch:Partial<Draft>)=>setDraft({...form,...patch});
 const valid=Number.isInteger(Number(form.min))&&Number.isInteger(Number(form.max))&&Number(form.min)>=1&&Number(form.max)>=Number(form.min)&&Number(form.max)<=3600&&Number.isInteger(Number(form.cap))&&Number(form.cap)>=1&&Number(form.cap)<=15&&(!form.enabled||form.ids.length>0);
 const capacity=Math.min(Number(form.cap),form.ids.length*120/(Number(form.min)+Number(form.max)));
 useEffect(()=>{if(!draft)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft]);
 return <section className="proxy-control" aria-labelledby="proxy-title">
  <div className="section-heading"><div><h2 id="proxy-title">Conexiunea cu SEAP</h2><p className="section-description">{policy.enabled?`${active} proxy-uri active · IP-ul serverului nu este folosit de colector.`:data.proxies.directAllowed?'Conexiune directă · proxy-urile nu sunt activate.':'Proxy-uri neactivate · conexiunea directă este blocată.'}</p></div><span className={`badge ${stale?'warning':policy.enabled?'neutral':'warning'}`}>{stale?'Status neactualizat':policy.enabled?'Prin proxy':data.proxies.directAllowed?'Direct':'Fără conexiune'}</span></div>
  <dl className="proxy-summary"><div><dt>Ritm observat</dt><dd>{stale?'—':number(data.proxies.observedPerMinute)} <small>cereri/min</small></dd><span>Media ultimelor 10 minute, inclusiv pauzele</span></div><div><dt>{policy.enabled?'Plafon total':'Pauză între cereri'}</dt><dd>{policy.enabled?policy.requests_per_minute:`${data.control.min_seconds}–${data.control.max_seconds}`} <small>{policy.enabled?'cereri/min':'sec'}</small></dd><span>{policy.enabled?`${policy.min_seconds}–${policy.max_seconds} secunde între cereri pe același IP`:'Același buget pentru date și documente'}</span></div></dl>
  <details className="proxy-settings" open><summary>Configurează conexiunea și ritmul</summary>
   {!editable&&<p className="policy-note">{stale?'Reconectarea la server este necesară pentru modificări.':'Pune colectarea pe pauză și așteaptă încheierea cererii sau documentului activ pentru a modifica setările.'} {!stale&&<Link href="/admin" scroll={false}>Vezi colectarea</Link>}</p>}
   {!endpoints.length&&<p className="policy-note">Niciun proxy înregistrat. Lista se instalează pe server; parolele nu se introduc în această pagină.</p>}
   <form onSubmit={async e=>{e.preventDefault();if(valid&&editable&&!conflict&&await change({action:'proxies',revision:form.revision,enabled:form.enabled,minSeconds:Number(form.min),maxSeconds:Number(form.max),requestsPerMinute:Number(form.cap),activeIds:form.ids}))setDraft(null);}}>
    <fieldset disabled={!editable}><legend>Traseul cererilor</legend><div className="proxy-modes"><label><input type="radio" name="proxy-mode" disabled={!data.proxies.directAllowed} checked={!form.enabled} onChange={()=>edit({enabled:false})}/>Direct</label><label><input type="radio" name="proxy-mode" checked={form.enabled} disabled={!endpoints.length} onChange={()=>edit({enabled:true})}/>Prin proxy-uri</label></div>
    <div className="proxy-fields"><label>Pauză minimă / IP <span>secunde</span><input type="number" min="1" max="3600" step="1" required value={form.min} onChange={e=>edit({min:e.target.value})}/></label><label>Pauză maximă / IP <span>secunde</span><input type="number" min={form.min||1} max="3600" step="1" required value={form.max} onChange={e=>edit({max:e.target.value})}/></label><label>Plafon total <span>cereri / minut</span><input type="number" min="1" max="15" step="1" required value={form.cap} onChange={e=>edit({cap:e.target.value})}/></label></div>
    {endpoints.length>0&&<fieldset className="proxy-picks"><legend>Proxy-uri folosite</legend>{endpoints.map(p=><label key={p.id}><input type="checkbox" checked={form.ids.includes(p.id)} onChange={e=>edit({ids:e.target.checked?[...form.ids,p.id]:form.ids.filter(id=>id!==p.id)})}/>{p.id}<small>{p.exit_ip}</small></label>)}</fieldset>}
    </fieldset>
    {form.enabled&&valid&&<p className="proxy-estimate">Capacitate teoretică: până la <strong>{number(capacity)} cereri/min</strong>. Pauzele, documentele și timpul de răspuns pot reduce ritmul.</p>}
    {conflict&&<p role="alert" className="form-error">Configurația s-a schimbat între timp. Reîncarcă setările înainte de aplicare.</p>}
    <div className="proxy-form-actions"><button className="button primary" disabled={!draft||!valid||conflict||!editable}>{saving?'Se salvează…':'Aplică setările conexiunii'}</button>{draft&&<button className="text-button" type="button" onClick={()=>setDraft(null)}>Renunță la modificări</button>}</div>
    <p className="footnote">Salvarea păstrează colectarea pe pauză și nu scurtează așteptarea deja începută.</p>
   </form>
  </details>
  {endpoints.length>0&&<><div className="proxy-table-scroll"><table className="proxy-table"><caption>Proxy-uri înregistrate · cereri și trafic de astăzi</caption><thead><tr><th>Proxy / IP</th><th>Stare</th><th>Cereri</th><th>Erori</th><th>Răspunsuri</th></tr></thead><tbody>{endpoints.slice((page-1)*10,page*10).map(p=>{const seconds=Math.max(0,Math.ceil((new Date(p.next_allowed_at??0).getTime()-now)/1000));return <tr key={p.id}><th scope="row">{p.id}<small>{p.exit_ip}</small></th><td>{stale?'Necunoscută':!p.enabled?(Number(p.consecutive_failures)>=3?'Oprit după erori':'Neutilizat'):!policy.enabled?'Pool oprit':p.job_status==='running'?<span className="proxy-reserved">Rezervat unui document</span>:p.last_error?<span className="form-error">{seconds?`Pauză după eroare · ${seconds} sec`:'De verificat'}</span>:seconds?`Disponibil în ${seconds} sec`:'Disponibil'}{p.last_error&&<small>{p.last_error}</small>}</td><td><span className="proxy-mobile-label" aria-hidden="true">Cereri</span>{number(p.attempts)}</td><td><span className="proxy-mobile-label" aria-hidden="true">Erori</span>{number(p.failed)}</td><td><span className="proxy-mobile-label" aria-hidden="true">Răspunsuri</span>{number(Number(p.bytes)/1048576)} MB</td></tr>;})}</tbody></table></div>{endpoints.length>10&&<nav className="queue-pagination" aria-label="Paginile proxy-urilor"><span>Pagina {page} din {Math.ceil(endpoints.length/10)}</span><button className="button" disabled={page===1} onClick={()=>setPage(page-1)}>Înapoi</button><button className="button" disabled={page*10>=endpoints.length} onClick={()=>setPage(page+1)}>Următoarele</button></nav>}<p className="footnote">Traficul reprezintă răspunsurile măsurate de aplicație, nu consumul facturat de furnizor.</p></>}
  <p className="proxy-rule">O singură cerere în curs. Documentele păstrează același IP până la finalul descărcării; minimum un minut între fișiere. Un refuz SEAP oprește întreaga colectare.</p>
 </section>;
}
