import type {CollectionStatus} from '@/lib/admin/collection';
const fmt=(v:number)=>new Intl.NumberFormat('ro-RO').format(v);
export default function RecoveryOverview({data,stale}:{data:CollectionStatus;stale:boolean}){
 const f=data.forecast,c=data.control!;
 if(!f||!data.recovery)return <section className="recovery-overview"><h2>Recuperarea, în ansamblu</h2><p>Niciun lot de recuperare înregistrat. Procentul și termenul vor apărea după inventariere.</p></section>;
 const end=String(data.recovery.batch.end_day),paused=c.paused||c.blocked_reason||(c.paused_streams as string[]).some(s=>['da','tenders','awards','catalogue'].includes(s));
 const alive=data.workers.some(w=>w.alive&&w.kind==='ingestion'),waiting=c.maintenance||data.quietWindow.active||data.timeoutRetry||c.daily_limit!==null&&Number(data.today.attempts)>=c.daily_limit;
 const suspend=stale||paused||!alive;
 const title=f.state==='complete'?'Lotul configurat este colectat.':f.state==='gaps'?'Există goluri care necesită rezolvare.':suspend?'Termenul nu poate fi actualizat acum.':f.daysLow!==null&&f.daysHigh!==null?`${waiting?'Ultima estimare':'Aproximativ'}: ${f.daysLow===f.daysHigh?f.daysHigh:`${f.daysLow}–${f.daysHigh}`} zile pentru acest lot`:'Strângem date pentru o estimare.';
 return <section className="recovery-overview" aria-labelledby="recovery-title"><div className="recovery-heading"><h2 id="recovery-title">Recuperarea, în ansamblu</h2><span>Lot până la {end} · {f.state==='complete'?'verificat în coadă':'estimare preliminară'}</span></div><div className="recovery-estimate"><div className="recovery-percent"><strong>{f.percent===null?'În evaluare':`${f.state==='complete'?'':'≈ '}${f.percent}%`}</strong>{f.percent!==null&&<span>din munca estimată a lotului</span>}</div><div><h3>{title}</h3><p>{f.state==='gaps'?`${fmt(f.deferred)} detalii nepreluate și ${fmt(f.failed)} sarcini eșuate. Nu putem estima o recuperare completă până la rezolvarea lor.`:f.state==='complete'?'Colectarea lotului nu include zilele de după data sa finală. Publicarea are propriile verificări.':stale?'Valorile sunt ultima stare cunoscută. Așteptăm reconectarea.':paused?'Progresul se păstrează. Termenul se reia după deblocarea tuturor fluxurilor.':!alive?'Colectorul nu are semnal recent. Așteptăm reluarea raportării.':waiting?'Cereri noi în așteptare. Pauzele sunt incluse în ritmul calendaristic observat.':f.daysLow===null?'Avem nevoie de un eșantion din fiecare flux și de cel puțin 24 de ore de ritm observat.':'Pe baza volumului descoperit și a ritmului real din ultimele maximum 7 zile.'}</p></div></div>
 {f.percent!==null&&<progress max={100} value={f.percent} aria-label="Progres total estimat al lotului"/>}
 <div className="recovery-caption"><span>{fmt(f.completed)} pași încheiați · {fmt(f.pending)} cereri cunoscute în așteptare</span><span>Colectare și partiționare · fără încercări eșuate</span></div>
 <details className="forecast-method"><summary>Pe ce se bazează estimarea?</summary><p>Estimăm separat cererile pentru instituții, zile de anunțuri, detalii și contracte, apoi adunăm volumul. Nu facem media procentelor celor trei fluxuri. Cererile de împărțire a ferestrelor sunt muncă încheiată, nu contracte arhivate.</p>
 <dl><div><dt>Pași încheiați din coada cunoscută</dt><dd>{fmt(f.completed)} / {fmt(f.known)}{f.knownPercent!==null?` (${f.knownPercent}%)`:''}</dd></div><div><dt>Cereri rămase estimate, inclusiv încă nedescoperite</dt><dd>{f.remainingLow===null?'Eșantion insuficient':`${fmt(f.remainingLow)}–${fmt(f.remainingHigh!)}`}</dd></div><div><dt>Ritm util observat, cu pauze și trafic de fișiere</dt><dd>{f.rate===null?'Mai avem nevoie de observații':`≈ ${fmt(f.rate)} pași / zi`}</dd></div></dl>
 <p>Eșantion minim: 100 de instituții și 20 de zile pe flux, cel puțin 10% din unitățile fiecărui flux, plus până la trei luni distincte pentru anunțuri (sau toate unitățile, dacă lotul este mai mic). Catalogul trebuie încheiat. Intervalul de zile este un scenariu de planificare, nu o probabilitate garantată: permite variații de cel puțin 25% ale volumului și ritmului. Volumul și procentul se pot revizui când descoperim cereri noi.</p>
 <p><b>Acest colector are un lot cu dată finală fixă.</b> Termenul se referă la lotul până la {end}, nu la toate datele apărute ulterior și nu certifică întreg istoricul SEAP. Nu afișăm „la zi” fără o recuperare a zilelor noi. Datele devin vizibile după procesare și validare.</p></details></section>;
}
