"use client";
import { useEffect, useId, useState } from "react";
import type { EntityHit } from "@/lib/search";
import { COUNTIES } from "@/lib/counties";
import { validatePopulation, type PopulationCondition, type QueryPopulation } from "@/lib/ask/population";
import "./query-recipes.css";

const fields = { date:"Data achiziției", value:"Valoare pe înregistrare (lei)", authority:"Instituții", supplier:"Firme", cpv:"Coduri CPV", county:"Județele cumpărătorilor" };
const blank = (): PopulationCondition => ({ field:"value", op:"gte", value:"" });

function EntitySet({ condition, onChange, disabled }: { condition:Extract<PopulationCondition, { values:string[] }>; onChange:(value:PopulationCondition)=>void; disabled:boolean }) {
  const [search, setSearch] = useState("");
  const [hits, setHits] = useState<EntityHit[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController(); setHits([]); setError("");
    if (search.trim().length < 2) { setBusy(false); return () => controller.abort(); }
    setBusy(true);
    const timer = setTimeout(async () => {
      try {
        const response = await fetch(`/api/search?q=${encodeURIComponent(search.trim())}`, { signal:controller.signal });
        if (!response.ok) throw new Error("Căutarea nu este disponibilă. Încearcă din nou.");
        const data = await response.json() as { hits:EntityHit[] };
        if (!controller.signal.aborted) setHits(data.hits.filter(h => h.roles.includes(condition.field)));
      } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : "Căutare indisponibilă."); }
      finally { if (!controller.signal.aborted) setBusy(false); }
    }, 250);
    return () => { controller.abort(); clearTimeout(timer); };
  }, [search, condition.field]);
  return <div className="qp-entity-set"><div className="qp-selected">{condition.values.map((id, index) => <span key={id}><a href={`/entitati/${id}`} target="_blank" rel="noreferrer">{condition.labels?.[index] ?? `Entitatea #${id}`}</a><button type="button" disabled={disabled} aria-label={`Elimină ${condition.labels?.[index] ?? id}`} onClick={() => onChange({ ...condition, values:condition.values.filter(v => v !== id), labels:condition.values.filter(v => v !== id).map(v => condition.labels?.[condition.values.indexOf(v)] ?? `Entitatea #${v}`) })}>Elimină</button></span>)}</div><label>Caută și adaugă {condition.field === "authority" ? "instituții" : "firme"}<input type="search" autoComplete="off" placeholder="Nume sau CUI" value={search} disabled={disabled || condition.values.length >= 100} onChange={e => { setSearch(e.target.value); setHits([]); setBusy(e.target.value.trim().length >= 2); }} /></label>{search.trim().length >= 2 && <div className="qp-entity-results" aria-busy={busy}><p role="status">{busy ? "Caut în date…" : error || (!hits.length ? "Nicio potrivire. Încearcă numele complet sau CUI-ul." : "Selectează o entitate pentru a o adăuga.")}</p>{!busy && hits.map(hit => <button key={hit.id} type="button" disabled={disabled || condition.values.includes(String(hit.id))} onClick={() => { onChange({ ...condition, values:[...condition.values, String(hit.id)], labels:[...condition.values.map((v, i) => condition.labels?.[i] ?? `Entitatea #${v}`), hit.name] }); setSearch(""); }}><strong>{hit.name}</strong><small>{[hit.cui && `CUI ${hit.cui}`, hit.county].filter(Boolean).join(" · ")}</small></button>)}</div>}</div>;
}

export default function PopulationEditor({ value, onChange, disabled = false }: { value?:QueryPopulation | undefined; onChange:(value:QueryPopulation | undefined)=>void; disabled?:boolean }) {
  const id = useId();
  const [open, setOpen] = useState(Boolean(value));
  const count = value?.groups.reduce((n, g) => n + g.conditions.length, 0) ?? 0;
  const validation = value ? validatePopulation(value) : null;
  function updateGroup(index:number, next:QueryPopulation["groups"][number]) { if (value) onChange({ ...value, groups:value.groups.map((g, i) => i === index ? next : g) }); }
  return <section className="qp-editor" aria-label="Selecție precisă"><button className="qp-toggle" type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpen(v => !v)}><span>Selecție precisă{count > 0 ? ` · ${count} condiții` : ""}</span><span>{open ? "Restrânge" : "Date, valori și grupuri"}</span></button>{open && <div id={id} className="qp-body"><p>Aceste condiții se adaugă celor de mai sus. Răspunsul, sursele și exportul folosesc aceeași selecție.</p>{!value ? <div className="qp-start"><p>De exemplu: achiziții de cel puțin 50.000 lei, dintr-o perioadă exactă, de la câteva firme.</p><button type="button" disabled={disabled} onClick={() => onChange({ operator:"and", groups:[{ operator:"and", conditions:[blank()] }] })}>Adaugă prima condiție</button></div> : <><label className="qp-operator">Între grupuri<select value={value.operator} disabled={disabled} onChange={e => onChange({ ...value, operator:e.target.value as "and" | "or" })}><option value="and">ȘI — trebuie îndeplinite toate grupurile</option><option value="or">SAU — ajunge oricare dintre grupuri</option></select></label>{value.groups.map((group, gi) => <fieldset key={gi} className="qp-group" disabled={disabled}><legend>Grupul {gi + 1}</legend><div className="qp-group-head"><label>În acest grup<select value={group.operator} onChange={e => updateGroup(gi, { ...group, operator:e.target.value as "and" | "or" })}><option value="and">Toate condițiile (ȘI)</option><option value="or">Oricare condiție (SAU)</option></select></label><button type="button" onClick={() => { const groups = value.groups.filter((_, i) => i !== gi); onChange(groups.length ? { ...value, groups } : undefined); }}>Elimină grupul</button></div>{group.conditions.map((condition, ci) => {
      const update = (next:PopulationCondition) => updateGroup(gi, { ...group, conditions:group.conditions.map((c, i) => i === ci ? next : c) });
      return <div className="qp-condition" key={ci}><div className="qp-condition-main"><label>Condiția {ci + 1}<select value={condition.field} onChange={e => { const field = e.target.value as PopulationCondition["field"]; update(field === "date" || field === "value" ? { field, op:"gte", value:"" } : { field, op:"in", values:[] }); }}>{Object.entries(fields).map(([field, label]) => <option key={field} value={field}>{label}</option>)}</select></label><label>Regulă<select value={condition.op} onChange={e => update({ ...condition, op:e.target.value } as PopulationCondition)}>{"value" in condition ? <><option value="gte">Cel puțin / începând cu</option><option value="lte">Cel mult / până la</option></> : <><option value="in">Include oricare din listă</option><option value="not_in">Exclude toate din listă</option></>}</select></label><button type="button" className="qp-remove" aria-label={`Elimină condiția ${ci + 1} din grupul ${gi + 1}`} onClick={() => { const conditions = group.conditions.filter((_, i) => i !== ci); if (conditions.length) updateGroup(gi, { ...group, conditions }); else { const groups = value.groups.filter((_, i) => i !== gi); onChange(groups.length ? { ...value, groups } : undefined); } }}>Elimină</button></div>{"value" in condition ? <label>{condition.field === "date" ? "Data calendaristică (inclusiv)" : "Valoarea în lei, cu punct pentru zecimale"}<input type={condition.field === "date" ? "date" : "text"} inputMode={condition.field === "value" ? "decimal" : undefined} value={condition.value} onChange={e => update({ ...condition, value:e.target.value })} placeholder={condition.field === "value" ? "50000.00" : undefined} /></label> : condition.field === "authority" || condition.field === "supplier" ? <EntitySet condition={condition} onChange={update} disabled={disabled} /> : condition.field === "county" ? <label>Județe (se pot alege mai multe)<select multiple value={condition.values} size={5} onChange={e => update({ ...condition, values:Array.from(e.target.selectedOptions, option => option.value) })}>{COUNTIES.map(county => <option key={county} value={county}>{county}</option>)}</select></label> : <label>Coduri CPV, separate prin virgulă<input value={condition.values.join(", ")} placeholder="45, 7731" onChange={e => update({ ...condition, values:e.target.value.split(",").map(v => v.trim()) })} /><small>Prefixe de 2–8 cifre, fără cifra de control. Un prefix include toate codurile sale.</small></label>}</div>;
    })}<button type="button" disabled={disabled || group.conditions.length >= 8 || count >= 32} onClick={() => updateGroup(gi, { ...group, conditions:[...group.conditions, blank()] })}>Adaugă o condiție în grup</button></fieldset>)}<div className="qp-actions"><button type="button" disabled={disabled || value.groups.length >= 8 || count >= 32} onClick={() => onChange({ ...value, groups:[...value.groups, { operator:"and", conditions:[blank()] }] })}>Adaugă un grup</button><button type="button" disabled={disabled} onClick={() => onChange(undefined)}>Elimină selecția precisă</button></div><p className="qp-note">Excluderile păstrează înregistrările cu identitate sau categorie necunoscută. Valoarea unui contract cu mai mulți câștigători este cota alocată furnizorului, nu valoarea integrală.</p>{validation && "error" in validation && <p role="status" className="qp-error">{validation.error}</p>}</>}</div>}</section>;
}
