'use client';
import { useEffect,useRef } from 'react';
import type { Story,StorySource } from '@/lib/stories/types';
import { dateLabel,sourceHref,sourceLinks,storyHref,storyTotal } from '@/lib/stories/shared';
import { Icon,money } from './StoryParts';
export function SourceRecord({story,source,standalone=false}:{story:Story;source:StorySource;standalone?:boolean}){
 const links=sourceLinks(source);
 const timestamp=(v:string)=>new Date(v).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});
 return <article className="record"><span className="record-tag">{source.kind==='procurement'?'Înregistrare de achiziție':source.kind==='external'?'Sursă externă':'Notă de documentare'}</span>
 <h3>{links.detail?<a href={links.detail} target="_blank" rel="noopener noreferrer">{source.title} <Icon name="external"/></a>:source.title}</h3>
 {source.kind==='procurement'?<><p className="record-amount">{money(source.amount)}</p><dl>{source.code&&<div><dt>Cod SEAP</dt><dd>{source.code}</dd></div>}{source.cpv&&<div><dt>CPV</dt><dd>{source.cpv}</dd></div>}{source.publishedAt&&<div><dt>Publicată · ora României</dt><dd>{timestamp(source.publishedAt)}</dd></div>}{source.finalizedAt&&<div><dt>Finalizată · ora României</dt><dd>{timestamp(source.finalizedAt)}</dd></div>}<div><dt>Data</dt><dd>{dateLabel(source.date)}</dd></div><div><dt>Instituție</dt><dd>{source.authority}</dd></div><div><dt>Furnizor{source.suppliers.length>1?'i':''}</dt><dd>{source.suppliers.join(', ')}</dd></div><div><dt>Documentat</dt><dd>{dateLabel(source.observedAt)}</dd></div></dl><p className="quiet">{story.finding.sourceIds.includes(source.id)?'Inclusă în totalul poveștii.':'Sursă de context — nu este inclusă în total.'} Valoare înregistrată, nu plată.</p>{source.note&&<p>{source.note}</p>}<div className="source-actions">{links.detail&&<a className="text-link" href={links.detail} target="_blank" rel="noopener noreferrer">Detaliile achiziției <Icon name="external"/></a>}{links.official&&<a className="text-link" href={links.official} target="_blank" rel="noopener noreferrer">Verifică în SEAP <Icon name="external"/></a>}</div></>:source.kind==='external'?<><p>{source.summary}</p><p className="quiet">{source.publisher} · Consultat la {dateLabel(source.observedAt)}</p>{links.detail&&<a className="text-link" href={links.detail} target="_blank" rel="noopener noreferrer">Citește la sursă <Icon name="external"/></a>}</>:<p>{source.text}</p>}
 {!standalone&&<a className="text-link" href={sourceHref(story.slug,source.id)} target="_blank" rel="noopener noreferrer">Deschide fișa documentată <Icon name="external"/></a>}
 </article>;
}
export function SourcePage({story,source}:{story:Story;source:StorySource}) {return <div className="document-page"><a className="back-link" href={storyHref(story.slug)}><Icon name="back"/> Înapoi la poveste</a><h1>{source.title}</h1><p className="source-note">{`Fișă păstrată la documentarea poveștii, la ${dateLabel(source.observedAt)}. Sursa poate conține date actualizate ulterior.`}</p><SourceRecord story={story} source={source} standalone/><details><summary>Metodologia selecției</summary><p>{story.methodology}</p></details></div>;}
export default function StoryEvidence({story,sourceId,onClose,onSelect}:{story:Story;sourceId:string;onClose:()=>void;onSelect:(id:string)=>void}){
 const ref=useRef<HTMLDialogElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const dialog=ref.current!,previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow=overflow;previous?.focus({preventScroll:true});};},[]);
 useEffect(()=>{if(ref.current){ref.current.scrollTop=0;ref.current.querySelector<HTMLButtonElement>('[data-close]')?.focus({preventScroll:true});}},[sourceId]);
 const all=sourceId==='all',source=story.sources.find(s=>s.id===sourceId),procurements=story.sources.filter(s=>s.kind==='procurement');
 return <dialog ref={ref} aria-labelledby="story-evidence-title" onCancel={e=>{e.preventDefault();close.current();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close.current();}}}>
 <header className="drawer-head"><div><span>Dosarul poveștii</span><h2 id="story-evidence-title">{all?'Sursele, la vedere':source?.kind==='procurement'?'Înregistrarea sursă':source?.title??'Sursă indisponibilă'}</h2></div><button className="icon-button" data-close aria-label="Închide sursele" onClick={onClose}><Icon name="close"/></button></header>
 <div className="drawer-body"><p className="source-note">Sursele documentării, cu valori și date păstrate. Verifică înregistrarea originală din fiecare fișă.</p>
 {all?<>{story.finding.sourceIds.length>0&&<div className="drawer-total"><b>{money(storyTotal(story))}</b><span>{story.finding.sourceIds.length} {story.finding.sourceIds.length===1?'înregistrare':'înregistrări'} în totalul prezentat</span></div>}{procurements.filter(s=>story.finding.sourceIds.includes(s.id)).map(s=><SourceRecord key={s.id} story={story} source={s}/>)}{procurements.some(s=>!story.finding.sourceIds.includes(s.id))&&<h3>Alte achiziții de context · în afara totalului</h3>}{procurements.filter(s=>!story.finding.sourceIds.includes(s.id)).map(s=><SourceRecord key={s.id} story={story} source={s}/>)}<h3>Context și documentare</h3>{story.sources.filter(s=>s.kind!=='procurement').map(s=><button className="source-context" key={s.id} onClick={()=>onSelect(s.id)}>{s.title}<Icon name="arrow"/></button>)}</>:source?<SourceRecord story={story} source={source}/>:<p>Sursa nu există în dosarul acestei povești.</p>}
 <button className="button return-reading" onClick={onClose}><Icon name="back"/> Continuă lectura</button></div></dialog>;
}
