'use client';
import { useEffect,useRef,useState } from 'react';
import { countyLabel,countyHref,dateLabel,storyTotal } from '@/lib/stories/shared';
import type {Story} from '@/lib/stories/types';
import {Icon,money,StoryCard} from './StoryParts';
import StoryArt from './StoryArt';
export default function StoryArticle({story,stories,openSource}:{story:Story;stories:Story[];openSource:(id:string)=>void}){
 const [chapter,setChapter]=useState('firul'),[copied,setCopied]=useState('');const body=useRef<HTMLDivElement>(null),progress=useRef<HTMLDivElement>(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setChapter(e.target.id);}),{rootMargin:'-15% 0px -65% 0px'});body.current?.querySelectorAll(':scope > section').forEach(s=>observer.observe(s));const scroll=()=>{if(!body.current||!progress.current)return;const max=body.current.getBoundingClientRect().bottom+scrollY-innerHeight;progress.current.style.width=`${Math.min(100,Math.max(0,scrollY/Math.max(1,max)*100))}%`;};addEventListener('scroll',scroll,{passive:true});scroll();return()=>{observer.disconnect();removeEventListener('scroll',scroll);};},[story.slug]);
 const refs=(ids:string[])=>ids.map(id=>{const s=story.sources.find(s=>s.id===id);return s?<button key={id} className="source-ref" onClick={()=>openSource(id)}><Icon name="file"/>{s.title}</button>:null;});
 const records=story.sources.filter(s=>story.finding.sourceIds.includes(s.id)&&s.kind==='procurement');
 const max=Math.max(...records.map(s=>s.kind==='procurement'?Number(s.amount):0),1);
 const related=stories.filter(s=>s.slug!==story.slug&&s.counties.some(c=>story.counties.includes(c))).slice(0,3);
 const procurementCount=story.sources.filter(s=>s.kind==='procurement').length;
 return <><div className="reading-progress" aria-hidden="true"><i ref={progress}/></div><div className="article-topline"><a className="back-link" href={countyHref(story.counties[0]!)}><Icon name="back"/> Povești din {countyLabel(story.counties[0]!)}</a><button className="text-link" aria-label="Copiază linkul poveștii" onClick={async()=>{try{await navigator.clipboard.writeText(location.href.split('#')[0]!);setCopied('Linkul poveștii a fost copiat.');}catch{setCopied('Copierea nu a reușit. Poți copia adresa din browser.');}}}><Icon name="link"/> Copiază linkul</button></div><span className="copy-status" role="status">{copied}</span>
 <article><header className="article-hero"><div><div className="article-meta">{story.counties.map(c=><a key={c} href={countyHref(c)}>{countyLabel(c)}</a>)}<span>{story.topic}</span><span>{story.minutes} min de citit</span></div><h1>{story.title}</h1><p className="article-dek">{story.summary}</p><div className="byline"><strong>{story.author}</strong><span>{story.status==='preview'?'Documentat la ':''}{dateLabel(story.publishedAt)}{story.updatedAt?` · Actualizat ${dateLabel(story.updatedAt)}`:''}</span></div></div><StoryArt kind={story.illustration} transition={`story-cover-${story.slug}`}/></header>
 <div className="article-layout"><nav className="chapter-nav" aria-label="Capitolele poveștii"><span>În această poveste</span>{[['firul','Firul poveștii'],['cronologie','Cronologia'],['intrebari','Ce rămâne de aflat'],['surse','Toate sursele']].map(([id,title])=><a key={id} href={`#${id}`} className={chapter===id?'selected':undefined} aria-current={chapter===id?'location':undefined}>{title}{id==='surse'&&<span>{story.sources.length}</span>}</a>)}</nav>
 <div className="reading-body" ref={body}><section id="firul"><h2>Ce arată achizițiile</h2>{story.intro.map((p,i)=><p key={i}>{p}</p>)}{refs(story.finding.sourceIds.slice(0,1))}
 {records.length>0&&<div className="finding"><span>{story.finding.title}</span><h3>{records.length} {records.length===1?'înregistrare':'înregistrări'}. {money(storyTotal(story))} în total.</h3><p>{story.finding.explanation}</p><div className="value-bars">{records.map(s=>s.kind==='procurement'&&<button key={s.id} onClick={()=>openSource(s.id)} aria-label={`${s.title}: ${money(s.amount)}. Deschide sursa`}><span>{s.title}</span><i style={{width:`${Number(s.amount)/max*100}%`}}/><b>{money(s.amount)}</b></button>)}</div><button className="text-link" onClick={()=>openSource('all')}>{records.length===1?'Verifică înregistrarea':`Verifică cele ${records.length} înregistrări`} <Icon name="arrow"/></button></div>}<p>{story.finding.after}</p>{story.sections?.map(section=><div className="narrative-section" key={section.id}><h2>{section.title}</h2>{section.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{refs(section.sourceIds)}</div>)}</section>
 <section id="cronologie"><div className="section-head"><h2>Cronologie</h2><span>{story.period}</span></div><ol className="timeline">{story.timeline.map(event=><li className={!event.date?'context-event':undefined} key={event.id}>{event.date?<time dateTime={event.date}>{dateLabel(event.date)}</time>:<span className="quiet">Contextul din afara achizițiilor</span>}<h3>{event.title}</h3><p>{event.text}</p><div className="event-source">{event.sourceIds.length===1&&(()=>{const s=story.sources.find(s=>s.id===event.sourceIds[0]);return s?.kind==='procurement'?<b>{money(s.amount)}</b>:null;})()}{refs(event.sourceIds)}</div></li>)}</ol></section>
 <section id="intrebari"><h2>Ce rămâne de aflat</h2>{story.questions.map((q,i)=><p key={i}>{q}</p>)}{story.reply?<div className="open-question"><h3>{story.reply.title}</h3><p>{story.reply.text}</p>{refs(story.reply.sourceIds)}</div>:<details className="right-reply"><summary>Despre răspunsul instituției</summary><p>Dosarul nu include un răspuns al instituției. Absența lui nu demonstrează că instituția a refuzat să răspundă.</p></details>}</section>
 <section id="surse"><div className="section-head"><h2>Documentele folosite</h2><span>{story.sources.length} surse</span></div><p>Acesta este dosarul poveștii. Fiecare document se deschide fără să pierzi locul în articol.</p><div className="source-list">{story.sources.map((s,i)=><button key={s.id} onClick={()=>openSource(s.id)}><span className="source-number">{i+1}</span><span><strong>{s.title}</strong><small>{s.kind==='procurement'?'Înregistrare de achiziție':s.kind==='external'?'Sursă externă':'Observații și limite'}</small></span><Icon name="arrow"/></button>)}</div><details className="methodology"><summary>Cum am documentat povestea</summary><p>{story.methodology}</p></details>{story.corrections.length>0&&<details className="methodology"><summary>Istoricul corecturilor</summary>{story.corrections.map((c,i)=><p key={i}><time dateTime={c.date}>{dateLabel(c.date)}</time> — {c.text}</p>)}</details>}</section>
 <div className="story-ending"><h2>Continuă verificarea</h2><a className="button" href="/intreaba" target="_blank" rel="noopener noreferrer">Explorează datele <Icon name="external"/></a></div></div>
 <aside className="evidence-rail"><div><span>Dosarul, la îndemână</span><h3>{procurementCount} achiziții<br/>{story.sources.length-procurementCount} surse de context</h3><button className="text-link" onClick={()=>openSource('all')}>Deschide dosarul <Icon name="arrow"/></button><hr/><p><b>Perioada urmărită</b>{story.period}</p><p><b>Ce arată cifrele</b>Valori înregistrate. Nu putem deduce plățile sau execuția lucrărilor.</p></div></aside></div></article>
 {related.length>0&&<section className="related"><div className="section-head"><h2>Alte povești</h2><a className="text-link" href={countyHref(story.counties[0]!)}>Toate poveștile din {countyLabel(story.counties[0]!)} <Icon name="arrow"/></a></div><div className="story-grid">{related.map(s=><StoryCard key={s.slug} story={s}/>)}</div></section>}</>;
}
