'use client';
import { useRef, useState } from 'react';
import { counties,countyLabel,countyHref,countStories,storyCount,storyBucket,matchingCounties } from '@/lib/stories/shared';
import type {Story} from '@/lib/stories/types';
import {Icon} from './StoryParts';
const fixed:Record<string,[number,number]>={cluj:[340,242],buzau:[682,445],iasi:[764,173],timis:[128,383],bucuresti:[621,568]};
export function bounds(d:string){const v=(d.match(/-?\d+(?:\.\d+)?/g)??[]).map(Number);const x=v.filter((_,i)=>i%2===0),y=v.filter((_,i)=>i%2===1);return {x:Math.min(...x),y:Math.min(...y),w:Math.max(...x)-Math.min(...x),h:Math.max(...y)-Math.min(...y)};}
export function CountySilhouette({county}:{county:string}){const c=counties.find(c=>c.key===county)!;const b=bounds(c.d);return <div className="county-silhouette" style={{viewTransitionName:`county-${county.replaceAll(' ','-')}`}}><svg viewBox={`${b.x-8} ${b.y-8} ${b.w+16} ${b.h+16}`} aria-hidden="true"><path d={c.d}/></svg></div>;}
/** Capture an HTML wrapper: SVG paths themselves are not eligible shared elements in Chromium. */
export function prepareCountyFlight(root:HTMLElement,county:string){
 const a=[...root.querySelectorAll<SVGAElement>('[data-county]')].find(el=>el.dataset.county===county),path=a?.querySelector('path'),stage=root.querySelector<HTMLElement>('.map-stage');if(!path||!stage)return()=>{};
 const b=path.getBBox(),r=path.getBoundingClientRect(),p=stage.getBoundingClientRect(),flight=document.createElement('div');flight.className='county-flight';flight.setAttribute('aria-hidden','true');
 Object.assign(flight.style,{left:`${r.left-p.left}px`,top:`${r.top-p.top}px`,width:`${r.width}px`,height:`${r.height}px`,viewTransitionName:`county-${county.replaceAll(' ','-')}`});
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`${b.x} ${b.y} ${b.width} ${b.height}`);svg.style.fill=getComputedStyle(path).fill;svg.append(path.cloneNode(true));flight.append(svg);stage.append(flight);path.style.visibility='hidden';
 return()=>{flight.remove();path.style.visibility='';};
}
export default function StoryMap({stories}:{stories:Story[]}){
 const [hovered,setHovered]=useState(''),[query,setQuery]=useState(''),[open,setOpen]=useState(false);
 const wrap=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),results=matchingCounties(query);
 const located=new Set(stories.flatMap(s=>s.counties)),countiesOnly=[...located].filter(k=>k!=='bucuresti').length;
 return <section className="map-panel" aria-label="Harta poveștilor"><div className="map-toolbar"><span>{storyCount(stories.length)} <span className="muted">{located.size?`în ${countiesOnly} județe${located.has('bucuresti')?' și București':''}`:'· alege un județ'}</span></span><span className="compass" aria-hidden="true">N ↑</span></div>
 <div className="map-stage"><svg className="romania" viewBox="-15 -15 1030 745" role="group" aria-label="Alege un județ. Poți folosi și căutarea de mai jos.">{counties.map(c=><a key={c.key} href={countyHref(c.key)} data-county={c.key} aria-label={`${c.label}: ${storyCount(countStories(stories,c.key))}`} onPointerEnter={()=>setHovered(c.key)} onPointerLeave={()=>setHovered('')} onFocus={()=>setHovered(c.key)} onBlur={()=>setHovered('')}><path className={`county level-${storyBucket(countStories(stories,c.key))}`} d={c.d}/></a>)}{counties.filter(c=>countStories(stories,c.key)>0).map(c=>{const b=bounds(c.d),p=fixed[c.key]??[b.x+b.w/2,b.y+b.h/2];return <g className="map-label" key={c.key} transform={`translate(${p[0]},${p[1]})`} aria-hidden="true"><circle r="15"/><text textAnchor="middle" y="5">{countStories(stories,c.key)}</text><text className="county-name" textAnchor="middle" y="36">{c.label}</text></g>;})}</svg>
 <div className="map-tip" role="status" hidden={!hovered}><b>{countyLabel(hovered)}</b><span>{countStories(stories,hovered)?`${storyCount(countStories(stories,hovered))} · Deschide județul`:'Încă nicio poveste'}</span></div></div>
 <div className="legend"><span>Povești publicate</span><div>{['Niciuna','1','2–3','4–7','8+'].map((n,i)=><span key={n}><i className={`level-${i}`}/>{n}</span>)}</div></div><p className="map-note">Intensitatea arată numărul poveștilor, nu nivelul de risc.</p>
 <div className="county-search" ref={wrap} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><label htmlFor="story-county-search">Unde vrei să te uiți?</label><div className="search-field"><Icon name="search"/><input ref={input} id="story-county-search" type="search" autoComplete="off" placeholder="Caută un județ…" value={query} aria-expanded={open} aria-controls="story-county-results" onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();wrap.current?.querySelector<HTMLAnchorElement>('#story-county-results a')?.focus();}if(e.key==='Enter')wrap.current?.querySelector<HTMLAnchorElement>('#story-county-results a')?.click();}}/></div>
 <div id="story-county-results" hidden={!open} onKeyDown={e=>{const links=[...e.currentTarget.querySelectorAll('a')],i=links.indexOf(document.activeElement as HTMLAnchorElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();links[(i+(e.key==='ArrowDown'?1:links.length-1))%links.length]?.focus();}if(e.key==='Escape'){input.current?.focus();setOpen(false);}}}>{results.length?results.map(c=><a key={c.key} href={countyHref(c.key)}>{c.label}<span>{countStories(stories,c.key)?storyCount(countStories(stories,c.key)):'Încă nicio poveste'}<Icon name="arrow"/></span></a>):<p>Nu am găsit județul. Încearcă un alt nume.</p>}</div></div></section>;
}
