import {map} from './map.js';
import {art} from './art.js';
import {stories,countyNames} from './data.js';
const main=document.querySelector('main'),dialog=document.querySelector('#evidence');
const I=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',back:'<path d="M19 12H5m6-6-6 6 6 6"/>',external:'<path d="M14 4h6v6m0-6-10 10M10 4H5v15h15v-5"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',file:'<path d="M14 3H5v18h14V8Zm0 0v5h5M8 12h8m-8 4h6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',moon:'<path d="M20 14A8 8 0 0 1 10 4a8.5 8.5 0 1 0 10 10Z"/>',chevron:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',link:'<path d="m10 14 4-4M8 16l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m0 12a4 4 0 0 0 6 0l5-5a4 4 0 0 0-6-6l-1 1" transform="translate(1 0) scale(.92)"/>'})[name]||''}</svg>`;
const label=k=>countyNames[k]||map.shapes.find(s=>s.key===k)?.label||k;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fold=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const ron=n=>new Intl.NumberFormat('ro-RO',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' lei';
const date=v=>new Date(v+'T12:00:00').toLocaleDateString('ro-RO',{day:'numeric',month:'long',year:'numeric'});
const count=k=>stories.filter(s=>s.county===k).length;
const total=s=>s.values.reduce((a,b)=>a+b,0);
let route='',currentStory=null,county='cluj',topic='Toate',savedY=0,transitionBusy=false;
const positions={cluj:[340,242],buzau:[682,445],iasi:[764,173],timis:[128,383],bucuresti:[621,568]};
const artHTML=(s,shared=false)=>`<div class="cover art-${s.art}" ${shared?`style="view-transition-name:story-cover-${s.id}"`:''}><svg viewBox="0 0 310 105" aria-hidden="true">${art[s.art]}</svg><span class="cover-caption">Ilustrație editorială</span></div>`;
const meta=s=>`<span>${esc(s.topic)}</span><span>${s.minutes} min de citit</span>`;
const link=(s,cl='')=>`<a class="story-link ${cl}" href="#/poveste/${s.id}">${esc(s.title)}${I('arrow')}</a>`;
function mapHTML(){return `<svg class="romania" viewBox="-15 -15 1030 745" role="group" aria-label="Povești demonstrative pe județe. Poți folosi și căutarea de județ.">${map.shapes.map(s=>`<a href="#/judet/${encodeURIComponent(s.key)}" data-county="${esc(s.key)}" aria-label="${esc(label(s.key))}: ${count(s.key)} ${count(s.key)===1?'poveste demonstrativă':'povești demonstrative'}"><path class="county level-${count(s.key)}" d="${s.d}"/></a>`).join('')}${Object.entries(positions).map(([k,p])=>`<g class="map-label" transform="translate(${p.join(',')})"><circle r="15"/><text text-anchor="middle" y="5">${count(k)}</text><text class="county-name" text-anchor="middle" y="36">${label(k)}</text></g>`).join('')}</svg>`;}
function shapeHTML(k){const shape=map.shapes.find(s=>s.key===k);return `<div class="county-silhouette" style="view-transition-name:county-${k.replaceAll(' ','-')}"><svg data-fit="${k}" viewBox="0 0 1000 715" aria-hidden="true"><path d="${shape.d}"/></svg></div>`;}
function countyFlight(k){
 const shape=map.shapes.find(s=>s.key===k),a=[...document.querySelectorAll('[data-county]')].find(a=>a.dataset.county===k);
 if(!shape||!a)return()=>{};
 const path=a.querySelector('path'),stage=document.querySelector('.map-stage'),b=path.getBBox(),rect=path.getBoundingClientRect(),parent=stage.getBoundingClientRect();
 const flight=document.createElement('div');flight.className='county-flight';flight.setAttribute('aria-hidden','true');
 Object.assign(flight.style,{left:(rect.left-parent.left)+'px',top:(rect.top-parent.top)+'px',width:rect.width+'px',height:rect.height+'px',viewTransitionName:'county-'+k.replaceAll(' ','-')});
 flight.innerHTML=`<svg viewBox="${b.x} ${b.y} ${b.width} ${b.height}" style="fill:${getComputedStyle(path).fill}"><path d="${shape.d}"/></svg>`;
 stage.append(flight);path.style.visibility='hidden';
 return()=>{flight.remove();path.style.visibility='';};
}
function atlas(){
 currentStory=null;
 main.innerHTML=`<section class="atlas-heading"><div><h1>Ce bate la ochi<span class="punct">.</span></h1><p>Povești despre banii publici. Cu toate firele la vedere.</p></div><a href="#povesti" class="text-link">Vezi toate poveștile ${I('arrow')}</a></section>
 <div class="atlas-layout"><section class="map-panel" aria-label="Harta poveștilor"><div class="map-toolbar"><span>${stories.length} povești <span class="muted">în ${new Set(stories.filter(s=>s.county!=='bucuresti').map(s=>s.county)).size} județe și București</span></span><span class="compass" aria-hidden="true">N ↑</span></div><div class="map-stage">${mapHTML()}<div class="map-tip" role="status" hidden></div></div><div class="legend"><span>Povești publicate</span><div>${[0,1,2,3].map(n=>`<span><i class="level-${n}"></i>${n===0?'Niciuna':n}</span>`).join('')}</div></div><p class="map-note">Intensitatea arată numărul poveștilor, nu nivelul de risc.</p><div class="county-search"><label for="county-search">Unde vrei să te uiți?</label><div class="search-field">${I('search')}<input type="search" id="county-search" autocomplete="off" placeholder="Caută un județ…" aria-controls="county-results" aria-expanded="false"></div><div id="county-results" hidden></div></div></section>
 <aside class="latest"><h2>Un fir de la care să începi</h2><a class="cover-link" href="#/poveste/acelasi-drum" aria-label="${esc(stories[0].title)}">${artHTML(stories[0],true)}</a><div class="meta"><span>Cluj · Drumuri</span><span>5 min</span></div>${link(stories[0],'lead-title')}<p>${stories[0].dek}</p><a class="text-link" href="#/poveste/acelasi-drum">Urmărește povestea ${I('arrow')}</a><div class="next-story"><span class="meta">Buzău · Infrastructură</span>${link(stories[3])}</div><div class="next-story"><span class="meta">Iași · Sănătate</span>${link(stories[5])}</div></aside></div>
 <section id="povesti" class="all-stories"><div class="section-head"><h2>Mai multe fire de urmărit</h2><span>${stories.length} povești demonstrative</span></div><div class="story-grid">${[...stories].sort((a,b)=>b.date.localeCompare(a.date)).map(s=>card(s,false)).join('')}</div></section>`;
 bindMap();
 const input=document.querySelector('#county-search'),results=document.querySelector('#county-results');
 function search(){const q=fold(input.value);const found=[...map.shapes].filter(s=>fold(label(s.key)).includes(q)).sort((a,b)=>label(a.key).localeCompare(label(b.key),'ro'));results.hidden=false;input.setAttribute('aria-expanded','true');results.innerHTML=found.length?found.map(s=>`<a href="#/judet/${encodeURIComponent(s.key)}">${label(s.key)}<span>${count(s.key)?count(s.key)+(count(s.key)===1?' poveste':' povești'):'Încă nicio poveste'} ${I('chevron')}</span></a>`).join(''):'<p>Nu am găsit județul. Încearcă un alt nume.</p>';}
 input.addEventListener('input',search);input.addEventListener('focus',search);input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('a')?.focus();}if(e.key==='Escape'){results.hidden=true;input.setAttribute('aria-expanded','false');}if(e.key==='Enter')results.querySelector('a')?.click();});
 results.addEventListener('keydown',e=>{const links=[...results.querySelectorAll('a')],i=links.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();links[(i+(e.key==='ArrowDown'?1:links.length-1))%links.length]?.focus();}if(e.key==='Escape'){input.focus();results.hidden=true;input.setAttribute('aria-expanded','false');}});
}
function bindMap(){const tip=document.querySelector('.map-tip');document.querySelectorAll('[data-county]').forEach(a=>{const show=()=>{const k=a.dataset.county;tip.hidden=false;tip.innerHTML=`<b>${label(k)}</b><span>${count(k)?count(k)+(count(k)===1?' poveste':' povești')+' · Deschide județul':'Încă nicio poveste'}</span>`;};a.addEventListener('pointerenter',show);a.addEventListener('focus',show);a.addEventListener('pointerleave',()=>tip.hidden=true);a.addEventListener('blur',()=>tip.hidden=true);});}
function card(s,shared=true){return `<article class="story-card"><a class="cover-link" href="#/poveste/${s.id}" aria-label="${esc(s.title)}">${artHTML(s,shared)}</a><div class="meta"><span>${label(s.county)} · ${s.topic}</span><span>${s.minutes} min</span></div>${link(s)}<p>${s.dek}</p><span class="quiet">${date(s.date)}</span></article>`;}
function countyPage(k){
 county=k;currentStory=null;const ss=stories.filter(s=>s.county===k);const filtered=topic==='Toate'?ss:ss.filter(s=>s.topic===topic),first=filtered[0];
 main.innerHTML=`<a href="#/" class="back-link">${I('back')} Înapoi la hartă</a><section class="county-masthead"><div><h1>${label(k)}<span class="punct">.</span></h1><p>${ss.length?`${ss.length} ${ss.length===1?'poveste':'povești'}. Pornește de la una și urmărește documentele.`:'Încă nicio poveste publicată în această machetă.'}</p></div>${shapeHTML(k)}</section>
 ${ss.length?`<div class="filter-row" aria-label="Filtrează poveștile">${['Toate',...new Set(ss.map(s=>s.topic))].map(t=>`<button data-topic="${t}" aria-pressed="${topic===t}">${t}${t==='Toate'?` <span>${ss.length}</span>`:''}</button>`).join('')}<span class="quiet">Cele mai noi întâi</span></div>
 <section class="county-stories" aria-label="Poveștile județului"><article class="featured"><a class="cover-link" href="#/poveste/${first.id}" aria-label="${esc(first.title)}">${artHTML(first,true)}</a><div class="meta">${meta(first)}</div>${link(first,'featured-title')}<p>${first.dek}</p><div class="featured-bottom"><span>Exemplu editorial · ${date(first.date)}</span><a class="text-link" href="#/poveste/${first.id}">Citește povestea ${I('arrow')}</a></div></article>
 <div class="county-secondary">${filtered.slice(1).map(s=>`<article class="side-story"><a href="#/poveste/${s.id}" class="cover-link" aria-label="${esc(s.title)}">${artHTML(s,true)}</a><div class="meta">${meta(s)}</div>${link(s)}<p>${s.dek}</p></article>`).join('')}${filtered.length===1?`<div class="reading-note"><h2>Fiecare afirmație are un punct de plecare.</h2><p>În poveste găsești cronologia, înregistrările folosite și întrebările care rămân deschise.</p><a class="text-link" href="#/">Vezi și alte județe ${I('arrow')}</a></div>`:''}</div></section>`:`<section class="empty-state"><h2>Aici povestea încă nu a început.</h2><p>Lipsa unei povești nu spune că nu există probleme. Înseamnă doar că nu am publicat una aici.</p><a class="button" href="#/">Alege alt județ ${I('arrow')}</a><a class="text-link" href="http://localhost:3000/intreaba" target="_blank" rel="noopener">Explorează tu datele ${I('external')}</a></section>`}
 <div class="county-close"><span>Povești scrise de oameni. Date pe care le poți verifica.</span><a href="#/" class="text-link">Alt județ ${I('arrow')}</a></div>`;
 fitShape();document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{topic=b.dataset.topic;countyPage(k);document.querySelector(`[data-topic="${topic}"]`).focus();}));
}
function fitShape(){document.querySelectorAll('[data-fit]').forEach(svg=>{const b=svg.querySelector('path').getBBox();svg.setAttribute('viewBox',`${b.x-8} ${b.y-8} ${b.width+16} ${b.height+16}`);});}
function sourceButton(s,index,text){return `<button class="source-ref" data-evidence="${s.id}:${index}">${I('file')}${text||'Sursa '+(index+1)}</button>`;}
function article(s){
 currentStory=s;
 const related=stories.filter(v=>v.county===s.county&&v.id!==s.id);
 main.innerHTML=`<div class="reading-progress" aria-hidden="true"><i></i></div><div class="article-topline"><a href="#/judet/${s.county}" class="back-link">${I('back')} Povești din ${label(s.county)}</a><button class="text-link" id="copy-story">${I('link')} Copiază linkul</button></div>
 <article><header class="article-hero"><div><div class="article-meta"><a href="#/judet/${s.county}">${label(s.county)}</a><span>${s.topic}</span><span>${s.minutes} min de citit</span></div><h1>${s.title}</h1><p class="article-dek">${s.dek}</p><div class="byline"><strong>Exemplu editorial</strong><span>${date(s.date)} · Conținut demonstrativ</span></div></div>${artHTML(s,true)}</header>
 <div class="article-layout"><aside class="chapter-nav"><span>În această poveste</span><a href="#firul" class="selected">Firul poveștii</a><a href="#cronologie">Cronologia</a><a href="#intrebari">Ce rămâne de aflat</a><a href="#surse">Toate sursele <span>5</span></a><p>Instituțiile, firmele și documentele din exemplu sunt fictive.</p></aside>
 <div class="reading-body"><section id="firul"><h2>Totul începe cu un detaliu.</h2><p>Într-o listă de achiziții, o înregistrare despre ${esc(s.subject)} poate părea doar încă un rând. Privite împreună, cele trei înregistrări din exemplul nostru ridică însă o întrebare: <strong>${esc(s.question.charAt(0).toLowerCase()+s.question.slice(1))}</strong></p><p>Am pornit de la prima achiziție și am urmărit ce a venit după. ${esc(s.authorities?s.authorities.join(', '):s.authority)} și ${esc(s.supplier)} sunt nume fictive, folosite aici pentru a arăta cum s-ar putea documenta povestea.</p>${sourceButton(s,0,'Deschide prima înregistrare')}
 <div class="finding"><span>Ce putem vedea în documente</span><h3>Trei înregistrări. ${ron(total(s))} în total.</h3><p>Valorile înregistrate ale contractelor, nu plățile efectuate.</p><div class="value-bars">${s.values.map((v,i)=>`<button data-evidence="${s.id}:${i}" aria-label="${s.labels[i]}: ${ron(v)}. Deschide sursa"><span>${s.labels[i]}</span><i style="--size:${v/Math.max(...s.values)*100}%"></i><b>${ron(v)}</b></button>`).join('')}</div><button class="text-link" data-evidence="${s.id}:all">Verifică cele 3 înregistrări ${I('arrow')}</button></div>
 <p>Legătura dintre rânduri ne ajută să formulăm întrebarea. Explicația ei cere mai mult: obiectul fiecărui contract, anexele, răspunsurile instituției și, unde este cazul, verificarea pe teren.</p></section>
 <section id="cronologie"><div class="section-head"><h2>Cum se leagă lucrurile</h2><span>${s.period}</span></div><p class="section-intro">Urmărește ordinea. Deschide documentul din fiecare pas.</p><ol class="timeline">${s.days.map((d,i)=>`<li><time datetime="${d}">${date(d)}</time><h3>${s.labels[i]}</h3><p>${i===0?'Prima înregistrare din selecție. De aici începe verificarea.':i===1?'O nouă achiziție intră în selecție. Comparăm obiectul și condițiile cu prima.':'Ultima înregistrare din acest exemplu. Reunim documentele înainte de a formula concluzii.'}</p><div class="event-source"><b>${ron(s.values[i])}</b>${sourceButton(s,i)}</div></li>`).join('')}<li class="context-event"><time>Contextul din afara achizițiilor</time><h3>Ce spune documentarea de pe teren</h3><p>Un articol sau o observație poate aduce context. Îl păstrăm separat de ceea ce demonstrează contractele.</p>${sourceButton(s,3,'Articol de context · exemplu')}</li></ol></section>
 <section id="intrebari"><h2>Ce rămâne de aflat</h2><p>${s.unknown}</p><div class="open-question"><h3>Întrebarea trimisă instituției</h3><p>„${s.question} Ne puteți pune la dispoziție documentele justificative?”</p><span>Exemplu de solicitare · nu a fost trimisă</span></div><details class="right-reply"><summary>Cum ar apărea răspunsul instituției</summary><p>Răspunsul integral ar fi publicat aici, datat și legat de documentul original. În această machetă nu există o solicitare reală și nici un răspuns primit.</p></details></section>
 <section id="surse"><div class="section-head"><h2>Nu ne crede pe cuvânt.</h2><span>5 surse demo</span></div><p>Acesta este dosarul poveștii. Fiecare document se deschide fără să pierzi locul în articol.</p><div class="source-list">${[...s.labels,'Articol de context','Notă de documentare'].map((t,i)=>`<button data-evidence="${s.id}:${i}"><span class="source-number">${i+1}</span><span><strong>${t}</strong><small>${i<3?'Înregistrare de achiziție · exemplu':i===3?'Sursă de presă · exemplu':'Observații și limite · exemplu'}</small></span>${I('arrow')}</button>`).join('')}</div><p class="editorial-note">În versiunea publicată: autor, data ultimei actualizări, metodologia selecției și istoricul corecturilor.</p></section>
 <div class="story-ending"><h2>Povestea e un început.</h2><p>Tu ce ai verifica mai departe?</p><a href="http://localhost:3000/intreaba" target="_blank" rel="noopener" class="button">Explorează datele ${I('external')}</a><span class="quiet">Deschide aplicația locală într-un tab nou.</span></div></div>
 <aside class="evidence-rail"><div><span>Dosarul, la îndemână</span><h3>3 achiziții<br>2 surse de context</h3><button class="text-link" data-evidence="${s.id}:all">Deschide dosarul ${I('arrow')}</button><hr><p><b>Perioada urmărită</b>${s.period}</p><p><b>Ce arată cifrele</b>Valori înregistrate. Nu putem deduce plățile sau execuția lucrărilor.</p></div></aside></div></article>
 ${related.length?`<section class="related"><div class="section-head"><h2>Mai există un fir.</h2><a class="text-link" href="#/judet/${s.county}">Toate poveștile din ${label(s.county)} ${I('arrow')}</a></div><div class="story-grid">${related.map(card).join('')}</div></section>`:''}`;
 document.querySelector('#copy-story').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Linkul machetei a fost copiat.');}catch{toast('Copierea nu a reușit. Poți copia adresa din browser.');}});
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.chapter-nav a').forEach(a=>a.classList.toggle('selected',a.hash==='#'+e.target.id));}});},{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('.reading-body>section').forEach(s=>observer.observe(s));cleanup=()=>observer.disconnect();updateProgress();
}
let cleanup=()=>{};
function evidence(s,index){
 const all=index==='all',i=Number(index),isContract=i<3;
 const head=`<header class="drawer-head"><div><span>Dosarul poveștii · exemplu</span><h2 id="evidence-title">${all?'Sursele, la vedere':isContract?'Înregistrarea sursă':i===3?'Articol de context':'Notă de documentare'}</h2></div><button class="icon-button" data-close aria-label="Închide sursele">${I('close')}</button></header>`;
 const record=n=>`<article class="record"><span class="record-tag">Achiziție demonstrativă · DEMO-${n+1}</span><h3>${s.labels[n]}</h3><p class="record-amount">${ron(s.values[n])}</p><dl><div><dt>Data</dt><dd>${date(s.days[n])}</dd></div><div><dt>Instituție</dt><dd>${s.authorities?.[n]||s.authority} <small>(fictivă)</small></dd></div><div><dt>Furnizor</dt><dd>${s.supplier} <small>(fictivă)</small></dd></div></dl><a class="text-link" href="document.html?story=${s.id}&source=${n}" target="_blank" rel="noopener">Deschide fișa demonstrativă ${I('external')}</a></article>`;
 document.querySelector('#evidence-content').innerHTML=head+`<div class="drawer-body"><p class="demo-note">Date fictive pentru machetă. În aplicație, fiecare fișă va avea linkul exact către înregistrarea și documentele SEAP.</p>${all?`<div class="drawer-total"><b>${ron(total(s))}</b><span>3 înregistrări în selecția poveștii</span></div>${s.values.map((_,n)=>record(n)).join('')}<h3>Context și documentare</h3><button class="source-context" data-evidence="${s.id}:3">Articol de context · exemplu ${I('arrow')}</button><button class="source-context" data-evidence="${s.id}:4">Notă de documentare · exemplu ${I('arrow')}</button>`:isContract?record(i):`<article class="record"><span class="record-tag">${i===3?'Context de presă':'Notițe editoriale'} · exemplu</span><h3>${i===3?'Dincolo de titlul contractului':'Cum am construit selecția'}</h3><p>${i===3?'Un material de presă ar putea aduce observații de pe teren și declarații. Acestea trebuie atribuite și verificate separat de datele din achiziții.':'Cele trei înregistrări au fost create exclusiv pentru această machetă. Într-o poveste reală, aici documentăm criteriile selecției, perioada, sursele și limitele.'}</p><a class="text-link" href="document.html?story=${s.id}&source=${i}" target="_blank" rel="noopener">${i===3?'Deschide articolul demonstrativ':'Deschide nota demonstrativă'} ${I('external')}</a><p class="quiet">În versiunea finală, o sursă externă deschide publicația originală într-un tab nou.</p></article>`}<button class="button return-reading" data-close>${I('back')} Continuă lectura</button></div>`;
 if(!dialog.open){savedY=scrollY;dialog.showModal();document.body.classList.add('dialog-open');}dialog.scrollTop=0;dialog.querySelector('[data-close]').focus({preventScroll:true});
}
function closeEvidence(){dialog.close();document.body.classList.remove('dialog-open');}
dialog.addEventListener('close',()=>document.body.classList.remove('dialog-open'));
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeEvidence();}});
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)closeEvidence();const b=e.target.closest('[data-evidence]');if(b){const[id,idx]=b.dataset.evidence.split(':');evidence(stories.find(s=>s.id===id),idx);}const chapter=e.target.closest('a[href^="#"]:not([href^="#/"])');if(chapter){const target=document.querySelector(chapter.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}const a=e.target.closest('a[href^="#/"]');if(a){e.preventDefault();navigate(a.getAttribute('href').slice(1));}if(!e.target.closest('.county-search')){const r=document.querySelector('#county-results');if(r){r.hidden=true;document.querySelector('#county-search').setAttribute('aria-expanded','false');}}});
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),3500);}
function updateProgress(){const b=document.querySelector('.reading-progress i');if(b){const el=document.querySelector('.reading-body');const distance=el.getBoundingClientRect().bottom+scrollY-innerHeight;b.style.width=Math.min(100,Math.max(0,scrollY/Math.max(1,distance)*100))+'%';}}
addEventListener('scroll',updateProgress,{passive:true});
function render(path){cleanup();cleanup=()=>{};route=path;topic='Toate';const parts=path.split('/');if(parts[1]==='judet'&&map.shapes.some(s=>s.key===decodeURIComponent(parts[2])))countyPage(decodeURIComponent(parts[2]));else if(parts[1]==='poveste'&&stories.some(s=>s.id===parts[2]))article(stories.find(s=>s.id===parts[2]));else atlas();document.title=`${currentStory?currentStory.title:parts[1]==='judet'?label(decodeURIComponent(parts[2])):'Ce bate la ochi'} · cinecâștigă?`;}
async function navigate(path,historyMode=true){
 if(transitionBusy)return;
 if(path===route){scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return;}
 transitionBusy=true;const previous=route;let removeFlight=()=>{};
 const update=()=>{if(dialog.open)closeEvidence();if(historyMode)history.pushState({path},'',`#${path}`);render(path);scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});if(path==='/'&&previous.startsWith('/judet/'))removeFlight=countyFlight(decodeURIComponent(previous.split('/')[2]));};
 if(document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
  if(previous==='/'&&path.startsWith('/judet/'))countyFlight(decodeURIComponent(path.split('/')[2]));
  try{await document.startViewTransition(update).finished;}catch{}
 }else update();
 removeFlight();transitionBusy=false;
}
addEventListener('popstate',()=>{const hash=location.hash.slice(1);if(hash.startsWith('/'))navigate(hash,false);});
try{document.documentElement.dataset.theme=localStorage.getItem('stories-mock-theme')||'light';}catch{}
document.querySelector('#theme').innerHTML=I('moon');document.querySelector('#theme').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('stories-mock-theme',next);}catch{}});
render(location.hash.startsWith('#/')?location.hash.slice(1):'/');
