/* Every visual mark has an equivalent, named link to its exact source rows. */
(function () {
  'use strict';
  const C = window.CQ, e = C.escape, money = C.formatMoney, compact = C.formatCompact, count = C.formatCount;
  const number = n => new Intl.NumberFormat('ro-RO',{maximumFractionDigits:2}).format(n);
  const colors=['#285b45','#708e59','#aab984','#c7cca7','#d9dbc5','#b67957','#547c76','#9cae98'];
  const arrow='<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M4 10h11m-4-4 4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
  const link=(g,text,cls='')=>`<button type="button" class="c-source-link ${cls}" data-action="q-evidence" data-key="${e(g.key)}" aria-label="${e(text+' · '+g.label)}">${e(text)}${arrow}</button>`;
  const allLink=text=>`<button type="button" class="c-source-link" data-action="q-evidence">${e(text)}${arrow}</button>`;
  const value=(g,q)=>q.measure==='count'?count(g.count):money(g.amount);
  const finiteRatio=(v,m)=>m>0?Math.max(0,Math.min(100,v/m*100)):0;
  const signed=n=>(n>0?'+':'')+money(n);
  const note=text=>`<p class="c-answer-note">${e(text)}</p>`;
  const shown=(gs,q)=>gs.slice(0,q.topN);
  const topNote=(gs,q)=>`<p class="c-chart-caption">${gs.length>q.topN?`Primii ${q.topN} din ${gs.length}. `:`${gs.length} ${gs.length===1?'grup':'grupuri'}. `}Butonul de înregistrări include întreaga selecție.</p>`;
  const empty=r=>`<div class="c-empty-answer"><span class="c-empty-symbol" aria-hidden="true">∅</span><h3>Nu am găsit în datele selectate.</h3><p>Încearcă o perioadă mai largă sau mai puține condiții. Lipsa unui rezultat în acest extras nu înseamnă lipsa unei achiziții în SEAP.</p>${allLink('Verifică selecția goală')}</div>`;
  function dataTable(groups,q,{percent=false,total=0}={}) {
    return `<div class="c-data-table"><div class="c-data-head" aria-hidden="true"><span>Entitate / grup</span><span>${q.measure==='count'?'Înregistrări':'Valoare înregistrată'}</span><span>Surse</span></div>${groups.map((g,i)=>`<div class="c-data-row"><span class="c-data-name"><small>${String(i+1).padStart(2,'0')}</small><strong>${e(g.label)}</strong></span><span class="c-data-amount">${value(g,q)}${percent?`<small>${number(total?g.amount/total*100:0)}% din selecție</small>`:''}</span>${link(g,`${count(g.count)} ${g.count===1?'înregistrare':'înregistrări'}`)}</div>`).join('')}</div>`;
  }
  function ranking(r,layout) {
    const gs=shown(r.groups,r.query), max=Math.max(...gs.map(g=>r.query.measure==='count'?g.count:g.amount),1);
    if(layout==='table')return dataTable(gs,r.query)+topNote(r.groups,r.query);
    return `<div class="c-ranking">${gs.map((g,i)=>`<button class="c-rank-row" data-action="q-evidence" data-key="${e(g.key)}" aria-label="${e(g.label+': '+value(g,r.query)+'. Vezi '+g.count+' înregistrări.')}"><span class="c-rank-number">${String(i+1).padStart(2,'0')}</span><span class="c-rank-body"><span class="c-rank-label">${e(g.label)}</span><span class="c-rank-track"><span style="width:${finiteRatio(r.query.measure==='count'?g.count:g.amount,max)}%;background:${colors[Math.min(i,colors.length-1)]}"></span></span></span><span class="c-rank-value"><strong>${value(g,r.query)}</strong><small>${count(g.count)} ${g.count===1?'înregistrare':'înregistrări'} ${arrow}</small></span></button>`).join('')}</div>${topNote(r.groups,r.query)}`;
  }
  function stat(r) {
    return `<div class="c-total-answer"><div class="c-total-primary"><span class="c-eyebrow">${r.query.measure==='count'?'Numărul înregistrărilor':'Valoare înregistrată în selecție'}</span><button data-action="q-evidence" class="c-total-number">${r.query.measure==='count'?count(r.count):compact(r.total)}${arrow}</button><span class="c-total-exact">${r.query.measure==='count'?money(r.total)+' valoare însumată':money(r.total)+' · valoare exactă'}</span></div><div class="c-addition"><span class="c-eyebrow">Cum se adună</span>${r.groups.map((g,i)=>`<div class="c-addition-line"><span class="c-add-sign">${i?'+':''}</span><span><strong>${e(g.label)}</strong><small>${count(g.count)} înregistrări</small></span><span>${money(g.amount)}</span>${link(g,'Surse')}</div>`).join('')}<div class="c-addition-total"><span>= Total</span><strong>${money(r.total)}</strong></div></div></div>${note('Suma valorilor înregistrate în eșantion. Un acord-cadru poate avea o valoare maximă; aceasta nu dovedește o plată efectivă.')}`;
  }
  function timeseries(r) {
    const max=Math.max(...r.groups.map(g=>r.query.measure==='count'?g.count:g.amount),1);
    const available=new Set(r.groups.map(g=>Number(g.id))),missing=[];
    for(let y=r.query.yearFrom;y<=r.query.yearTo;y++)if(!available.has(y))missing.push(y);
    return `<div class="c-time-chart" style="--c-columns:${r.groups.length}">${r.groups.map(g=>`<button class="c-time-column" data-action="q-evidence" data-key="${e(g.key)}" aria-label="${e(g.label+': '+value(g,r.query)+'. Vezi înregistrările.')}"><strong>${r.query.measure==='count'?count(g.count):compact(g.amount)}</strong><span class="c-time-space"><span class="c-time-bar" style="height:${Math.max(3,finiteRatio(r.query.measure==='count'?g.count:g.amount,max))}%"></span></span><span class="c-time-year">${e(g.label)}</span><small>${count(g.count)} ${g.count===1?'înregistrare':'înregistrări'}</small></button>`).join('')}</div>${missing.length?note(`Fără înregistrări în acest extras pentru: ${missing.join(', ')}. Nu sunt afișate drept ani fără activitate.`):''}<details class="c-equivalent"><summary>Vezi valorile exacte, an cu an</summary>${dataTable(r.groups,r.query)}</details>${note('Seria descrie selecția de înregistrări din prototip. Diferențele dintre ani pot reflecta alegerea eșantionului și nu demonstrează o tendință în întreaga bază.')}`;
  }
  function map(r) {
    const M=window.MOCK_MAP,groups=new Map(r.groups.map(g=>[C.fold(g.label),g]));
    return `<div class="c-map-answer"><div class="c-romania"><svg viewBox="0 0 ${M.width} ${M.height}" role="img" aria-label="Harta județelor. Doar Cluj și București au înregistrări în acest extras.">${M.shapes.map(s=>{const g=groups.get(C.fold(s.label));return g?`<a role="button" tabindex="0" data-action="q-evidence" data-key="${e(g.key)}" aria-label="${e(s.label+': '+value(g,r.query)+'. Vezi sursele.')}" class="c-map-active"><path d="${s.d}"/><title>${e(s.label+': '+value(g,r.query))}</title></a>`:`<path class="c-map-absent" d="${s.d}"><title>${e(s.label)}: fără date în acest extras</title></path>`;}).join('')}</svg><div class="c-map-legend"><span><i></i>Cu înregistrări în selecție</span><span><i></i>Fără date în extras</span></div></div><div class="c-map-list"><span class="c-eyebrow">Județul cumpărătorului</span><h3>Geografia unei selecții.</h3><p>Apasă pe un județ pentru fiecare contract din suma lui.</p>${r.groups.map(g=>`<button class="c-county-item" data-action="q-evidence" data-key="${e(g.key)}"><span><strong>${e(g.label)}</strong><small>${count(g.count)} înregistrări</small></span><span>${value(g,r.query)}${arrow}</span></button>`).join('')}<p class="c-chart-caption">Județul este sediul autorității, nu locul în care se execută lucrarea.</p></div></div>`;
  }
  function breakdown(r,layout) {
    return `<div class="c-composition-strip" aria-label="Ponderea categoriilor în totalul selecției">${r.groups.map((g,i)=>`<button data-action="q-evidence" data-key="${e(g.key)}" style="flex:${Math.max(.08,g.amount/r.total*100)};background:${colors[i%colors.length]}" aria-label="${e(g.label+': '+number(g.extra.percentage)+'%. Vezi înregistrările.')}" title="${e(g.label+' · '+number(g.extra.percentage)+'%')}"></button>`).join('')}</div>${layout==='table'?dataTable(r.groups,r.query,{percent:true,total:r.total}):`<div class="c-category-list">${r.groups.map((g,i)=>`<button data-action="q-evidence" data-key="${e(g.key)}" class="c-category-row"><span class="c-category-name"><i style="background:${colors[i%colors.length]}"></i><strong>${e(g.label)}</strong></span><span class="c-category-percent">${number(g.extra.percentage)}<small>%</small></span><span class="c-category-value">${money(g.amount)}<small>${count(g.count)} înregistrări ${arrow}</small></span></button>`).join('')}</div>`}${note(`Fiecare pondere = suma categoriei ÷ ${money(r.total)} × 100. Numitorul cuprinde toate cele ${count(r.count)} înregistrări ale răspunsului.`)}`;
  }
  function profileCard(g,r,{compactCard=false}={}) {
    const p=g.profile,split=r.groups.find(x=>x.key==='split:'+p.id);
    return `<article class="c-profile-card ${compactCard?'c-profile-card-small':''}"><div class="c-profile-top"><span class="c-eyebrow">${e(p.county)}</span><span class="c-profile-stamp">Profil verificabil</span></div><h3>${e(g.label)}</h3><span class="c-profile-label">Valoare înregistrată în profil</span><strong class="c-profile-value">${compact(p.totalRon)}</strong><span class="c-profile-exact">${money(p.totalRon)}</span><div class="c-profile-metrics"><span><strong>${count(p.nDas)}</strong><small>înregistrări DA</small></span><span><strong>${number(p.cri)}<small> / 1</small></strong><small>indice de risc</small></span></div><p class="c-profile-state">Include oferte neacceptate.${Number.isFinite(p.acceptedN)?` ${count(p.acceptedN)} înregistrări au starea acceptată.`:''}</p>${link(g,`${count(g.count)} înregistrări · SEAP`)}${split?link(split,'Exemplul indicatorului de fragmentare','c-split-link'):''}</article>`;
  }
  function methodology(r) {
    return `<details class="c-methodology"><summary><span>De unde vine indicele de 0,20?</span><span>1 semnal / 5 indicatori</span></summary><div><p>${e(r.extra.cohort[0]?.calculation || r.extra.note)}</p><p>În aceste profiluri, indicatorul activ este fragmentarea achizițiilor. Un exemplu de înregistrări pentru fiecare profil este disponibil separat. Exemplul arată un grup semnalat; întregul profil se verifică din lista completă.</p><p>Un semnal statistic cere context. El nu stabilește singur o încălcare a legii.</p>${r.extra.profileGroups.map(g=>{const s=r.groups.find(x=>x.key==='split:'+g.id);return s?link(s,g.label+' · exemplu'):'';}).join('')}</div></details>`;
  }
  function compare(r) {
    return `<div class="c-comparison">${r.extra.profileGroups.map(g=>profileCard(g,r)).join('')}</div><div class="c-profile-scope-note"><strong>Același cadru de comparație.</strong><span>Profiluri de achiziții directe din 2020–2026, inclusiv oferte neacceptate. Fiecare sumă se reface din înregistrările profilului; nu este suma eșantionului de contracte.</span></div>${methodology(r)}`;
  }
  function trend(r) {
    const gs=shown(r.extra.entities,r.query);
    return `<div class="c-change-intro"><span><small>${r.query.yearFrom} · selecție</small><strong>${compact(r.extra.fromAmount)}</strong></span><span class="c-change-connector" aria-hidden="true">→</span><span><small>${r.query.yearTo} · selecție</small><strong>${compact(r.extra.toAmount)}</strong></span><span class="c-change-summary"><small>Diferența celor două sume</small><strong>${signed(r.extra.difference)}</strong></span></div><div class="c-change-table"><div class="c-change-head" aria-hidden="true"><span>Entitate</span><span>${r.query.yearFrom}</span><span>${r.query.yearTo}</span><span>Schimbare</span></div>${gs.map(g=>`<button class="c-change-row" data-action="q-evidence" data-key="${e(g.key)}"><strong>${e(g.label)}</strong><span data-label="${r.query.yearFrom}">${money(g.extra.fromAmount)}</span><span data-label="${r.query.yearTo}">${money(g.extra.toAmount)}</span><span data-label="Schimbare" class="c-change-diff ${g.extra.difference>=0?'is-up':'is-down'}">${signed(g.extra.difference)}${arrow}</span></button>`).join('')}</div>${topNote(r.extra.entities,r.query)}${note(`Clasament după mărimea absolută a diferenței. Sursele includ numai ${r.query.yearFrom} și ${r.query.yearTo}; anii dintre ei nu intră în calcul. Valoarea zero înseamnă lipsa unei înregistrări în extras pentru acel an.`)}`;
  }
  function network(r) {
    const gs=r.extra.partners.slice(0,6),pos=[[95,65],[95,175],[95,285],[645,65],[645,175],[645,285]];
    return `<div class="c-network-figure"><svg viewBox="0 0 740 350" role="img" aria-label="${e('Relațiile de achiziții ale '+r.extra.focus+'. Lista completă este dedesubt.')}">${gs.map((g,i)=>{const[x,y]=pos[i];return `<path class="c-network-line" d="M370 175 C${x<370?250:490} 175,${x<370?250:490} ${y},${x} ${y}" stroke-width="${Math.max(2,Math.sqrt(g.amount/r.total)*16)}"/>`;}).join('')}<circle cx="370" cy="175" r="59" class="c-network-focus"/><text x="370" y="165" text-anchor="middle" class="c-network-focus-text"><tspan x="370">${r.query.focusRole==='supplier'?'Furnizor':'Cumpărător'}</tspan><tspan x="370" dy="25">${count(r.count)} înreg.</tspan></text>${gs.map((g,i)=>{const[x,y]=pos[i],words=g.label.length>27?g.label.slice(0,25)+'…':g.label;return `<a role="button" tabindex="0" data-action="q-evidence" data-key="${e(g.key)}" aria-label="${e(g.label+': '+money(g.amount)+'. Vezi '+g.count+' înregistrări.')}" class="c-network-node"><rect x="${x-82}" y="${y-26}" width="164" height="52" rx="12"/><text x="${x}" y="${y-3}" text-anchor="middle"><tspan>${e(words)}</tspan><tspan x="${x}" dy="18" class="c-network-node-value">${e(compact(g.amount))}</tspan></text></a>`;}).join('')}</svg><p>${e(r.extra.focus)} <span>· relații de achiziții din selecție</span></p></div>${r.extra.partners.length>6?note(`Diagrama arată primii 6 din ${r.extra.partners.length} parteneri; lista de mai jos și sursele păstrează toți partenerii.`):''}${dataTable(r.extra.partners,r.query)}${note('O linie înseamnă achiziții între cumpărător și furnizor. Nu afirmă o relație de proprietate, afiliere sau legătură personală.')}`;
  }
  function sankey(r) {
    const flows=r.extra.flows,top=flows.slice(0,6),max=Math.max(...top.map(g=>g.amount),1);
    return `<div class="c-flow-title"><span class="c-eyebrow">${e(r.extra.focus)}</span><h3>Urmează fiecare sumă.</h3><p>De la partenerul de achiziții la domeniul în care apare.</p></div><div class="c-flow-head" aria-hidden="true"><span>Partener</span><span>Valoare înregistrată</span><span>Domeniu CPV</span></div><div class="c-flows">${top.map((g,i)=>`<button data-action="q-evidence" data-key="${e(g.key)}" class="c-flow-row"><strong>${e(g.extra.partner)}</strong><span class="c-flow-band" style="--c-flow-color:${colors[i%colors.length]};--c-flow-width:${Math.max(8,finiteRatio(g.amount,max))}%"><span>${compact(g.amount)}</span><i></i></span><span class="c-flow-category">${e(g.extra.category)}<small>${count(g.count)} înregistrări ${arrow}</small></span></button>`).join('')}</div>${flows.length>6?note(`Afișăm primele 6 din ${flows.length} fluxuri. Restul sunt păstrate în tabelul complet și în lista de înregistrări.`):''}<details class="c-equivalent"><summary>Toate fluxurile, cu valorile exacte</summary>${dataTable(flows,{measure:'value'})}</details>${note('Fiecare înregistrare aparține unui singur flux partener–domeniu. Suma tuturor fluxurilor este egală cu totalul răspunsului.')}`;
  }
  function fact(r) {
    return `<div class="c-fact-answer"><span class="c-fact-mark" aria-hidden="true">${r.extra.found?'✓':'∅'}</span><div><span class="c-eyebrow">Verificarea relației</span><h3>${r.extra.found?'Da, în datele selectate.':'Nu am găsit în datele selectate.'}</h3><p><strong>${e(r.extra.buyer)}</strong><span class="c-fact-arrow">→</span><strong>${e(r.extra.supplier)}</strong></p><div class="c-fact-numbers"><span><strong>${count(r.count)}</strong><small>${r.count===1?'înregistrare':'înregistrări'} în selecție</small></span><span><strong>${compact(r.total)}</strong><small>${money(r.total)} · exact</small></span></div>${allLink('Deschide înregistrările dintre cele două părți')}</div></div>${r.count?dataTable(r.groups,{measure:'value'}):''}${note('Răspunsul se referă strict la cele două identități și la condițiile aplicate. Eșantionul nu permite concluzii despre întreaga lor istorie în SEAP.')}`;
  }
  function profileTable(r) {
    return `<div class="c-cohort-table"><div class="c-cohort-head" aria-hidden="true"><span>Autoritate</span><span>Indice de risc</span><span>Înregistrări DA</span><span>Valoare în profil</span><span>Surse</span></div>${r.extra.profileGroups.map(g=>`<div class="c-cohort-row ${g.id===r.query.authorityId?'is-focus':''}"><strong>${e(g.label)}${g.id===r.query.authorityId?'<small>Profilul ales</small>':''}</strong><span data-label="Indice de risc">${number(g.profile.cri)} <small>/ 1</small></span><span data-label="Înregistrări DA">${count(g.profile.nDas)}</span><span class="c-cohort-value" data-label="Valoare în profil">${money(g.profile.totalRon)}</span>${link(g,'Vezi înregistrările')}</div>`).join('')}</div>`;
  }
  function distribution(r) {
    const bins=[0,0,0,0,0];r.extra.cohort.forEach(p=>bins[Math.min(4,Math.floor(Number(p.cri)*5+1e-8))]++);
    const max=Math.max(...bins,1), labels=['0–0,19','0,20–0,39','0,40–0,59','0,60–0,79','0,80–1'];
    const focal=r.extra.focus;
    return `<div class="c-distribution-intro"><div><span class="c-eyebrow">${focal?e(focal.label):'Profil în afara populației selectate'}</span><h3>${focal?number(focal.profile.cri):'—'}<small> / 1</small></h3><p>Indicele de risc publicat</p></div><div class="c-cohort-context"><strong>${r.extra.allEqual?'Aceeași valoare în toate profilurile selectate.':'Un reper în populația selectată.'}</strong><p>${r.extra.allEqual?`Toate cele ${r.extra.cohort.length} autorități au indicele ${number(r.extra.minCri)}. Graficul păstrează această egalitate; extrasul nu permite o ierarhie după acest indice.`:`Populația include ${r.extra.cohort.length} autorități din extras, cu minimum 10 înregistrări DA fiecare.`}</p><span>Populație din extras · nu percentilă națională</span></div></div><div class="c-histogram" role="group" aria-label="${e('Distribuția indicelui: '+bins.map((n,i)=>labels[i]+': '+n+' autorități').join('; '))}">${bins.map((n,i)=>`<${n?'button':'div'} class="c-histogram-bin" ${n?'data-action="q-evidence" data-key="riskbin:'+i+'" aria-label="'+e(n+' autorități cu indice '+labels[i]+'. Vezi înregistrările.')+'"':''}><strong>${n}</strong><span><i style="height:${n/max*100}%"></i></span><small>${labels[i]}</small></${n?'button':'div'}>`).join('')}</div><div class="c-axis-label">Indice de risc · ${r.extra.cohort.length} autorități eligibile</div>${profileTable(r)}${methodology(r)}`;
  }
  function scatter(r) {
    const gs=r.extra.profileGroups,max=Math.max(...gs.map(g=>Number(g.profile.nDas)),1),width=740,height=300;
    return `<div class="c-scatter-context"><span class="c-eyebrow">${gs.length} autorități · minimum 10 înregistrări DA</span><p>${r.extra.allEqual?'Același indice, volume diferite. Punctele se află pe aceeași linie pentru că datele reale arată aceeași valoare de risc.':'Fiecare punct este o autoritate din populația selectată.'}</p></div><div class="c-scatter-chart"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Indice de risc pe axa verticală, număr de înregistrări DA pe axa orizontală. Valorile exacte sunt în tabel.">${[0,.2,.4,.6,.8,1].map(v=>{const y=245-v*205;return `<path d="M55 ${y}H700" class="c-scatter-grid"/><text x="40" y="${y+4}" text-anchor="end" class="c-axis-text">${number(v)}</text>`;}).join('')}${[0,.25,.5,.75,1].map(v=>`<text x="${55+v*630}" y="272" text-anchor="middle" class="c-axis-text">${count(Math.round(max*v))}</text>`).join('')}<text x="55" y="19" class="c-axis-title">Indice de risc</text>${gs.map((g,i)=>{const x=55+Number(g.profile.nDas)/max*630,y=245-Number(g.profile.cri)*205,labelY=i%2?y+31:y-21,labelX=g.id==='2146445'?Math.max(265,x+55):x,label=g.id==='2143172'?'Consiliul Județean':g.label;return `<a role="button" tabindex="0" data-action="q-evidence" data-key="${e(g.key)}" class="c-scatter-point" aria-label="${e(g.label+': indice '+number(g.profile.cri)+', '+count(g.profile.nDas)+' înregistrări. Vezi sursele.')}" style="--c-point:${colors[i%colors.length]}"><circle cx="${x}" cy="${y}" r="8"/><path d="M${x} ${y+9}L${labelX} ${labelY-12}" class="c-scatter-leader" style="${labelX===x?'display:none':''}"/><text x="${labelX}" y="${labelY}" text-anchor="${labelX>580?'end':labelX<130||labelX!==x?'start':'middle'}">${e(label)}</text><title>${e(g.label+': '+number(g.profile.cri)+' / 1 · '+count(g.profile.nDas)+' DA')}</title></a>`;}).join('')}</svg></div><div class="c-axis-label">Număr de înregistrări DA în profil · inclusiv oferte neacceptate</div>${profileTable(r)}${methodology(r)}`;
  }
  function entityCard(r) {
    const winners=r.extra.winners,criterion=r.query.rankBy==='risk'?'indicele de risc':r.query.rankBy==='count'?'numărul de înregistrări':'valoarea înregistrată';
    return `<div class="c-winner-intro"><span class="c-winner-star" aria-hidden="true">✳</span><div><span class="c-eyebrow">Reper în populația selectată</span><h3>${winners.length>1?`${winners.length} autorități la egalitate.`:e(winners[0]?.label||'Niciun profil eligibil')}</h3><p>Criteriu: <strong>${e(criterion)}</strong>. ${r.extra.cohort.length} autorități eligibile în extras, fiecare cu minimum 20 de înregistrări DA.</p>${winners.length>1?'<p>Toate rezultatele la egalitate sunt afișate; ordinea nu indică un risc mai mare.</p>':''}</div></div><div class="c-winners ${winners.length>1?'has-ties':''}">${winners.map(g=>profileCard(g,r,{compactCard:winners.length>1})).join('')}</div>${winners.length<r.extra.cohort.length?`<details class="c-equivalent"><summary>Vezi întreaga populație de comparație</summary>${profileTable(r)}</details>`:''}${r.query.rankBy==='risk'?methodology(r):''}`;
  }
  function render(r,layout='bars') {
    if(r.extra?.unavailable)return `<div class="c-empty-answer"><h3>Nu există profiluri eligibile în acest extras.</h3><p>Schimbă județul sau tipul de autoritate. Un profil lipsă nu primește un scor estimat.</p></div>`;
    if(!r.count&&!r.extra.profile&&r.block!=='fact_check')return empty(r);
    if(layout==='table'&&!['table','breakdown','stat','trend','fact_check'].includes(r.block)) {
      const content=r.extra.profile?profileTable(r)+methodology(r):dataTable(r.block==='network'?r.extra.partners:r.block==='sankey'?r.extra.flows:r.groups,r.query);
      return `<div class="c-answer-visual c-answer-${e(r.block)} c-answer-table-view">${content}</div>`;
    }
    const renderers={table:ranking,stat,timeseries,map,breakdown,compare,trend,network,sankey,fact_check:fact,distribution,scatter,entity_card:entityCard};
    return `<div class="c-answer-visual c-answer-${e(r.block)}">${renderers[r.block](r,layout)}</div>`;
  }
  window.Answers={render};
})();
