const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let paused=false,filter='all',page=1,dirty=false,config={min:50,max:70},toastTimer;
const validViews=['colectare','procesare','fisiere','jurnal','conturi'];
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200)}
function renderView(focus=false){const v=new URL(location.href).searchParams.get('sectiune')||'colectare',view=validViews.includes(v)?v:'colectare';$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==view);$$('nav [data-view]').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#draft-note').hidden=!dirty||view==='colectare';document.title=$('nav [aria-current]').textContent.trim()+' · Administrare · cinecâștigă?';if(focus){$('#content').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-view]');if(!a||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();history.pushState({},'',a.href);renderView(true)});window.addEventListener('popstate',()=>renderView(true));
$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('#theme').textContent=dark?'Temă luminoasă':'Temă întunecată'};
function status(){forecast();const s=$('#scenario').value;$('#global-collection').textContent=s==='processing'?'în pauză':paused?'oprită manual':s==='retry'?'reîncercare în 5 min':'activă';$('#global-processing').textContent=s==='processing'?'în curs':'mâine, 05:00';$('#global-alert').hidden=s!=='retry';$('#collection-title').textContent=s==='processing'?'Colectarea așteaptă încheierea procesării.':paused?'Colectarea este pe pauză.':s==='retry'?'Aceeași cerere va fi reîncercată după 5 minute.':'Următoarea cerere, în aproximativ un minut.';$('#collection-badge').textContent=(s==='live'||s==='learning')&&!paused?'În ritmul stabilit':'În așteptare';$('#pause').disabled=s==='processing';$('#pause').textContent=paused?'Reia colectarea':'Pune colectarea pe pauză';$('#processing-title').textContent=s==='processing'?'Actualizarea de la 05:00 este în curs.':'Următoarea actualizare: mâine, la 05:00.';$('#processing-copy').textContent=s==='processing'?'Date și statistici · 18 minute de la pornire. Site-ul rămâne în mentenanță până trec verificările.':'Radiografie, statistici și căutare, în fiecare noapte. Semnalele de risc se recalculează duminica.';$('#processing-badge').textContent=s==='processing'?'Mentenanță':'Site disponibil';$$('.steps li').forEach((li,i)=>li.classList.toggle('current',s==='processing'&&i===1))}
$('#scenario').onchange=status;$('#pause').onclick=()=>{paused=!paused;status();toast(paused?'Colectare pusă pe pauză în simulare.':'Colectare reluată în simulare.')};
$('#settings').oninput=()=>{const min=Number($('#min').value),max=Number($('#max').value),valid=Number.isInteger(min)&&min>=1&&Number.isInteger(max)&&max>=min&&max<=3600;dirty=min!==config.min||max!==config.max;$('#save').disabled=!valid||!dirty;$('#save').textContent=dirty?'Aplică modificările':'Setările sunt la zi';$('#rate').textContent=valid?'≈ '+Math.round(7200/(min+max))+' cereri / oră':'Interval nevalid';$('#settings-feedback').textContent=valid?'Modificările se aplică doar după salvare.':'Folosește valori întregi între 1 și 3600; maximul trebuie să fie cel puțin egal cu minimul.'};
$('#settings').onsubmit=e=>{e.preventDefault();config={min:Number($('#min').value),max:Number($('#max').value)};$('#active-delay').textContent=config.min+'–'+config.max+' secunde';dirty=false;$('#save').disabled=true;$('#save').textContent='Setările sunt la zi';$('#draft-note').hidden=true;toast('Interval salvat doar în mockup.')};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
$('#schedule').onsubmit=e=>{e.preventDefault();toast('Program salvat în simulare. Nu modifică serverul.')};
const files=['Caiet de sarcini — lucrări de reparații.pdf.p7s','Formulare pentru ofertanți.pdf','Specificații tehnice — echipamente.pdf.p7s','Anexe și cantități de lucrări.pdf'];$('#file-list').innerHTML=files.map((f,i)=>`<div class="file-row"><div><b>${f}</b><p>Solicitare demonstrativă · în așteptarea preluării</p></div><span>Poziția ${i+1}</span></div>`).join('');
const logs=Array.from({length:14},(_,i)=>({id:867-i,time:'09:'+String(42-i).padStart(2,'0')+':08',name:['Achiziții directe','Anunțuri de participare','Anunțuri de atribuire'][i%3],error:i===3||i===9}));
function journal(){const list=logs.filter(r=>filter!=='errors'||r.error);$('#rows').innerHTML=list.slice((page-1)*10,page*10).map(r=>`<tr><td>${r.time}</td><td>${r.name}<small>Cererea #${r.id}</small></td><td><span class="result ${r.error?'error':''}">${r.error?'Timeout':'200 · reușit'}</span></td><td>${r.error?'45,0':'1,2'} s</td><td><details><summary>Detalii</summary><p class="footnote">POST · date simulate<br>${r.error?'Termenul de 45 secunde a fost depășit.':'Răspuns arhivat.'}</p></details></td></tr>`).join('');$('#range').textContent=`${(page-1)*10+1}–${Math.min(page*10,list.length)} din ${list.length} cereri`;$('#prev').disabled=page===1;$('#next').disabled=page*10>=list.length}
$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;page=1;$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});journal()});$('#prev').onclick=()=>{page--;journal()};$('#next').onclick=()=>{page++;journal()};$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(logs,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jurnal-DEMO.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#add-account').onclick=()=>{const open=$('#account-form').hidden;$('#account-form').hidden=!open;$('#add-account').setAttribute('aria-expanded',String(open));if(open)$('#account-form input').focus()};$('#account-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),tr=document.createElement('tr');for(const value of [data.get('name')+' · '+data.get('email'),'Watchdog','Activ','Cont demonstrativ']){const td=document.createElement('td');td.textContent=value;tr.append(td)}$('#users').append(tr);e.target.reset();e.target.hidden=true;$('#add-account').setAttribute('aria-expanded','false');toast('Cont fictiv adăugat. Nu s-a trimis niciun email.')};$('.account-toggle').onclick=e=>{const b=e.target,badge=b.closest('tr').querySelector('.badge'),active=b.textContent==='Dezactivează';b.textContent=active?'Reactivează':'Dezactivează';badge.textContent=active?'Dezactivat':'Activ';badge.classList.toggle('neutral',active);toast('Acces modificat doar în simulare.')};
journal();status();renderView();

function forecast(){const mode=$('#scenario').value,learning=mode==='learning',waiting=paused||mode==='processing'||mode==='retry';$('.recovery-overview').dataset.waiting=String(waiting);$('#overall-percent').textContent=learning?'În evaluare':'≈ 30%';$('.recovery-percent>span').hidden=learning;$('#overall-days').textContent=learning?'Strângem date pentru o estimare':paused?'Termen suspendat cât colectarea este oprită':mode==='processing'?'Ultima estimare: 7–12 zile':mode==='retry'?'Ultima estimare: 7–12 zile':'Aproximativ 7–12 zile până la zi';$('#overall-context').textContent=learning?'Avem nevoie de un eșantion reprezentativ din fiecare flux și de ritmul efectiv de colectare.':paused?'Progresul se păstrează. Recalculăm zilele rămase după reluare.':mode==='processing'?'Colectarea așteaptă procesarea. Actualizăm estimarea după reluare.':mode==='retry'?'Așteptăm reîncercarea cererii. Estimarea se actualizează când colectarea avansează.':'La ritmul efectiv recent, cu pauze și cu achizițiile noi care apar între timp.';$('#overall-progress').hidden=learning;$('#forecast-summary').textContent=learning?'în evaluare':paused?'≈ 30% · în pauză':waiting?'≈ 30% · în așteptare':'≈ 30% · 7–12 zile';$('#forecast-confidence').textContent=learning?'Fără procent sau termen până avem suficiente date':waiting?'Ultimul calcul păstrat · colectarea așteaptă':'Estimare preliminară · se ajustează pe parcurs'}
