import { describe, it, expect } from "vitest";
import { boundZoom, zoomAt, INITIAL_ZOOM, lotColumns, sliceIncludes } from "./radiografie-view";
import type { MatrixRow, SliceRow } from "./radiografie";
const row = (contractId: string, supplierId: string, d = "2023-01-01"): MatrixRow => ({ cls: "4523", notice: "CAN1", contractId, supplierId, supplierName: supplierId, d, nWinners: 1, single: null, tr: null, vFull: 100, framework: false });
describe("radiografie exploration", () => {
    it("keeps the cursor's data coordinate fixed while zooming", () => { const before = { k: 2, x: .15, y: .25 }, next = zoomAt(before, 2, .4, .3); expect(next.x + .4 / next.k).toBeCloseTo(before.x + .4 / before.k); expect(next.y + .3 / next.k).toBeCloseTo(before.y + .3 / before.k); });
    it("bounds scale and pan; zooming out restores the full domain", () => { expect(boundZoom({ k: 50, x: 5, y: -1 })).toEqual({ k: 12, x: 1 - 1 / 12, y: 0 }); expect(zoomAt({ k: 4, x: .5, y: .1 }, .01, .5, .5)).toEqual(INITIAL_ZOOM); });
    it("counts each consortium contract once and normalizes member order", () => { const cols = lotColumns([row("1", "b"), row("1", "a"), row("1", "a"), row("2", "a"), row("2", "b"), row("3", "solo")]); expect(cols).toHaveLength(1); expect(cols[0]!.contracts).toHaveLength(3); expect(cols[0]!.cells.get("a+b")!.contracts).toHaveLength(2); expect(cols[0]!.cells.get("a+b")!.contracts.reduce((a, r) => a + r.vFull, 0)).toBe(200); });
    it("keeps all members when selecting a year and excludes small procedures", () => { expect(lotColumns([row("1", "a"), row("1", "b"), row("2", "a")])).toEqual([]); expect(lotColumns([row("1", "a"), row("2", "a"), row("3", "b")], 2024, 2025)).toEqual([]); });
    it("preserves per-record threshold eligibility, type and CPV membership", () => { const s = { d0: "2023-01-01", d1: "2023-02-28", cpvClass: "7131", purchaseType: "goods_services" } as SliceRow; const p = { d: "2023-01-15", v: 999, cls: "7131", cpvName: "", gap: null, ceiling: 1000, purchaseType: "goods_services" as const }; expect(sliceIncludes(s, p)).toBe(true); expect(sliceIncludes(s, { ...p, v: 1000 })).toBe(false); expect(sliceIncludes(s, { ...p, ceiling: null })).toBe(false); expect(sliceIncludes(s, { ...p, purchaseType: "works" })).toBe(false); expect(sliceIncludes(s, { ...p, cls: "7132" })).toBe(false); expect(sliceIncludes(s, { ...p, d: "2023-03-01" })).toBe(false); });
});
