/* Authentic local database extract. See MOCK_DATA.meta for coverage and scope. */
window.MOCK_DATA = {
  "meta": {
    "snapshotDate": "2026-09-12",
    "periodLabel": "2018–2026 · date importate în proiect",
    "latestSelectedAuthorityActivity": "2026-07-15",
    "note": "Extras din baza locală a proiectului. Agregatele reproduc marturile existente; selecția interactivă este un eșantion, nu totalitatea achizițiilor. Valorile sunt contractate, nu dovezi ale plăților efective. Titlurile achizițiilor directe sunt categoriile CPV, nu titlurile originale SICAP.",
    "sampleSelection": "Patru autorități: ultimele cinci contracte cu câștigător unic și trei dintre cele mai mari începând cu 2024, plus ultimele patru achiziții directe cu valori valide per autoritate.",
    "aggregateScope": "Agregate existente pentru întreaga bază importată; nu se recalculează din eșantion și nu se filtrează după selecția interactivă. Județul este sediul autorității, nu locul execuției.",
    "source": "Baza locală SEAP: marts.entity_profile, marts.national_stats, marts.spend_by_county, marts.spend_by_cpv, marts.contract_transactions, marts.da_transactions; core.contracts.",
    "sourceLinkStatus": "Linkuri originale construite după apps/web/lib/elicitatie.ts. SICAP nu este accesibil de pe acest dispozitiv; nu au fost reverificate în direct."
  },
  "headline": {
    "suppliers": 163736,
    "authorities": 33225,
    "totalSpend": 823037737693.76
  },
  "counties": [
    {
      "county": "Bucuresti",
      "totalRon": 264168539541.88,
      "n": 1459
    },
    {
      "county": "Cluj",
      "totalRon": 37496684156.01,
      "n": 497
    },
    {
      "county": "Constanta",
      "totalRon": 30161765481.92,
      "n": 467
    },
    {
      "county": "Ilfov",
      "totalRon": 24419054459.75,
      "n": 256
    },
    {
      "county": "Iasi",
      "totalRon": 23185805827.05,
      "n": 544
    },
    {
      "county": "Sibiu",
      "totalRon": 22610037636.92,
      "n": 369
    },
    {
      "county": "Timis",
      "totalRon": 22025040763.12,
      "n": 489
    },
    {
      "county": "Dolj",
      "totalRon": 19496298139.5,
      "n": 498
    },
    {
      "county": "Prahova",
      "totalRon": 19081033129.35,
      "n": 508
    },
    {
      "county": "Mures",
      "totalRon": 18403241380.84,
      "n": 414
    },
    {
      "county": "Bihor",
      "totalRon": 18124300013.07,
      "n": 439
    },
    {
      "county": "Brasov",
      "totalRon": 17500519601.45,
      "n": 441
    },
    {
      "county": "Galati",
      "totalRon": 16464457581.42,
      "n": 413
    },
    {
      "county": "Bacau",
      "totalRon": 15365477727.57,
      "n": 393
    },
    {
      "county": "Suceava",
      "totalRon": 14817909129.25,
      "n": 448
    },
    {
      "county": "Dambovita",
      "totalRon": 12559376331.13,
      "n": 345
    },
    {
      "county": "Arges",
      "totalRon": 11960133806.82,
      "n": 444
    },
    {
      "county": "Maramures",
      "totalRon": 11753103892.23,
      "n": 359
    },
    {
      "county": "Gorj",
      "totalRon": 11430317031.9,
      "n": 279
    },
    {
      "county": "Hunedoara",
      "totalRon": 10994216126.46,
      "n": 288
    },
    {
      "county": "Arad",
      "totalRon": 10918303088.76,
      "n": 379
    },
    {
      "county": "Valcea",
      "totalRon": 10130970070.84,
      "n": 306
    },
    {
      "county": "Neamt",
      "totalRon": 9939979442.62,
      "n": 329
    },
    {
      "county": "Olt",
      "totalRon": 9816547711.27,
      "n": 376
    },
    {
      "county": "Buzau",
      "totalRon": 9526469972.41,
      "n": 360
    },
    {
      "county": "Vrancea",
      "totalRon": 9327298531.91,
      "n": 308
    },
    {
      "county": "Vaslui",
      "totalRon": 8957405483.13,
      "n": 321
    },
    {
      "county": "Alba",
      "totalRon": 8952330482.05,
      "n": 333
    },
    {
      "county": "Satu Mare",
      "totalRon": 8875018063.88,
      "n": 282
    },
    {
      "county": "Botosani",
      "totalRon": 8739233086.32,
      "n": 331
    },
    {
      "county": "Bistrita-Nasaud",
      "totalRon": 8612793618.19,
      "n": 260
    },
    {
      "county": "Harghita",
      "totalRon": 7662092844.57,
      "n": 347
    },
    {
      "county": "Tulcea",
      "totalRon": 7479794068.73,
      "n": 233
    },
    {
      "county": "Caras-Severin",
      "totalRon": 7444209584.2,
      "n": 294
    },
    {
      "county": "Braila",
      "totalRon": 6968727531.68,
      "n": 314
    },
    {
      "county": "Calarasi",
      "totalRon": 6728214638.21,
      "n": 275
    },
    {
      "county": "Mehedinti",
      "totalRon": 6217813555.28,
      "n": 243
    },
    {
      "county": "Giurgiu",
      "totalRon": 6180638570.55,
      "n": 217
    },
    {
      "county": "Teleorman",
      "totalRon": 6144057248.73,
      "n": 333
    },
    {
      "county": "Salaj",
      "totalRon": 5615508662.42,
      "n": 247
    },
    {
      "county": "Ialomita",
      "totalRon": 5282249586.51,
      "n": 255
    },
    {
      "county": "Covasna",
      "totalRon": 4445199007.44,
      "n": 224
    }
  ],
  "categories": [
    {
      "division": "45",
      "nameRo": "Lucrări de construcţii",
      "totalRon": 427945575181.94
    },
    {
      "division": "33",
      "nameRo": "Echipamente medicale, produse farmaceutice şi produse de îngrijire personală",
      "totalRon": 49078337966.51
    },
    {
      "division": "34",
      "nameRo": "Echipament de transport şi produse auxiliare pentru transport",
      "totalRon": 38861184810.57
    },
    {
      "division": "09",
      "nameRo": "Produse petroliere, combustibil, electricitate şi alte surse de energie",
      "totalRon": 31648844751.24
    },
    {
      "division": "71",
      "nameRo": "Servicii de arhitectură, de construcţii, de inginerie şi de inspecţie",
      "totalRon": 30351699785.19
    },
    {
      "division": "50",
      "nameRo": "Servicii de reparare şi întreţinere",
      "totalRon": 26845966503.49
    },
    {
      "division": "90",
      "nameRo": "Servicii de evacuare a apelor reziduale, de eliminare a deşeurilor, de igienizare şi servicii privind mediul",
      "totalRon": 25905510623.19
    },
    {
      "division": "79",
      "nameRo": "Servicii pentru întreprinderi: drept, marketing, consultanţă, recrutare, tipărire şi securitate",
      "totalRon": 21953523124.61
    },
    {
      "division": "30",
      "nameRo": "Echipament informatic şi accesorii de birou, cu excepţia mobilierului şi a pachetelor software",
      "totalRon": 13286055851.18
    },
    {
      "division": "44",
      "nameRo": "Structuri şi materiale de construcţii; produse auxiliare pentru construcţii (cu excepţia aparatelor electrice)",
      "totalRon": 12274928142.67
    },
    {
      "division": "60",
      "nameRo": "Servicii de transport (cu excepţia transportului de deşeuri)",
      "totalRon": 12119739895.49
    },
    {
      "division": "72",
      "nameRo": "Servicii IT: consultanţă, dezvoltare de software, internet şi asistenţă",
      "totalRon": 11387253315.89
    },
    {
      "division": "39",
      "nameRo": "Mobilă (inclusiv mobilă de birou), accesorii de mobilier, aparate de uz casnic (exclusiv dispozitive de iluminat) şi produse de curăţat",
      "totalRon": 10608890119.62
    },
    {
      "division": "35",
      "nameRo": "Echipament de securitate, de luptă împotriva incendiilor, de poliţie şi de apărare",
      "totalRon": 10481054445.33
    },
    {
      "division": "15",
      "nameRo": "Alimente, băuturi, tutun şi produse conexe",
      "totalRon": 9287676908.03
    },
    {
      "division": "48",
      "nameRo": "Pachete software şi sisteme informatice",
      "totalRon": 8179766400.41
    },
    {
      "division": "42",
      "nameRo": "Echipamente industriale",
      "totalRon": 7836708615.3
    },
    {
      "division": "38",
      "nameRo": "Echipamente de laborator, optice şi de precizie (cu excepţia ochelarilor)",
      "totalRon": 7470726171.04
    },
    {
      "division": "32",
      "nameRo": "Echipament de radio, televiziune, comunicaţii, telecomunicaţii şi articole conexe",
      "totalRon": 7256235962.7
    },
    {
      "division": "77",
      "nameRo": "Servicii pentru agricultură, silvicultură, horticultură, acvacultură şi apicultură",
      "totalRon": 6671232790.64
    },
    {
      "division": "31",
      "nameRo": "Maşini, aparate, echipamente şi consumabile electrice; iluminat",
      "totalRon": 6344085439.82
    },
    {
      "division": "85",
      "nameRo": "Servicii de sănătate şi servicii de asistenţă socială",
      "totalRon": 5890478049.09
    },
    {
      "division": "66",
      "nameRo": "Servicii financiare şi de asigurare",
      "totalRon": 4206336589.1
    },
    {
      "division": "64",
      "nameRo": "Servicii poştale şi de telecomunicaţii",
      "totalRon": 4194720766.83
    },
    {
      "division": "24",
      "nameRo": "Produse chimice",
      "totalRon": 3947930942.03
    },
    {
      "division": "43",
      "nameRo": "Utilaje pentru minerit, cariere de piatră şi construcţii",
      "totalRon": 3349031297.45
    },
    {
      "division": "14",
      "nameRo": "Produse de minerit, metale de bază şi produse conexe",
      "totalRon": 3256210104.88
    },
    {
      "division": "55",
      "nameRo": "Servicii hoteliere, de restaurant şi de vânzare cu amănuntul",
      "totalRon": 3250281800.56
    },
    {
      "division": "03",
      "nameRo": "Produse agricole, de fermă, de pescuit, de silvicultură şi produse conexe",
      "totalRon": 3063786563.43
    },
    {
      "division": "18",
      "nameRo": "Îmbrăcăminte, încălţăminte, articole de voiaj şi accesorii",
      "totalRon": 2911754703.68
    },
    {
      "division": "22",
      "nameRo": "Imprimate şi produse conexe",
      "totalRon": 1956125576.64
    },
    {
      "division": "65",
      "nameRo": "Utilităţi publice",
      "totalRon": 1633448211.81
    },
    {
      "division": "37",
      "nameRo": "Instrumente muzicale, articole sportive, jocuri, jucării, obiecte de artizanat, obiecte de artă şi accesorii",
      "totalRon": 1185753476.97
    },
    {
      "division": "76",
      "nameRo": "Servicii privind industria petrolului şi a gazului",
      "totalRon": 1160699611.33
    },
    {
      "division": "63",
      "nameRo": "Servicii de transport anexe şi conexe; servicii de agenţii de turism",
      "totalRon": 1021720718.3
    },
    {
      "division": "92",
      "nameRo": "Servicii de recreere, culturale şi sportive",
      "totalRon": 1021149807.43
    },
    {
      "division": "16",
      "nameRo": "Utilaje agricole",
      "totalRon": 989536515.85
    },
    {
      "division": "98",
      "nameRo": "Alte servicii comunitare, sociale şi personale",
      "totalRon": 989221255.33
    },
    {
      "division": "80",
      "nameRo": "Servicii de învăţământ şi formare profesională",
      "totalRon": 950908490.55
    },
    {
      "division": "51",
      "nameRo": "Servicii de instalare (cu excepţia programelor software)",
      "totalRon": 860866682.33
    },
    {
      "division": "19",
      "nameRo": "Produse din piele, materiale textile, din plastic şi din cauciuc",
      "totalRon": 438058940.21
    },
    {
      "division": "73",
      "nameRo": "Servicii de cercetare şi de dezvoltare şi servicii conexe de consultanţă",
      "totalRon": 383099724.47
    },
    {
      "division": "75",
      "nameRo": "Servicii de administraţie publică, de apărare şi de asigurări sociale",
      "totalRon": 380255414.74
    },
    {
      "division": "70",
      "nameRo": "Servicii imobiliare",
      "totalRon": 166511256.47
    },
    {
      "division": "41",
      "nameRo": "Apă captată şi epurată",
      "totalRon": 34797666.84
    }
  ],
  "authorities": [
    {
      "id": "2084803",
      "name": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "county": "Cluj",
      "totalRon": 617419965.38,
      "nContracts": 3312,
      "nDas": 23747,
      "firstActivity": "2018-08-29",
      "lastActivity": "2026-07-15"
    },
    {
      "id": "2143172",
      "name": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "county": "Cluj",
      "totalRon": 3740755162.18,
      "nContracts": 647,
      "nDas": 876,
      "firstActivity": "2018-03-20",
      "lastActivity": "2026-07-10"
    },
    {
      "id": "2146146",
      "name": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "county": "Bucuresti",
      "totalRon": 38251066388.36,
      "nContracts": 5224,
      "nDas": 3679,
      "firstActivity": "2018-01-05",
      "lastActivity": "2026-07-15"
    },
    {
      "id": "2146445",
      "name": "Municipiul Cluj-Napoca",
      "county": "Cluj",
      "totalRon": 3568556321.37,
      "nContracts": 583,
      "nDas": 4565,
      "firstActivity": "2018-04-20",
      "lastActivity": "2026-07-15"
    }
  ],
  "records": [
    {
      "id": "ct-405405",
      "source": "contract",
      "code": "633230",
      "title": "servicii integrate de analiza, care vor fi aplicate pe sistemele deja existente și detinute, pentru dezvoltarea unei analize privind managementul adaptiv al semaforizarii urbane în timp real, în cadrul proiectului ZERO-MOVE - Zero Emission Mobility Initiatives",
      "titleKind": "contract",
      "amount": 495609.3,
      "date": "2026-06-29",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2162205",
      "supplierName": "TRAFFIC PLAN",
      "county": "Cluj",
      "cpvCode": "72240000-9",
      "cpvName": "Servicii de analiză şi de programare de sisteme",
      "category": "IT și echipamente",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100639084",
      "internalUrl": "/contracte/107792160",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Procedura simplificata",
      "flags": [],
      "noticeId": "100639084"
    },
    {
      "id": "ct-437344",
      "source": "contract",
      "code": "572984",
      "title": "Delegarea gestiunii activitatii de operare a centrului de colectare prin aport voluntar a deseurilor din Municipiul Cluj-Napoca",
      "titleKind": "contract",
      "amount": 5738019,
      "date": "2026-06-01",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2102072",
      "supplierName": "REGIA AUTONOMA A DOMENIULUI PUBLIC CLUJ-NAPOCA",
      "county": "Cluj",
      "cpvCode": "90500000-2",
      "cpvName": "Servicii privind deşeurile menajere şi deşeurile",
      "category": "Curățenie și mediu",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100633076",
      "internalUrl": "/contracte/107684818",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100633076"
    },
    {
      "id": "ct-366680",
      "source": "contract",
      "code": "557663",
      "title": "Aparate si echipamente de joaca pentru copii cu dizabilitati, aparate de joaca pentru copii (sub 3 ani, 2-6 ani, 3-14 ani) si aparate de joaca confectionate preponderent din lemn in municipiul Cluj-Napoca",
      "titleKind": "contract",
      "amount": 6409800,
      "date": "2026-05-24",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2062273",
      "supplierName": "URBAN MARKET SRL",
      "county": "Cluj",
      "cpvCode": "43325000-7",
      "cpvName": "Echipament pentru parcuri şi terenuri de joacă",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100635599",
      "internalUrl": "/contracte/107726751",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100635599"
    },
    {
      "id": "ct-366679",
      "source": "contract",
      "code": "557584",
      "title": "Aparate si echipamente de joaca pentru copii cu dizabilitati, aparate de joaca pentru copii (sub 3 ani, 2-6 ani, 3-14 ani) si aparate de joaca confectionate preponderent din lemn in municipiul Cluj-Napoca",
      "titleKind": "contract",
      "amount": 3604490,
      "date": "2026-05-24",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2117279",
      "supplierName": "DUPEX",
      "county": "Cluj",
      "cpvCode": "43325000-7",
      "cpvName": "Echipament pentru parcuri şi terenuri de joacă",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100635599",
      "internalUrl": "/contracte/107726679",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100635599"
    },
    {
      "id": "ct-455884",
      "source": "contract",
      "code": "538733",
      "title": "Proiectare si executie „Realizarea unui parc fotovoltaic pentru producerea energiei electrice prin utilizarea panourilor fotovoltaice în Municipiul Cluj-Napoca, Valea Chintăului”",
      "titleKind": "contract",
      "amount": 11653306.39,
      "date": "2026-05-17",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2161986",
      "supplierName": "VOLTA X SOLAR SYSTEMS S.R.L.",
      "county": "Cluj",
      "cpvCode": "45200000-9",
      "cpvName": "Lucrări de construcţii complete sau parţiale şi lucrări publice",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100629539",
      "internalUrl": "/contracte/107643106",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Procedura simplificata",
      "flags": [],
      "noticeId": "100629539"
    },
    {
      "id": "ct-632867",
      "source": "contract",
      "code": "547457",
      "title": "Act aditional nr. 2 la ctr. cu nr. 280505/07.03.2023- Contract de furnizare a 40 autobuze electrice articulate de 18 m, 18 statii de incarcare lenta si 6 statii de incarcare rapida",
      "titleKind": "contract",
      "amount": 147056000,
      "date": "2025-05-29",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2270401",
      "supplierName": "SOLARIS BUS & COACH sp. z. o. o",
      "county": "Cluj",
      "cpvCode": "34144910-0",
      "cpvName": "Autobuze electrice",
      "category": "Transport",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100548732",
      "internalUrl": "/contracte/106358004",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100548732"
    },
    {
      "id": "ct-544642",
      "source": "contract",
      "code": "949658",
      "title": "Întreţinere şi amenajare  zone verzi și locuri de joacă - pe raza municipiului Cluj-Napoca, precum și  zonele verzi din cimitirele administrate de Consiliul local al municipiului Cluj-Napoca",
      "titleKind": "contract",
      "amount": 64456577.2,
      "date": "2025-12-17",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2084170",
      "supplierName": "ECO GARDEN CONSTRUCT SRL",
      "county": "Cluj",
      "cpvCode": "77310000-6",
      "cpvName": "Amenajare şi întreţinere de spaţii verzi",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100599370",
      "internalUrl": "/contracte/107126001",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100599370"
    },
    {
      "id": "ct-544643",
      "source": "contract",
      "code": "949644",
      "title": "Întreţinere şi amenajare  zone verzi și locuri de joacă - pe raza municipiului Cluj-Napoca, precum și  zonele verzi din cimitirele administrate de Consiliul local al municipiului Cluj-Napoca",
      "titleKind": "contract",
      "amount": 64456577.2,
      "date": "2025-12-17",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2084170",
      "supplierName": "ECO GARDEN CONSTRUCT SRL",
      "county": "Cluj",
      "cpvCode": "77310000-6",
      "cpvName": "Amenajare şi întreţinere de spaţii verzi",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100599370",
      "internalUrl": "/contracte/107126374",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100599370"
    },
    {
      "id": "da-122622082",
      "source": "da",
      "code": "DA40824995",
      "title": "Materiale de construcţii şi articole conexe",
      "titleKind": "cpv",
      "amount": 34058.9,
      "date": "2026-07-15",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2107447",
      "supplierName": "DENNVER COMIMPEX S.R.L.",
      "county": "Cluj",
      "cpvCode": "44100000-1",
      "cpvName": "Materiale de construcţii şi articole conexe",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122622082",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 78
    },
    {
      "id": "da-122622609",
      "source": "da",
      "code": "DA40826214",
      "title": "Servicii legislative",
      "titleKind": "cpv",
      "amount": 46750,
      "date": "2026-07-15",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2109355",
      "supplierName": "WOLTERS KLUWER ROMANIA S.R.L.",
      "county": "Cluj",
      "cpvCode": "75111200-9",
      "cpvName": "Servicii legislative",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122622609",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [
        "da_rapid"
      ],
      "gapMinutes": 5
    },
    {
      "id": "da-122620697",
      "source": "da",
      "code": "DA40823519",
      "title": "Servicii de consultanţă în domeniul securităţii",
      "titleKind": "cpv",
      "amount": 16500,
      "date": "2026-07-15",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2039860",
      "supplierName": "S.C. PROTCONSULT S.R.L.",
      "county": "Cluj",
      "cpvCode": "79417000-0",
      "cpvName": "Servicii de consultanţă în domeniul securităţii",
      "category": "Servicii",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122620697",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 106
    },
    {
      "id": "da-122614669",
      "source": "da",
      "code": "DA40817815",
      "title": "Hârtie şi carton asamblate",
      "titleKind": "cpv",
      "amount": 5722.5,
      "date": "2026-07-15",
      "authorityId": "2146445",
      "authorityName": "Municipiul Cluj-Napoca",
      "supplierId": "2123833",
      "supplierName": "MILANO PAPETARIE",
      "county": "Cluj",
      "cpvCode": "30197610-5",
      "cpvName": "Hârtie şi carton asamblate",
      "category": "IT și echipamente",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122614669",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 1335
    },
    {
      "id": "ct-404492",
      "source": "contract",
      "code": "16855/107",
      "title": "Contract subsecvent lucrari de intretinere LOT 4",
      "titleKind": "contract",
      "amount": 727109.7,
      "date": "2026-06-14",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2161956",
      "supplierName": "CLARO BUILD S.R.L.",
      "county": "Cluj",
      "cpvCode": "45233141-9",
      "cpvName": "Lucrări de întreţinere a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100636784",
      "internalUrl": "/contracte/107778729",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100636784"
    },
    {
      "id": "ct-404491",
      "source": "contract",
      "code": "20395/186",
      "title": "Contract subsecvent lucrari de intretinere LOT 2",
      "titleKind": "contract",
      "amount": 636526.84,
      "date": "2026-06-11",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2041492",
      "supplierName": "ZADILOC SRL",
      "county": "Cluj",
      "cpvCode": "45233141-9",
      "cpvName": "Lucrări de întreţinere a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100636784",
      "internalUrl": "/contracte/107780628",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100636784"
    },
    {
      "id": "ct-404490",
      "source": "contract",
      "code": "20400/187",
      "title": "Contract subsecvent lucrari de intretinere LOT 4",
      "titleKind": "contract",
      "amount": 186679.3,
      "date": "2026-06-11",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2161956",
      "supplierName": "CLARO BUILD S.R.L.",
      "county": "Cluj",
      "cpvCode": "45233141-9",
      "cpvName": "Lucrări de întreţinere a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100636784",
      "internalUrl": "/contracte/107767359",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100636784"
    },
    {
      "id": "ct-404489",
      "source": "contract",
      "code": "20355/178",
      "title": "Contract subsecvent lucrari de intretinere LOT 3",
      "titleKind": "contract",
      "amount": 55501.5,
      "date": "2026-06-11",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2110241",
      "supplierName": "ANTREPRIZA DE REPARATII SI LUCRARI A R L CLUJ",
      "county": "Cluj",
      "cpvCode": "45233141-9",
      "cpvName": "Lucrări de întreţinere a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100636784",
      "internalUrl": "/contracte/107754365",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100636784"
    },
    {
      "id": "ct-404488",
      "source": "contract",
      "code": "20385/175",
      "title": "Contract subsecvent lucrari de intretinere LOT 3",
      "titleKind": "contract",
      "amount": 227602.45,
      "date": "2026-06-11",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2110241",
      "supplierName": "ANTREPRIZA DE REPARATII SI LUCRARI A R L CLUJ",
      "county": "Cluj",
      "cpvCode": "45233141-9",
      "cpvName": "Lucrări de întreţinere a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100636784",
      "internalUrl": "/contracte/107754359",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100636784"
    },
    {
      "id": "ct-404400",
      "source": "contract",
      "code": "23154/169",
      "title": "Contract subsecvent lucrari de intretinere LOT 4",
      "titleKind": "contract",
      "amount": 86307449.76,
      "date": "2025-05-29",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2161956",
      "supplierName": "CLARO BUILD S.R.L.",
      "county": "Cluj",
      "cpvCode": "45233141-9",
      "cpvName": "Lucrări de întreţinere a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100636784",
      "internalUrl": "/contracte/107747762",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100636784"
    },
    {
      "id": "ct-769615",
      "source": "contract",
      "code": "19397/145",
      "title": "ACORD CONTRACTUAL Proiectarea și execuția Instalației de tratare prin dezintegrare moleculară pentru valorificarea energetică a deșeurilor municipale din județul Cluj, \ninclusiv operarea și mentenanța pe perioada de garanție",
      "titleKind": "contract",
      "amount": 60794052,
      "date": "2024-05-06",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2166705",
      "supplierName": "WASTE POWERTECH",
      "county": "Cluj",
      "cpvCode": "45222100-0",
      "cpvName": "Lucrări de construcţii de uzine de tratare a deşeurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100472815",
      "internalUrl": "/contracte/105220244",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100472815"
    },
    {
      "id": "ct-515973",
      "source": "contract",
      "code": "41184/363",
      "title": "MICROBUZE ELECTRICE PENTRU ELEVII DIN JUDETUL CLUJ",
      "titleKind": "contract",
      "amount": 28900000,
      "date": "2024-10-09",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "1969623",
      "supplierName": "AVEURO INTERNATIONAL SRL",
      "county": "Cluj",
      "cpvCode": "34144900-7",
      "cpvName": "Vehicule electrice",
      "category": "Transport",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100613668",
      "internalUrl": "/contracte/107354956",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100613668"
    },
    {
      "id": "da-122592969",
      "source": "da",
      "code": "DA40797689",
      "title": "Produse de curăţenie",
      "titleKind": "cpv",
      "amount": 19070,
      "date": "2026-07-10",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2078916",
      "supplierName": "S.C. HYGIENE PLUS S.R.L.",
      "county": "Cluj",
      "cpvCode": "39831240-0",
      "cpvName": "Produse de curăţenie",
      "category": "Dotări și mobilier",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122592969",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 967
    },
    {
      "id": "da-122567856",
      "source": "da",
      "code": "DA40774540",
      "title": "Lucrări de reparaţii generale şi de renovare",
      "titleKind": "cpv",
      "amount": 81740.55,
      "date": "2026-07-07",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2104649",
      "supplierName": "SC IMSAT SERVICE CLUJ SA",
      "county": "Cluj",
      "cpvCode": "45453000-7",
      "cpvName": "Lucrări de reparaţii generale şi de renovare",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122567856",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 66
    },
    {
      "id": "da-122553687",
      "source": "da",
      "code": "DA40761383",
      "title": "Servicii de urbanism",
      "titleKind": "cpv",
      "amount": 35000,
      "date": "2026-07-07",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2204317",
      "supplierName": "ROZUA ASOCIAŢI",
      "county": "Cluj",
      "cpvCode": "71410000-5",
      "cpvName": "Servicii de urbanism",
      "category": "Proiectare și consultanță",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122553687",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 1701
    },
    {
      "id": "da-122549311",
      "source": "da",
      "code": "DA40757263",
      "title": "Sisteme de navigare şi de poziţionare globală (GPS sau echivalente)",
      "titleKind": "cpv",
      "amount": 41900,
      "date": "2026-07-06",
      "authorityId": "2143172",
      "authorityName": "JUDETUL CLUJ (CONSILIUL JUDETEAN)",
      "supplierId": "2126287",
      "supplierName": "BLACK LIGHT S.R.L.",
      "county": "Cluj",
      "cpvCode": "38112100-4",
      "cpvName": "Sisteme de navigare şi de poziţionare globală (GPS sau echivalente)",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122549311",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 4132
    },
    {
      "id": "ct-362624",
      "source": "contract",
      "code": "22439",
      "title": "Acord cadru",
      "titleKind": "contract",
      "amount": 372000,
      "date": "2026-06-28",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2114185",
      "supplierName": "LUAN VISION",
      "county": "Cluj",
      "cpvCode": "33140000-3",
      "cpvName": "Consumabile medicale",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100641358",
      "internalUrl": "/contracte/107830903",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100641358"
    },
    {
      "id": "ct-362623",
      "source": "contract",
      "code": "22432",
      "title": "Acord cadru",
      "titleKind": "contract",
      "amount": 280000,
      "date": "2026-06-28",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2127838",
      "supplierName": "ALPHA MEDICAL",
      "county": "Cluj",
      "cpvCode": "33140000-3",
      "cpvName": "Consumabile medicale",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100641358",
      "internalUrl": "/contracte/107830902",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100641358"
    },
    {
      "id": "ct-362622",
      "source": "contract",
      "code": "22435",
      "title": "Acord cadru",
      "titleKind": "contract",
      "amount": 1500000,
      "date": "2026-06-28",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "1990121",
      "supplierName": "EXIMIA MEDICAL",
      "county": "Cluj",
      "cpvCode": "33140000-3",
      "cpvName": "Consumabile medicale",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100641358",
      "internalUrl": "/contracte/107830901",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100641358"
    },
    {
      "id": "ct-362621",
      "source": "contract",
      "code": "22440",
      "title": "Acord Cadru",
      "titleKind": "contract",
      "amount": 3573000,
      "date": "2026-06-28",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2113762",
      "supplierName": "REVISMED MEDICAL",
      "county": "Cluj",
      "cpvCode": "33140000-3",
      "cpvName": "Consumabile medicale",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100641358",
      "internalUrl": "/contracte/107830900",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100641358"
    },
    {
      "id": "ct-362620",
      "source": "contract",
      "code": "22437",
      "title": "Acord Cadru",
      "titleKind": "contract",
      "amount": 3589100,
      "date": "2026-06-28",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2127057",
      "supplierName": "FRESENIUS KABI ROMANIA",
      "county": "Cluj",
      "cpvCode": "33140000-3",
      "cpvName": "Consumabile medicale",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100641358",
      "internalUrl": "/contracte/107830899",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100641358"
    },
    {
      "id": "ct-613586",
      "source": "contract",
      "code": "25323",
      "title": "Acord Cadru Medicamente 165",
      "titleKind": "contract",
      "amount": 249546561.18,
      "date": "2025-07-13",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2161704",
      "supplierName": "DR.MAX",
      "county": "Cluj",
      "cpvCode": "33600000-6",
      "cpvName": "Produse farmaceutice",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100562711",
      "internalUrl": "/contracte/106597486",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100562711"
    },
    {
      "id": "ct-613588",
      "source": "contract",
      "code": "25325",
      "title": "Acord Cadru Medicamente 165",
      "titleKind": "contract",
      "amount": 89882958.75,
      "date": "2025-07-13",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2128622",
      "supplierName": "FARMEXIM S.A.",
      "county": "Cluj",
      "cpvCode": "33600000-6",
      "cpvName": "Produse farmaceutice",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100562711",
      "internalUrl": "/contracte/106597491",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100562711"
    },
    {
      "id": "ct-794363",
      "source": "contract",
      "code": "13500/68",
      "title": "Eculizumabum",
      "titleKind": "contract",
      "amount": 50113480,
      "date": "2024-03-24",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2128212",
      "supplierName": "ALLIANCE HEALTHCARE ROMANIA",
      "county": "Cluj",
      "cpvCode": "33600000-6",
      "cpvName": "Produse farmaceutice",
      "category": "Sănătate",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100453979",
      "internalUrl": "/contracte/104972011",
      "singleBidder": false,
      "tendersReceived": 3,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100453979"
    },
    {
      "id": "da-122628654",
      "source": "da",
      "code": "DA40830807",
      "title": "Acumulatori electrici",
      "titleKind": "cpv",
      "amount": 288,
      "date": "2026-07-15",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2110165",
      "supplierName": "MICROELECTRONICA",
      "county": "Cluj",
      "cpvCode": "31430000-9",
      "cpvName": "Acumulatori electrici",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122628654",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [
        "da_rapid"
      ],
      "gapMinutes": 9
    },
    {
      "id": "da-122628679",
      "source": "da",
      "code": "DA40830822",
      "title": "Acumulatori electrici",
      "titleKind": "cpv",
      "amount": 498,
      "date": "2026-07-15",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2110165",
      "supplierName": "MICROELECTRONICA",
      "county": "Cluj",
      "cpvCode": "31430000-9",
      "cpvName": "Acumulatori electrici",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122628679",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [
        "da_rapid"
      ],
      "gapMinutes": 8
    },
    {
      "id": "da-122627558",
      "source": "da",
      "code": "DA40829766",
      "title": "Cabluri de conectare",
      "titleKind": "cpv",
      "amount": 1497,
      "date": "2026-07-15",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2127571",
      "supplierName": "DRAGER MEDICAL ROMANIA",
      "county": "Cluj",
      "cpvCode": "31224400-6",
      "cpvName": "Cabluri de conectare",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122627558",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [
        "da_split"
      ],
      "gapMinutes": 60
    },
    {
      "id": "da-122627797",
      "source": "da",
      "code": "DA40829990",
      "title": "Garnituri",
      "titleKind": "cpv",
      "amount": 1308.01,
      "date": "2026-07-15",
      "authorityId": "2084803",
      "authorityName": "Spitalul Clinic Judetean de Urgenta Cluj-Napoca",
      "supplierId": "2128437",
      "supplierName": "RAFI INTERNATIONAL GENERAL COMMERCE",
      "county": "Cluj",
      "cpvCode": "44523300-5",
      "cpvName": "Garnituri",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122627797",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [
        "da_rapid"
      ],
      "gapMinutes": 2
    },
    {
      "id": "ct-362076",
      "source": "contract",
      "code": "77",
      "title": "Contract subsecvent de lucrari nr. 2 avand ca obiect – Lucrari de intretinere curenta - parte carosabila, acostamente, benzi de urgenta si benzi de incadrare anul I – II - SDN Orsova",
      "titleKind": "contract",
      "amount": 1235400,
      "date": "2026-07-08",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2073287",
      "supplierName": "ROUTE CENTER CONSTRUCT",
      "county": "Bucuresti",
      "cpvCode": "45233139-3",
      "cpvName": "Lucrări de întreţinere a drumurilor naţionale",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100641817",
      "internalUrl": "/contracte/107837976",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100641817"
    },
    {
      "id": "ct-374801",
      "source": "contract",
      "code": "24/4043/2",
      "title": "CONTRACT SUBSECVENT NR: 2 -MIXTURA ASFALTICA TIP BA16 cu transport inclus pentru DRDP CLUJ – Acord Cadru – 24 luni",
      "titleKind": "contract",
      "amount": 711654,
      "date": "2026-07-06",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2110059",
      "supplierName": "VIAROM CONSTRUCT",
      "county": "Bucuresti",
      "cpvCode": "44113620-7",
      "cpvName": "Asfalt",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100640654",
      "internalUrl": "/contracte/107819348",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100640654"
    },
    {
      "id": "ct-376688",
      "source": "contract",
      "code": "24/2007/4",
      "title": "CONTRACT SUBSECVENT NR : 3 - Lucrări și servicii privind întreținerea periodică a drumurilor publice – Covoare bituminoase BA 16 cu frezare 4 cm – An I – An IV pe autostrăzile și drumurile naționale din administrarea D.R.D.P. Cluj, Acord - cadru 4 ani pe SDN Baia Mare\" pe DN 18 km 90+816 – km 96+053",
      "titleKind": "contract",
      "amount": 1973400,
      "date": "2026-07-05",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2075122",
      "supplierName": "OPENTRANS",
      "county": "Bucuresti",
      "cpvCode": "45233139-3",
      "cpvName": "Lucrări de întreţinere a drumurilor naţionale",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100640649",
      "internalUrl": "/contracte/107819123",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100640649"
    },
    {
      "id": "ct-379643",
      "source": "contract",
      "code": "1119",
      "title": "Servicii de proiectare fazele P.A.C + P.T.E. + A.T. și Execuție lucrări pentru “Consolidarea părții carosabile DN 10 km 76+768 -:- 76+944 dreapta (UAT Siriu)”",
      "titleKind": "contract",
      "amount": 10699732.5,
      "date": "2026-07-01",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2100176",
      "supplierName": "MEGA EDIL",
      "county": "Bucuresti",
      "cpvCode": "45233000-9",
      "cpvName": "Lucrări de construcţii, de fundaţie şi de îmbrăcare a autostrăzilor şi a drumurilor",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100640620",
      "internalUrl": "/contracte/107818995",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Negociere fara publicare prealabila",
      "flags": [],
      "noticeId": "100640620"
    },
    {
      "id": "ct-379642",
      "source": "contract",
      "code": "159",
      "title": "Acord Cadru Lucrări de întreținere curentă pe timp de vară - Estetică rutieră și scurgerea apelor anul  I-IV - D.R.D.P. Brașov - A3 Tg. Mureș - Iernut - Câmpia Turzii",
      "titleKind": "contract",
      "amount": 13755971,
      "date": "2026-06-30",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2059613",
      "supplierName": "SC. CONSTRUCTII GENERALE OLTENIA .SRL",
      "county": "Bucuresti",
      "cpvCode": "45233139-3",
      "cpvName": "Lucrări de întreţinere a drumurilor naţionale",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100640766",
      "internalUrl": "/contracte/107821755",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100640766"
    },
    {
      "id": "ct-560648",
      "source": "contract",
      "code": "92129585",
      "title": "Executie Lucrari “Drum Expres Conexiune Satu Mare (VO Satu Mare) - Oar (Granita Romano - Ungara - Drum Expres M49 Ungaria)”",
      "titleKind": "contract",
      "amount": 720487744.04,
      "date": "2025-10-30",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2124463",
      "supplierName": "CONSTRUCTII ERBASU S.A.",
      "county": "Bucuresti",
      "cpvCode": "45233100-0",
      "cpvName": "Lucrări de construcţii de autostrăzi şi de drumuri",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100594560",
      "internalUrl": "/contracte/107060894",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100594560"
    },
    {
      "id": "ct-748100",
      "source": "contract",
      "code": "217",
      "title": "Executie lucrari la obiectivul „Modernizare DN 73 km 13+800 - km 42+850, km 54+050 - km 128+250 Pitesti-Campulung-Brasov” - sector km 54+050-km 128+250, LOT 1 km 54+050 – km 92+000",
      "titleKind": "contract",
      "amount": 426213446.79,
      "date": "2024-08-05",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2110241",
      "supplierName": "ANTREPRIZA DE REPARATII SI LUCRARI A R L CLUJ",
      "county": "Bucuresti",
      "cpvCode": "45233130-9",
      "cpvName": "Lucrări de construcţii de drumuri naţionale",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100486967",
      "internalUrl": "/contracte/105395312",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100486967"
    },
    {
      "id": "ct-717841",
      "source": "contract",
      "code": "92/110496",
      "title": "Proiectare si executie „Varianta de ocolire Buftea”",
      "titleKind": "contract",
      "amount": 281172365.65,
      "date": "2024-11-04",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2108050",
      "supplierName": "PORR CONSTRUCT",
      "county": "Bucuresti",
      "cpvCode": "45233130-9",
      "cpvName": "Lucrări de construcţii de drumuri naţionale",
      "category": "Drumuri și construcții",
      "sourceUrl": "https://e-licitatie.ro/pub/notices/ca-notices/view-c/100507370",
      "internalUrl": "/contracte/105648205",
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Licitatie deschisa",
      "flags": [],
      "noticeId": "100507370"
    },
    {
      "id": "da-122597638",
      "source": "da",
      "code": "DA40802934",
      "title": "Piatră de carieră şi concasată",
      "titleKind": "cpv",
      "amount": 165330,
      "date": "2026-07-15",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2128399",
      "supplierName": "MIS GRUP",
      "county": "Bucuresti",
      "cpvCode": "14212300-3",
      "cpvName": "Piatră de carieră şi concasată",
      "category": "Alte achiziții",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122597638",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 7240
    },
    {
      "id": "da-122596202",
      "source": "da",
      "code": "DA40800944",
      "title": "Servicii de expertiză",
      "titleKind": "cpv",
      "amount": 30000,
      "date": "2026-07-15",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2219046",
      "supplierName": "VEXILLUM",
      "county": "Bucuresti",
      "cpvCode": "71319000-7",
      "cpvName": "Servicii de expertiză",
      "category": "Proiectare și consultanță",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122596202",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 7343
    },
    {
      "id": "da-122613361",
      "source": "da",
      "code": "DA40816615",
      "title": "Servicii de proiectare tehnică pentru construcţia de lucrări publice",
      "titleKind": "cpv",
      "amount": 136491.5,
      "date": "2026-07-15",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2071779",
      "supplierName": "Greco Proiect Solutions",
      "county": "Bucuresti",
      "cpvCode": "71322000-1",
      "cpvName": "Servicii de proiectare tehnică pentru construcţia de lucrări publice",
      "category": "Proiectare și consultanță",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122613361",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 1315
    },
    {
      "id": "da-122586590",
      "source": "da",
      "code": "DA40791782",
      "title": "Containere şi pubele de deşeuri",
      "titleKind": "cpv",
      "amount": 126.84,
      "date": "2026-07-13",
      "authorityId": "2146146",
      "authorityName": "COMPANIA NATIONALA DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
      "supplierId": "2094557",
      "supplierName": "ARLI CO SRL",
      "county": "Bucuresti",
      "cpvCode": "34928480-6",
      "cpvName": "Containere şi pubele de deşeuri",
      "category": "Transport",
      "sourceUrl": "https://e-licitatie.ro/pub/direct-acquisition/view/122586590",
      "internalUrl": null,
      "singleBidder": null,
      "tendersReceived": null,
      "procedure": "Achiziție directă",
      "flags": [],
      "gapMinutes": 5969
    }
  ],
  "years": [
    "2026",
    "2025",
    "2024"
  ],
  "nationalYearly": [
    {
      "kind": "award",
      "year": 2018,
      "n": 19428,
      "totalRon": 20338340026.03
    },
    {
      "kind": "da",
      "year": 2018,
      "n": 2019867,
      "totalRon": 8435048673.89
    },
    {
      "kind": "award",
      "year": 2019,
      "n": 34227,
      "totalRon": 39315038091.68
    },
    {
      "kind": "da",
      "year": 2019,
      "n": 2464554,
      "totalRon": 11075458615.31
    },
    {
      "kind": "award",
      "year": 2020,
      "n": 35662,
      "totalRon": 40331129714.02
    },
    {
      "kind": "da",
      "year": 2020,
      "n": 2222824,
      "totalRon": 11695364479.92
    },
    {
      "kind": "award",
      "year": 2021,
      "n": 36955,
      "totalRon": 47210534753.15
    },
    {
      "kind": "da",
      "year": 2021,
      "n": 2372588,
      "totalRon": 12572986804.76
    },
    {
      "kind": "award",
      "year": 2022,
      "n": 43132,
      "totalRon": 62312926006.53
    },
    {
      "kind": "da",
      "year": 2022,
      "n": 2453203,
      "totalRon": 15846068336.09
    },
    {
      "kind": "award",
      "year": 2023,
      "n": 40354,
      "totalRon": 104171114148.16
    },
    {
      "kind": "da",
      "year": 2023,
      "n": 2314179,
      "totalRon": 17883069150.32
    },
    {
      "kind": "award",
      "year": 2024,
      "n": 40865,
      "totalRon": 111448461604.27
    },
    {
      "kind": "da",
      "year": 2024,
      "n": 2347744,
      "totalRon": 20535108202.79
    },
    {
      "kind": "award",
      "year": 2025,
      "n": 37449,
      "totalRon": 136315640675.4
    },
    {
      "kind": "da",
      "year": 2025,
      "n": 2232963,
      "totalRon": 18814572161.17
    },
    {
      "kind": "award",
      "year": 2026,
      "n": 24452,
      "totalRon": 136442274300.14
    },
    {
      "kind": "da",
      "year": 2026,
      "n": 1154292,
      "totalRon": 9615471931.15
    }
  ]
};
