'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import DiscoveryIcon from '@/app/DiscoveryIcon';
import {stageLabel,foldText,type ContractFiles as Files,type ContractFile,type DocumentPage} from '@/lib/documents/shared';
import './documents.css';
import PdfPage from './PdfPage';
const api=(id:string)=>`/api/documents/${id}`;
async function json(url:string,options?:RequestInit){const r=await fetch(url,options);const body=await r.json();if(!r.ok)throw new Error(body.error??'Nu am putut citi datele. Încearcă din nou.');return body;}
const date=(v:string)=>new Date(v).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'});
function Highlight({text,query}:{text:string;query:string}){
 if(!query.trim())return <>{text}</>;
 const start=foldText(text).indexOf(foldText(query.trim()));if(start<0)return <>{text}</>;
 return <>{text.slice(0,start)}<mark>{text.slice(start,start+query.trim().length)}</mark>{text.slice(start+query.trim().length)}</>;
}
function snippet(text:string,query:string){const i=foldText(text).indexOf(foldText(query));const start=Math.max(0,i-100);return (start?'…':'')+text.slice(start,start+350)+(text.length>start+350?'…':'');}
export default function ContractFiles({nid,initial,authenticated}:{nid:string;initial:Files;authenticated:boolean}){
 const [data,setData]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
 const [selected,setSelected]=useState<ContractFile|null>(null),[page,setPage]=useState(1),[text,setText]=useState<DocumentPage|null>(null),[reading,setReading]=useState(false),[readerError,setReaderError]=useState('');
 const [query,setQuery]=useState(''),[scope,setScope]=useState('all'),[searched,setSearched]=useState(''),[searching,setSearching]=useState(false),[hits,setHits]=useState<{id:string;filename:string;page:number;text:string;method:string}[]|null>(null),[truncated,setTruncated]=useState(false);
 const [readerHighlight,setReaderHighlight]=useState(''),[documentApplied,setDocumentApplied]=useState('');
 const [documentQuery,setDocumentQuery]=useState(''),[documentHits,setDocumentHits]=useState<{page:number;text:string}[]|null>(null),[documentSearching,setDocumentSearching]=useState(false);
 const [quote,setQuote]=useState('');const ocr=useRef<HTMLDivElement>(null),reader=useRef<HTMLElement>(null);
 const running=[data.job,...data.files.map(f=>f.job)].some(j=>j&&['queued','running'].includes(j.status));
 const ready=data.files.filter(f=>f.processedAt),total=data.total??data.files.length;
 const load=async()=>{const d=await json(`/api/contracte/${nid}/files`);setData(d);return d as Files;};
 // A tab with no active job must still discover work started elsewhere.
 useEffect(()=>{let alive=true,pending=false;const controller=new AbortController();
  const refresh=async()=>{if(pending||document.visibilityState==='hidden')return;pending=true;try{const d=await json(`/api/contracte/${nid}/files`,{signal:controller.signal,cache:'no-store'});if(alive){setData(d);setError('');}}catch(e){if(alive)setError((e as Error).message);}finally{pending=false;}};
  void refresh();const timer=setInterval(()=>void refresh(),running?2500:15000);
  const resume=()=>void refresh();window.addEventListener('focus',resume);document.addEventListener('visibilitychange',resume);
  return()=>{alive=false;controller.abort();clearInterval(timer);window.removeEventListener('focus',resume);document.removeEventListener('visibilitychange',resume);};
 },[running,nid]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),id=params.get('document'),p=Number(params.get('page')??1);const f=initial.files.find(f=>f.id===id&&f.pdfHash);if(f){setSelected(f);setPage(Number.isInteger(p)&&p>0&&p<=(f.pageCount??1)?p:1);setTimeout(()=>reader.current?.scrollIntoView({block:'start'}),100);}},[initial.files]);
 useEffect(()=>{if(!selected)return;let alive=true;const controller=new AbortController();setReading(true);setText(null);setQuote('');setReaderError('');
  void json(`${api(selected.id)}?page=${page}`,{signal:controller.signal}).then(d=>{if(alive)setText(d.page);}).catch(e=>{if(alive)setReaderError(e.message);}).finally(()=>{if(alive)setReading(false);});
  const url=new URL(window.location.href);url.searchParams.set('document',selected.id);url.searchParams.set('page',String(page));window.history.replaceState(null,'',url);
  return()=>{alive=false;controller.abort();};
 },[selected?.id,page]);
 async function enqueue(id:string|null){setBusy(id??'list');setError('');try{await json(`/api/contracte/${nid}/files`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:id})});await load();}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
 function open(f:ContractFile,p=1,highlight=''){setReaderHighlight(highlight);if(f.id!==selected?.id){setDocumentHits(null);setDocumentQuery('');}setSelected(f);setPage(p);setQuote('');setTimeout(()=>{reader.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});reader.current?.focus({preventScroll:true});},0);}
 async function search(e:React.FormEvent){e.preventDefault();setSearching(true);setError('');try{const result=await json(`/api/contracte/${nid}/files/search?q=${encodeURIComponent(query.trim())}${scope==='all'?'':`&documentId=${scope}`}`);setHits(result.hits);setSearched(query.trim());setTruncated(result.truncated);}catch(e){setError((e as Error).message);}finally{setSearching(false);}}
 async function searchDocument(e:React.FormEvent){e.preventDefault();if(!selected)return;setDocumentSearching(true);setReaderError('');try{const r=await json(`/api/contracte/${nid}/files/search?q=${encodeURIComponent(documentQuery.trim())}&documentId=${selected.id}`);setDocumentHits(r.hits);setDocumentApplied(documentQuery.trim());setReaderHighlight(documentQuery.trim());}catch(e){setReaderError((e as Error).message);}finally{setDocumentSearching(false);}}
 function captureSelection(){const selection=window.getSelection();if(selection&&ocr.current?.contains(selection.anchorNode)&&ocr.current?.contains(selection.focusNode)){const value=selection.toString();setQuote(value.length>=3&&value.length<=8000?value:'');}}
 const login=<Link className="df-button" href={`/login?next=${encodeURIComponent(`/contracte/${nid}#fisiere`)}`}>Autentifică-te pentru a pregăti fișiere</Link>;
 return <section className="df-section" id="fisiere" aria-labelledby="files-heading">
  <div className="df-heading"><div><h2 id="files-heading">Fișierele procedurii</h2><p>Citește sursa. Caută o cerință. Păstrează pasajul care contează.</p></div>{data.notice&&<a href={data.notice.url} target="_blank" rel="noopener noreferrer">Anunțul în SEAP ↗</a>}</div>
  {!data.notice?<p className="df-empty">Nu avem încă o legătură verificată cu un anunț compatibil pentru preluarea fișierelor. Poți consulta sursa oficială a contractului de mai sus.</p>:<>
   <p className="df-muted">Documentele aparțin procedurii {data.notice.noticeNo}; pot privi mai multe contracte sau loturi.</p>
   <div className="df-queue" role="status"><span>{running?'Un singur fișier se descarcă și se procesează la un moment dat. Poți părăsi pagina; coada este păstrată.':data.checkedAt?`Lista verificată la ${date(data.checkedAt)}.`:data.files.length?`Avem metadate pentru ${data.files.length} din ${total} fișiere. Verifică lista completă, fără a descărca documentele.`:'Lista de fișiere nu a fost încă preluată. Verificarea listei nu descarcă documentele.'}</span><small>{data.requestCount} cereri SEAP înregistrate în această coadă</small></div>
   {!data.enabled&&<p className="df-muted">Preluarea este momentan oprită pe acest server. Documentele deja pregătite pot fi citite și căutate.</p>}
   {data.job&&data.job.status!=='complete'&&<p role="status">{data.job.status==='failed'?data.job.error:stageLabel[data.job.stage]}{data.job.status==='queued'?` · poziția ${data.job.position}`:''}</p>}
   {data.enabled&&(!data.checkedAt||!running)&&<div className="df-list-action">{authenticated?<button className="df-button" disabled={busy!==null||!!data.job&&['queued','running'].includes(data.job.status)||!!data.checkedAt&&Date.now()-Date.parse(data.checkedAt)<86400000} onClick={()=>void enqueue(null)}>{busy==='list'?'Se trimite…':!data.checkedAt?'Vezi fișierele disponibile':'Actualizează lista'}</button>:!data.checkedAt?login:null}{data.checkedAt&&<small>Lista se poate actualiza o dată la 24 de ore.</small>}</div>}
   {data.checkedAt&&data.files.length===0&&<p className="df-empty">La ultima verificare, SEAP nu a returnat fișiere pentru acest anunț.</p>}
   <div className="df-list">{data.files.map(f=>{const j=f.job,active=j&&['queued','running'].includes(j.status);return <article className={`df-file${f.originalHash?' df-file-downloaded':''}`} key={f.id}>
    <span className="df-format" aria-hidden="true">{f.filename.toLowerCase().endsWith('.p7s')?'P7S':'PDF'}</span>
    <div className="df-file-body"><h3>{f.pdfHash?<button className="df-title" onClick={()=>open(f)}>{f.filename}</button>:f.filename}</h3>
     <p className="df-status">{f.originalHash&&<><span className="df-downloaded"><DiscoveryIcon name="checkCircle" className="df-icon"/>Descărcat</span>{' · '}</>}{f.processedAt?`${f.pageCount} pagini · text căutabil`:active?`${stageLabel[j.stage]??j.stage}${j.status==='queued'?` · poziția ${j.position}`:''}`:j?.status==='failed'?j.error:f.originalHash?'Text încă nepregătit':'Disponibil în SEAP · încă nedescărcat'}</p>
     {j?.status==='running'&&<div className="df-progress"><progress aria-label={stageLabel[j.stage]} {...(j.pagesTotal?{value:j.pagesDone,max:j.pagesTotal}:{})}/>{j.pagesTotal&&<small>{j.pagesDone} din {j.pagesTotal} pagini citite</small>}</div>}
     <details className="df-provenance"><summary>Proveniență și original</summary><dl><dt>Cod SEAP</dt><dd>{f.code}</dd>{f.publishedAt&&<><dt>Publicat</dt><dd>{date(f.publishedAt)}</dd></>}{f.downloadedAt&&<><dt>Original păstrat</dt><dd>{date(f.downloadedAt)}</dd><dt>Amprentă SHA-256</dt><dd className="df-hash">{f.originalHash}</dd></>}{f.signature&&<><dt>Semnătură</dt><dd>{f.signature}</dd></>}</dl>{f.originalHash&&<a href={`${api(f.id)}/file`}>Descarcă originalul{f.filename.endsWith('.p7s')?' semnat (.p7s)':''}</a>}</details>
    </div>
    <div className="df-file-action">{f.pdfHash?<button className="df-button df-primary" onClick={()=>open(f)}><DiscoveryIcon name="bookOpen" className="df-icon"/><span>Deschide documentul</span></button>:active?<span className="df-muted">{j.status==='queued'?'În coadă':'În lucru'}</span>:data.enabled?(authenticated?<button className={`df-button${f.originalHash?' df-resume':''}`} disabled={busy!==null} onClick={()=>void enqueue(f.id)}><DiscoveryIcon name={f.originalHash?'retry':'download'} className="df-icon"/><span>{busy===f.id?'Se trimite…':f.originalHash?'Reia procesarea':j?.status==='failed'?'Reîncearcă descărcarea':'Descarcă și procesează'}</span></button>:login):null}{f.originalHash&&<a className="df-original-link" href={`${api(f.id)}/file`}><DiscoveryIcon name="download" className="df-icon"/>Descarcă originalul</a>}</div>
   </article>;})}</div>
   {data.files.length>0&&<div className="df-search"><h3>Caută în fișierele contractului</h3><p className="df-muted">{ready.length?`Cauți în ${ready.length} din ${total} fișiere. Documentele fără text pregătit nu intră în rezultate.`:'Pregătește primul document pentru a putea căuta în conținutul lui.'}</p>
    <form onSubmit={e=>void search(e)}><label className="df-query">Cuvânt sau expresie<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="De exemplu: garanție, subcontractare…" minLength={2} maxLength={150} required disabled={!ready.length}/></label><label>Unde cauți<select value={scope} onChange={e=>{setScope(e.target.value);setHits(null);}} disabled={!ready.length}><option value="all">Toate fișierele pregătite</option>{ready.map(f=><option key={f.id} value={f.id}>{f.filename}</option>)}</select></label><button className="df-button df-primary" disabled={searching||!ready.length}>{searching?'Se caută…':'Caută'}</button></form>
    <div className="df-results" aria-live="polite" aria-busy={searching}>{hits&&<><p>{hits.length?`${hits.length}${truncated?'+':''} pagini cu „${searched}”`:`Nu am găsit „${searched}” în documentele căutabile.`}</p>{hits.map(h=><button key={`${h.id}:${h.page}`} className="df-hit" onClick={()=>{const f=data.files.find(f=>f.id===h.id);if(f)open(f,h.page,searched);}}><strong>{h.filename} · pagina {h.page}</strong><span><Highlight text={snippet(h.text,searched)} query={searched}/></span><small>Deschide pagina în context →</small></button>)}{truncated&&<p>Se afișează primele 100 de pagini găsite. Restrânge expresia sau alege un document.</p>}</>}</div>
   </div>}
  </>}
  {error&&<p className="df-error" role="alert">{error}</p>}
  {selected&&<section className="df-reader" ref={reader} tabIndex={-1} aria-labelledby="reader-heading"><div className="df-heading"><div><h3 id="reader-heading">{selected.filename}</h3><p>Originalul și textul extras, pagină cu pagină.</p></div><button className="df-button" onClick={()=>{setSelected(null);const u=new URL(window.location.href);u.searchParams.delete('document');u.searchParams.delete('page');window.history.replaceState(null,'',u);document.getElementById('files-heading')?.scrollIntoView();}}>Închide documentul</button></div>
   <div className="df-reader-toolbar"><button className="df-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Înapoi</button><label>Pagina<select value={page} onChange={e=>setPage(Number(e.target.value))}>{Array.from({length:selected.pageCount??1},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><span>din {selected.pageCount}</span><button className="df-button" disabled={page>=(selected.pageCount??1)} onClick={()=>setPage(p=>p+1)}>Înainte →</button><a href={`${api(selected.id)}/file?kind=pdf#page=${page}`} target="_blank" rel="noopener noreferrer">PDF în alt tab ↗</a><a href={`${api(selected.id)}/file`}>Originalul ↓</a></div>
   <form className="df-document-search" onSubmit={e=>void searchDocument(e)}><label>Caută în acest document<input type="search" minLength={2} maxLength={150} required value={documentQuery} onChange={e=>setDocumentQuery(e.target.value)} placeholder="Cuvânt sau expresie"/></label><button className="df-button" disabled={documentSearching}>{documentSearching?'Se caută…':'Găsește paginile'}</button></form>
   {documentHits&&<div className="df-page-matches" aria-live="polite">{documentHits.length?<>Pagini cu „{documentApplied}”: {documentHits.map(h=><button key={h.page} className="df-button" aria-current={h.page===page?'page':undefined} onClick={()=>{setPage(h.page);setReaderHighlight(documentApplied);}}>{h.page}</button>)}</>:<>Nu am găsit expresia în textul acestui document.</>}</div>}
   <div className="df-reader-body"><PdfPage key={selected.id} url={`${api(selected.id)}/file?kind=pdf`} page={page} filename={selected.filename}/><div className="df-transcript"><h4>Textul paginii {page}</h4><p className="df-muted">{text?.method==='ocr'?'Text recunoscut automat (OCR). Verifică pasajul în original înainte de a-l cita.':'Text extras din PDF. Verifică formatarea și contextul în original.'}</p><p className="df-muted">Selectează un pasaj pentru a-l păstra într-o anchetă.</p><div className="df-page-text" ref={ocr} onMouseUp={captureSelection} onKeyUp={captureSelection} onTouchEnd={()=>setTimeout(captureSelection,100)} tabIndex={0} aria-busy={reading}>{reading?'Se încarcă textul paginii…':readerError?<p role="alert">{readerError}</p>:text?.text?<Highlight text={text.text} query={readerHighlight}/>:<p>Nu s-a extras text din această pagină. Verifică imaginea originală; pagina poate fi goală sau greu de citit.</p>}</div>
    {!quote&&text?.text&&text.text.length<=8000&&!reading&&<button className="df-button" onClick={()=>setQuote(text.text)}>Păstrează textul acestei pagini</button>}
    {quote&&<QuoteSaver key={`${selected.id}:${page}:${quote}`} document={selected} nid={nid} page={page} quote={quote} authenticated={authenticated}/>}</div></div>
  </section>}
 </section>;
}
function QuoteSaver({document:doc,nid,page,quote,authenticated}:{document:ContractFile;nid:string;page:number;quote:string;authenticated:boolean}){
 const [list,setList]=useState<{id:string;title:string}[]|null>(null),[id,setId]=useState(''),[title,setTitle]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<{id:string;investigationId:string}|null>(null);
 useEffect(()=>{if(!authenticated)return;let alive=true;void json('/api/anchete').then(d=>{if(!alive)return;const available=d.investigations.filter((i:{access?:{canEdit?:boolean}})=>i.access?.canEdit!==false);setList(available);setId(available[0]?.id??'new');}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[authenticated]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let destination=id;if(id==='new'){const inv=await json('/api/anchete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title})});destination=inv.id;setId(destination);setList(items=>[...(items??[]),{id:destination,title}]);}setSaved(await json(`${api(doc.id)}/quote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({investigationId:destination,contractId:nid,page,quote,note,originalHash:doc.originalHash})}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="df-quote"><h4>Păstrează pasajul</h4><blockquote>{quote}</blockquote>{saved?<p role="status">Pasaj salvat, cu pagina și originalul. <Link href={`/anchete/${saved.investigationId}?sectiune=evidence#clip-${saved.id}`}>Deschide ancheta →</Link></p>:!authenticated?<Link href={`/login?next=${encodeURIComponent(`/contracte/${nid}?document=${doc.id}&page=${page}`)}`}>Autentifică-te pentru a păstra pasajul</Link>:<form onSubmit={e=>void save(e)}><label>Ancheta<select value={id} onChange={e=>setId(e.target.value)} disabled={!list||busy}>{!list&&<option>Se încarcă anchetele…</option>}{list?.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}<option value="new">Creează o anchetă nouă</option></select></label>{id==='new'&&<label>Titlul anchetei<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={200}/></label>}<label>Observația ta (opțional)<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} maxLength={4000} placeholder="Ce merită verificat în acest pasaj?"/></label><button className="df-button df-primary" disabled={busy||!list}>{busy?'Se salvează…':'Salvează pasajul în anchetă'}</button></form>}{error&&<p role="alert" className="df-error">{error}</p>}</div>;
}
