import { data } from './data.js';

const APP = 'http://localhost:3000';
const variant = document.body.dataset.variant;
const root = document.querySelector('#app');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n = (value, decimals = 0) => Number(value).toLocaleString('ro-RO', {minimumFractionDigits:decimals, maximumFractionDigits:decimals});
const money = value => `${n(value, 2)} lei`;
const shortMoney = value => Number(value)>=1e9?`${n(Number(value)/1e9,2)} mld.`:Number(value)>=1e6?`${n(Number(value)/1e6,1)} mil.`:Number(value)>=1000?`${n(Number(value)/1000,Number(value)%1000?1:0)} mii`:`${n(value)} lei`;
const pct = value => `${n(value*100,1)}%`;
const date = value => String(value).slice(0,10).split('-').reverse().join('.');
const clean = value => String(value).replace(/\s+S\.?R\.?L\.?$/i,'').trim();
const fold = value => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const paths = {arrow:'M4 9h10m-4-4 4 4-4 4',external:'M10 3h5v5m0-5L7 11M7 3H3v12h12v-4',close:'m4 4 10 10M14 4 4 14',search:'M12 12l4 4M8 2a6 6 0 1 0 0 12A6 6 0 0 0 8 2',moon:'M14 11A6 6 0 0 1 7 4 6 6 0 1 0 14 11',file:'M5 2h6l4 4v10H3V2h2m6 0v5h4M6 10h6M6 13h4',clock:'M9 2a7 7 0 1 0 0 14A7 7 0 0 0 9 2m0 3v4l3 2',info:'M9 2a7 7 0 1 0 0 14A7 7 0 0 0 9 2m0 6v5m0-8v1',chevron:'m6 4 5 5-5 5'};
const icon = name => `<svg class="icon" viewBox="0 0 18 18" aria-hidden="true"><path d="${paths[name]||paths.arrow}"/></svg>`;
const appLink = (path,label,classes='source-link') => `<a class="${classes}" href="${APP}${path}" target="_blank" rel="noopener noreferrer">${label} ${icon('external')}</a>`;
const valuro = data.slices.find(s=>s.supplierId==='2058488');
const middle = data.slices.find(s=>s.supplierId==='2024523');
const esta = data.dep.find(s=>s.id==='1968012');
const oyl = data.patterns.find(p=>p.id===2719);
const state = {aType:'all',showAll:false,tab:'suppliers',query:'',limit:12,selected:'2066692',class:'4523',period:'2022-2024',matrixPage:1,matrixSelection:null,slice:valuro.supplierId,fullHistory:false,zoom:{k:1,x:0,y:0}};
try {document.documentElement.dataset.theme=localStorage.getItem('rx-mock-theme')||'light';}catch{}

function shell(){
 root.innerHTML=`<div class="mockbar"><span><strong>Varianta ${variant.toUpperCase()}</strong> · ${variant==='a'?'Piste de verificat':'Explorare vizuală'}<span class="mock-extra"> · mockup CNAIR, pe date locale</span></span><a href="../${variant==='a'?'b':'a'}/">Deschide varianta ${variant==='a'?'B':'A'} ${icon('external')}</a></div>
 <header class="site-header"><div class="header-inner"><a class="brand" href="${APP}" target="_blank" rel="noopener">cinecâștigă<span>?</span></a><nav aria-label="Navigare principală"><a href="${APP}" target="_blank" rel="noopener">Descoperă</a><a class="active" href="${APP}/entitati/2146146" target="_blank" rel="noopener">Explorează</a><a href="${APP}/anchete" target="_blank" rel="noopener">Anchete</a></nav><button class="icon-button" data-action="theme" aria-label="Schimbă tema">${icon('moon')}</button></div></header>
 <main class="shell" id="main"><nav class="breadcrumb" aria-label="Locul în aplicație">${appLink('/entitati/2146146','CNAIR','')}${icon('chevron')}<span>Radiografie</span></nav><div class="page-heading ${variant==='b'?'b-heading':''}"><div><h1>Radiografie CNAIR</h1><p>${variant==='a'?'O pistă bună începe cu date pe care le poți verifica.':'Explorează relațiile. Urmărește datele până la sursă.'}</p><p class="authority-name">Compania Națională de Administrare a Infrastructurii Rutiere</p></div>${appLink('/entitati/2146146','Profilul instituției','button')}</div>
 <div class="context-line"><span><strong>53,01 mld. lei</strong> valoare contractată</span><span><strong>10.513</strong> contracte distincte</span><span><strong>3.679</strong> achiziții directe</span><span>${icon('clock')} Istoric <strong>2016–2026</strong></span></div><div id="content"></div>
 <footer class="footer"><p>Date din copia locală din 28.09.2026. Aceste tipare sunt puncte de plecare pentru verificare, nu dovezi de încălcare a legii. Valorile contractate nu reprezintă plăți.</p><a href="${APP}/metodologie" target="_blank" rel="noopener">Metodologie și limite ${icon('external')}</a></footer></main>
 <dialog class="source-drawer" id="sources" aria-labelledby="drawer-title"><div class="drawer-head"><div><h2 id="drawer-title"></h2><p id="drawer-subtitle"></p></div><button class="icon-button" data-action="close" aria-label="Închide sursele">${icon('close')}</button></div><div class="drawer-body" id="drawer-body"></div></dialog>`;
 render();
}
const badge=(label,caution=false)=>`<span class="badge${caution?' caution':''}">${icon(caution?'info':'file')}${label}</span>`;
function directLead(s,feature=false){
 const e=data.evidence[s.supplierId];
 if(feature)return `<article class="lead-feature"><div class="feature-top"><div>${badge('Achiziții directe · grup apropiat în timp')}<h2>Șapte achiziții.<br>Aceeași zi.</h2><p><strong>${clean(s.supplierName)}</strong> apare în șapte achiziții de servicii de expertiză, însumând <strong>${money(e.totalExact)}</strong>.</p></div><div class="date-block"><strong>7 martie 2023</strong>CNAIR → VALURO</div></div>
 <div class="feature-chart"><div class="chart-heading"><strong>Fiecare bară este o achiziție</strong><span>Valoare fără TVA</span></div><div class="mini-bars">${e.records.map(r=>`<button data-action="direct" data-id="${s.supplierId}" data-record="${r.refId}" aria-label="${esc(r.daCode)} · ${esc(money(r.valueExact))}"><span>${n(Number(r.valueExact)/1000,Number(r.valueExact)%1000?1:0)} mii</span><i style="--height:${Math.max(8,Number(r.valueExact)/Math.max(...e.records.map(x=>Number(x.valueExact)))*85)}px"></i></button>`).join('')}</div><div class="chart-caption"><span>7 achiziții finalizate în aceeași zi</span><span>Apasă o bară pentru sursă</span></div></div>
 <div class="feature-bottom"><div class="observation"><div><h3>De ce merită verificat</h3><p>Același furnizor, aceeași clasă CPV și aceeași zi. Obiectul fiecărei achiziții arată dacă necesitățile sunt legate.</p></div><div><h3>Ce nu putem concluziona</h3><p>Suma cumulată nu demonstrează o divizare ilegală. Tipul a fost dedus din CPV pentru cele șapte achiziții.</p></div></div><div class="actions"><button class="primary" data-action="direct" data-id="${s.supplierId}">Verifică cele 7 achiziții ${icon('arrow')}</button>${appLink(`/entitati/${s.supplierId}`,'Profilul furnizorului')}</div></div></article>`;
 return `<article class="lead-row"><div>${badge('Achiziții directe')}<h3>${s.n} achiziții, ${s.d0===s.d1?'în aceeași zi':`între ${date(s.d0)} și ${date(s.d1)}`}</h3><p><strong>${esc(clean(s.supplierName))}</strong> · ${esc(s.cpvName)}. Aceeași clasă CPV și același tip, într-o fereastră de cel mult 60 de zile.</p><button class="quiet" data-action="direct" data-id="${s.supplierId}">Vezi exact cele ${s.n} achiziții ${icon('arrow')}</button></div><div class="side-number">${shortMoney(e.totalExact)}<small>lei · valoare cumulată</small></div></article>`;
}
function lotLead(){return `<article class="lead-row"><div>${badge('Loturi · tipar repetat')}<h3>Același câștigător în toate loturile, în șase proceduri.</h3><p><strong>OYL COMPANY HOLDING AG</strong> · 2018–2024. Tiparul apare în 6 dintre cele 125 de proceduri cu cel puțin trei loturi din clasa CPV 4523.</p><p class="small">Repetarea nu dovedește o înțelegere. Numărul ofertelor este necunoscut pentru acest tipar.</p><button class="quiet" data-action="pattern">Deschide contractele tiparului ${icon('arrow')}</button></div><div class="side-number">200,9 mil.<small>lei · valoarea tiparului</small></div></article>`;}
function capacityLead(){return `<article class="lead-row"><div>${badge('Context financiar · cotă estimată',true)}<h3>Un contract mare. O comparație care cere context.</h3><p>Pentru <strong>ESTA CONSTRUCTION GROUP</strong>, aplicația estimează o cotă de 289,7 milioane lei dintr-un contract de asociere. Cifra de afaceri din 2023 este de 3,9 milioane lei.</p><p class="small">Cota este împărțită egal între cei trei membri. Participația contractuală reală și durata execuției trebuie verificate.</p><button class="quiet" data-action="capacity">Înțelege comparația și verifică sursa ${icon('arrow')}</button></div><div class="side-number">1 contract<small>asociere cu 3 membri</small></div></article>`;}
function renderA(){
 const t=state.aType;
 const buttons=[['all','Toate pistele'],['direct','Achiziții directe'],['lots','Loturi'],['capacity','Context financiar']];
 document.querySelector('#content').innerHTML=`<div class="view-intro"><h2>De unde începi verificarea?</h2><p>O selecție de observații din această radiografie. Deschide sursele, citește contextul și decide ce merită urmărit.</p></div><nav class="tabs" aria-label="Tipul pistelor">${buttons.map(([id,label])=>`<button aria-pressed="${t===id}" data-action="atype" data-id="${id}">${label}</button>`).join('')}</nav><div class="a-layout"><div>
 ${['all','direct'].includes(t)?directLead(valuro,true):''}<div class="lead-list">${['all','lots'].includes(t)?lotLead():''}${['all','capacity'].includes(t)?capacityLead():''}${['all','direct'].includes(t)?directLead(middle):''}${state.showAll&&['all','direct'].includes(t)?data.slices.filter(s=>![valuro.supplierId,middle.supplierId].includes(s.supplierId)).map(s=>directLead(s)).join(''):''}</div>
 ${['all','direct'].includes(t)?`<div class="section-foot"><button class="button" data-action="all-direct">${state.showAll?'Restrânge lista':'Vezi toate cele 7 grupuri de achiziții directe'} ${icon('arrow')}</button><p class="small muted" style="margin-top:12px">Grupuri detectate prin criteriile actuale. Lipsa unui tipar nu confirmă absența unei probleme.</p></div>`:''}</div>
 <aside class="a-aside"><h2>Urmează firul datelor</h2><p>Fiecare observație are o explicație și o listă de surse. Nu trebuie să interpretezi mai întâi un grafic.</p><div class="aside-links"><button data-action="atype" data-id="direct"><span>Achiziții apropiate în timp</span><b>7 grupuri</b></button><button data-action="atype" data-id="lots"><span>Loturi câștigate repetat</span>${icon('arrow')}</button><button data-action="atype" data-id="capacity"><span>Contextul furnizorilor</span>${icon('arrow')}</button></div><div class="method-note"><h3>Observație, nu verdict</h3><p>Contractele nu sunt plăți. Cotele asocierilor pot fi estimate. Un tipar repetat este o invitație la verificare.</p><details><summary>Ce date comparăm?</summary><p>Istoricul instituției acoperă 2016–2026. Comparația ESTA folosește un contract semnat în 2023 și cifra de afaceri din acel an. Fiecare pistă își afișează propria perioadă.</p></details></div></aside></div>`;
}
function relationLink(id){const spec={block:'fact_check',dataset:'contracts',measure:'value',filters:{authorityId:2146146,supplierId:Number(id)}};return `/intreaba?spec=${encodeURIComponent(btoa(JSON.stringify(spec)))}&drill=1`;}
function supplierPanel(s){return `<span class="selection-type">Furnizor selectat · ${s.y0}–${s.y1}</span><h3>${esc(clean(s.name))}</h3><dl><div><dt>Valoare alocată din contractele CNAIR</dt><dd>${shortMoney(s.here)} lei</dd></div><div><dt>Din valoarea contractelor CNAIR</dt><dd>${pct(s.shareHere)}</dd></div><div><dt>CNAIR în contractele publice observate ale firmei</dt><dd>${pct(s.shareLife)}</dd></div><div><dt>Contracte în relație</dt><dd>${n(s.n)}</dd></div></dl><p class="caveat">Ponderi în contractele din datele disponibile, nu în toate veniturile firmei. În asocieri, cotele pot fi estimate.</p>${appLink(relationLink(s.id),'Verifică relația în contracte','button primary')}`;}
function dependencyRows(){return data.dep.filter(s=>!state.query||fold(s.name).includes(fold(state.query))).slice(0,state.limit);}
function supplierChart(rows){
 const w=700,h=370,l=62,r=25,t=68,b=52,pw=w-l-r,ph=h-t-b;
 const maxX=Math.max(.02,...rows.map(s=>s.shareHere))*1.14;
 const {k,x,y}=state.zoom;
 const X=v=>l+(v/maxX-x)*k*pw,Y=v=>t+(1-v-y)*k*ph,R=v=>Math.min(24,5+Math.sqrt(v/1e6)*.25);
 const visible=rows.filter(s=>X(s.shareHere)>=l&&X(s.shareHere)<=w-r&&Y(s.shareLife)>=t&&Y(s.shareLife)<=h-b);
 return `<svg viewBox="0 0 ${w} ${h}" role="group" aria-label="Ponderile furnizorilor în contractele CNAIR. Zoom ${n(k,1)} ori."><defs><clipPath id="supplier-clip"><rect x="${l-25}" y="${t-25}" width="${pw+50}" height="${ph+50}"/></clipPath></defs>${[0,.25,.5,.75,1].map(v=>{const py=t+v*ph;return `<line class="plot-grid" x1="${l}" y1="${py}" x2="${w-r}" y2="${py}"/><text class="chart-axis" text-anchor="end" x="${l-12}" y="${py+4}">${pct(Math.max(0,1-y-v/k))}</text>`;}).join('')}${[0,.25,.5,.75,1].map(v=>`<text class="chart-axis" text-anchor="middle" x="${l+v*pw}" y="${h-b+24}">${pct((x+v/k)*maxX)}</text>`).join('')}<text class="chart-label" x="${l}" y="16">CNAIR în contractele publice ale firmei</text><text class="chart-axis" text-anchor="middle" x="${w/2}" y="${h-3}">Ponderea furnizorului în valoarea contractelor CNAIR</text><g clip-path="url(#supplier-clip)">${visible.map(s=>`<g class="point ${state.selected===s.id?'selected':''}" role="button" tabindex="0" aria-pressed="${state.selected===s.id}" aria-label="${esc(clean(s.name))}, ${pct(s.shareLife)} din contractele publice observate de la CNAIR" data-action="supplier" data-id="${s.id}"><circle cx="${X(s.shareHere)}" cy="${Y(s.shareLife)}" r="${R(s.here)}"/><title>${esc(clean(s.name))} · ${pct(s.shareHere)} din CNAIR · ${pct(s.shareLife)} din portofoliul public</title>${state.selected===s.id?`<text class="selected-label" x="${Math.min(w-210,Math.max(l,X(s.shareHere)-60))}" y="${Y(s.shareLife)>h-b-60?Y(s.shareLife)-R(s.here)-10:Y(s.shareLife)+R(s.here)+20}">${esc(clean(s.name).slice(0,29))}</text>`:''}</g>`).join('')}</g></svg>`;
}
function zoomControls(){return `<div class="zoom-toolbar" role="group" aria-label="Mărire grafic furnizori"><span>Explorează graficul</span><div><button data-action="zoom-out" aria-label="Micșorează graficul" ${state.zoom.k<=1?'disabled':''}>${zoomIcon('minus')}</button><output id="zoom-level" aria-live="polite">${n(state.zoom.k,1)}×</output><button data-action="zoom-in" aria-label="Mărește graficul" ${state.zoom.k>=12?'disabled':''}>${zoomIcon('plus')}</button><button class="zoom-reset" data-action="zoom-reset">Resetează</button></div></div>`;}
function zoomIcon(kind){return `<svg class="icon" viewBox="0 0 18 18" aria-hidden="true"><path d="M4 9h10${kind==='plus'?'M9 4v10':''}"/></svg>`;}
function refreshZoom(){
 const viewport=document.querySelector('#supplier-viewport');if(!viewport)return;
 viewport.innerHTML=supplierChart(dependencyRows());
 document.querySelector('#zoom-level').textContent=`${n(state.zoom.k,1)}×`;
 document.querySelector('[data-action="zoom-out"]').disabled=state.zoom.k<=1;
 document.querySelector('[data-action="zoom-in"]').disabled=state.zoom.k>=12;
}
function changeZoom(factor,ax,ay){
 const z=state.zoom;
 if(ax==null){const rows=dependencyRows(),selected=rows.find(s=>s.id===state.selected);const maxX=Math.max(.02,...rows.map(s=>s.shareHere))*1.14;ax=Math.max(0,Math.min(1,((selected?.shareHere??maxX/2)/maxX-z.x)*z.k));ay=Math.max(0,Math.min(1,(1-(selected?.shareLife??.5)-z.y)*z.k));}
 const next=Math.min(12,Math.max(1,z.k*factor));
 state.zoom={k:next,x:Math.max(0,Math.min(1-1/next,z.x+ax/z.k-ax/next)),y:Math.max(0,Math.min(1-1/next,z.y+ay/z.k-ay/next))};refreshZoom();
}

function renderSuppliers(){
 const rows=dependencyRows();if(!rows.some(s=>s.id===state.selected)&&rows.length)state.selected=rows[0].id;
 const selected=rows.find(s=>s.id===state.selected);
 return `<div class="b-toolbar"><label>Caută un furnizor<input id="supplier-query" type="search" value="${esc(state.query)}" placeholder="Nume de firmă…"></label><div class="toolbar-right"><label>Furnizori afișați<select id="supplier-limit"><option value="12" ${state.limit===12?'selected':''}>Primii 12 după valoare</option><option value="25" ${state.limit===25?'selected':''}>Primii 25 după valoare</option><option value="150" ${state.limit===150?'selected':''}>Toți cei 150 din grafic</option></select></label></div></div>
 ${!rows.length?'<div class="empty"><h3>Niciun furnizor găsit</h3><p>Încearcă un alt nume în selecția celor 150 de furnizori.</p><button data-action="reset-suppliers">Șterge căutarea</button></div>':`<section class="workspace"><div class="workspace-heading"><div><h2>Cât de strânsă este relația?</h2><p>Selectează un furnizor. Valorile și sursele rămân alături de grafic.</p></div></div><div class="workspace-grid"><div><div class="chart-area dependency-plot">${zoomControls()}<div id="supplier-viewport" class="zoom-viewport" tabindex="0" role="group" aria-label="Grafic cu zoom. Plus și minus pentru mărire, săgeți pentru deplasare, zero pentru resetare.">${supplierChart(rows)}</div><p class="zoom-help">Ctrl / ⌘ + scroll pentru zoom · trage pentru deplasare · click pe cerc pentru detalii</p><div class="chart-legend"><span><i></i>Fiecare cerc = un furnizor</span><span>Mărime = valoarea alocată din contracte</span></div><p class="chart-summary">Axa verticală măsoară dependența în contractele publice observate. Un procent mare nu înseamnă că firma nu are și clienți privați.</p></div><div class="dependency-mobile"><p class="small muted">Furnizori ordonați după valoare. Procentul arată ponderea CNAIR în contractele publice ale firmei.</p>${rows.map(s=>`<button class="mobile-supplier" data-action="supplier" data-id="${s.id}" aria-pressed="${state.selected===s.id}"><span>${esc(clean(s.name))}<small>${shortMoney(s.here)} lei alocați</small></span><strong>${pct(s.shareLife)}</strong></button>`).join('')}</div></div><aside class="selection-panel" id="supplier-detail" aria-live="polite">${supplierPanel(selected)}</aside></div><div class="workspace-bottom"><span>${rows.length} furnizori selectați din 150 · întregul istoric disponibil</span><button class="quiet" data-action="jump-table">Vezi aceleași date în tabel ${icon('arrow')}</button></div></section>
 <section class="ranking" id="supplier-table"><div class="section-heading"><div><h2>Aceeași relație, în cifre</h2><p>Valorile estimate pentru membrii unei asocieri nu sunt plăți.</p></div></div><div class="table-scroll" role="region" aria-label="Indicatorii furnizorilor" tabindex="0"><table><thead><tr><th>Furnizor</th><th class="num">Valoare alocată</th><th class="num">Din CNAIR</th><th class="num">CNAIR în portofoliul public</th><th>Surse</th></tr></thead><tbody>${rows.map(s=>`<tr class="${state.selected===s.id?'selected':''}"><td><button class="quiet" data-action="supplier" data-id="${s.id}">${esc(clean(s.name))}</button></td><td class="num">${shortMoney(s.here)} lei</td><td class="num">${pct(s.shareHere)}</td><td class="num">${pct(s.shareLife)}</td><td>${appLink(relationLink(s.id),`${n(s.n)} contracte`)}</td></tr>`).join('')}</tbody></table></div><p class="metric-note">Selecția include cel mult 150 de furnizori peste pragul de afișare al radiografiei. Pentru CNAIR, pragul este aproximativ 53 milioane lei în valoare alocată.</p></section>`}`;
}
const className = id => ({'4523':'Drumuri, rețele și infrastructură','5010':'Întreținerea vehiculelor și echipamentelor','7152':'Supravegherea lucrărilor'}[id]||data.families[id]?.name||id);
function matrixData(){
 const rows=data.families[state.class].rows;
 const byContract=new Map();
 for(const row of rows){if(state.period!=='all'){const [from,to]=state.period.split('-').map(Number);const y=Number(row.d.slice(0,4));if(y<from||y>to)continue;}if(!byContract.has(row.contractId))byContract.set(row.contractId,[]);byContract.get(row.contractId).push(row);}
 const notices=new Map(),winners=new Map();
 for(const members of byContract.values()){
  const unique=[...new Map(members.map(m=>[m.supplierId,m])).values()].sort((a,b)=>a.supplierId.localeCompare(b.supplierId));const first=unique[0],key=unique.map(x=>x.supplierId).join('+');
  if(!notices.has(first.notice))notices.set(first.notice,{id:first.notice,date:first.d,cells:new Map(),contracts:[]});const col=notices.get(first.notice);col.date=col.date<first.d?col.date:first.d;col.contracts.push(first.contractId);
  if(!col.cells.has(key))col.cells.set(key,[]);col.cells.get(key).push(first.contractId);
  if(!winners.has(key))winners.set(key,{id:key,name:unique.map(x=>clean(x.supplierName)).join(' + '),value:0,members:unique.length});winners.get(key).value+=first.vFull;
 }
 const cols=[...notices.values()].filter(c=>c.contracts.length>=3).sort((a,b)=>a.date.localeCompare(b.date));
 const visibleKeys=new Set(cols.flatMap(c=>[...c.cells.keys()]));
 return {cols,winners:[...winners.values()].filter(w=>visibleKeys.has(w.id)).sort((a,b)=>b.value-a.value)};
}
function renderLots(){
 const {cols,winners}=matrixData();const pages=Math.max(1,Math.ceil(cols.length/8));state.matrixPage=Math.min(state.matrixPage,pages);
 const visible=cols.slice((state.matrixPage-1)*8,state.matrixPage*8);
 const activeKeys=new Set(visible.flatMap(c=>[...c.cells.keys()]));const rows=winners.filter(w=>activeKeys.has(w.id));
 if(!state.matrixSelection||!visible.some(c=>c.id===state.matrixSelection.notice&&c.cells.has(state.matrixSelection.winner))){const first=visible[0];state.matrixSelection=first?{notice:first.id,winner:[...first.cells.keys()][0]}:null;}
 const selected=state.matrixSelection;const selectedCol=selected?cols.find(c=>c.id===selected.notice):null;const selectedWinner=selected?winners.find(w=>w.id===selected.winner):null;
 return `<div class="b-toolbar"><label>Domeniul CPV<input type="search" id="cpv-search" placeholder="Caută domeniu în cele 37 de categorii…" aria-label="Caută un domeniu CPV"><select id="cpv-select" aria-label="Domeniul CPV">${Object.keys(data.families).sort((a,b)=>className(a).localeCompare(className(b),'ro')).map(id=>`<option value="${id}" ${id===state.class?'selected':''}>${esc(className(id))} · ${id}</option>`).join('')}</select></label><div class="toolbar-right"><label>Perioada procedurilor<select id="lot-period"><option value="2022-2024" ${state.period==='2022-2024'?'selected':''}>2022–2024</option><option value="2025-2026" ${state.period==='2025-2026'?'selected':''}>2025–2026</option><option value="2016-2021" ${state.period==='2016-2021'?'selected':''}>2016–2021</option><option value="all" ${state.period==='all'?'selected':''}>Toți anii</option></select></label></div></div>
 <section class="workspace"><div class="workspace-heading"><div><h2>Cine câștigă loturile?</h2><p>${esc(className(state.class))} · ${cols.length} proceduri cu cel puțin 3 contracte în selecție. Asocierile apar împreună.</p></div></div>
 ${!cols.length?'<div class="empty"><h3>Nicio procedură în acest interval</h3><p>Alege altă perioadă sau alt domeniu CPV.</p><button data-action="lot-all-years">Vezi toți anii</button></div>':`<div class="matrix-wrap"><div class="chart-legend"><span><i></i>Verde închis: toate loturile procedurii</span><span>Fracția arată loturile câștigate / totalul</span></div><div class="matrix-scroll" role="region" tabindex="0" aria-label="Matricea loturilor, derulare orizontală"><table class="matrix"><thead><tr><th>Furnizor / asociere</th>${visible.map(c=>`<th>${date(c.date)}<small>${esc(c.id)}</small><small>${c.contracts.length} loturi</small></th>`).join('')}</tr></thead><tbody>${rows.map(w=>`<tr><td>${esc(w.name)}${w.members>1?'<small class="muted"> · asociere</small>':''}</td>${visible.map(c=>{const contracts=c.cells.get(w.id);return `<td>${contracts?`<button class="cell ${contracts.length===c.contracts.length?'all':''}" aria-pressed="${selected?.notice===c.id&&selected?.winner===w.id}" data-action="matrix" data-notice="${c.id}" data-winner="${w.id}" aria-label="${esc(w.name)} · ${esc(c.id)} · ${contracts.length} din ${c.contracts.length} loturi">${contracts.length}/${c.contracts.length}</button>`:'<span class="empty-cell" aria-label="Niciun lot câștigat">—</span>'}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div><div class="pager"><button data-action="matrix-prev" ${state.matrixPage===1?'disabled':''}>Anterior</button><span>Procedurile ${(state.matrixPage-1)*8+1}–${Math.min(state.matrixPage*8,cols.length)} din ${cols.length}</span><button data-action="matrix-next" ${state.matrixPage===pages?'disabled':''}>Următor ${icon('arrow')}</button></div></div><div class="matrix-selection" aria-live="polite"><div><h3>${esc(selectedWinner.name)}</h3><p>${esc(selectedCol.id)} · ${date(selectedCol.date)} · ${selectedCol.cells.get(selectedWinner.id).length} din ${selectedCol.contracts.length} loturi. Selectează o celulă pentru a schimba sursele.</p></div><button class="primary" data-action="matrix-sources">Verifică aceste contracte ${icon('arrow')}</button></div>`}
 </section><p class="metric-note">În această vizualizare, contractele distincte dintr-un anunț reprezintă loturile. Câștigarea repetată nu dovedește o înțelegere. Numărul ofertelor nu este codificat prin culoare aici.</p>`;
}
function timeline(s){
 const e=data.evidence[s.supplierId];const records=e.records;const start=Date.parse(s.d0),end=Date.parse(s.d1),day=86400000;
 const from=state.fullHistory?Date.parse(`${Math.min(2020,...s.points.map(p=>Number(p.d.slice(0,4))))}-01-01`):start-14*day;
 const to=state.fullHistory?Date.parse('2026-12-31'):end+14*day;
 const points=state.fullHistory?s.points.map(p=>({refId:p.id,date:p.d,valueExact:p.v})):records;
 const mobile=matchMedia('(max-width:760px)').matches;
 const w=mobile?Math.max(280,innerWidth-76):1000,h=220,l=65,r=30,t=25,b=45,max=Math.max(s.ceiling,...points.map(p=>Number(p.valueExact)))*1.28;
 const X=v=>l+(Date.parse(v)-from)/(to-from)*(w-l-r),Y=v=>t+(1-Number(v)/max)*(h-t-b);
 const counts={};const dots=points.map(p=>{const key=p.date+':'+p.valueExact;const i=counts[key]||0;counts[key]=i+1;return {...p,jitter:i*8};});
 return `<svg viewBox="0 0 ${w} ${h}" role="group" aria-label="Achizițiile ${esc(clean(s.supplierName))}, intervalul selectat"><rect class="timeline-band" x="${X(s.d0)-6}" y="${t}" width="${Math.max(12,X(s.d1)-X(s.d0)+12)}" height="${h-t-b}"/>${[.25,.5,.75,1].map(v=>`<line class="plot-grid" x1="${l}" x2="${w-r}" y1="${Y(max*v)}" y2="${Y(max*v)}"/><text class="chart-axis" x="${l-9}" y="${Y(max*v)+4}" text-anchor="end">${n(max*v/1000)} mii</text>`).join('')}${!state.fullHistory?`<line class="timeline-ceiling" x1="${l}" x2="${w-r}" y1="${Y(s.ceiling)}" y2="${Y(s.ceiling)}"/><text class="chart-axis" text-anchor="end" x="${w-r}" y="${Y(s.ceiling)-8}">${mobile?'Plafon':'Plafonul grupului'}: ${n(s.ceiling)} lei</text>`:''}${[0,.25,.5,.75,1].map(v=>{const d=new Date(from+v*(to-from)).toISOString().slice(0,10);return `<text class="chart-axis" text-anchor="middle" x="${l+v*(w-l-r)}" y="${h-b+26}">${state.fullHistory?d.slice(0,4):date(d).slice(0,5)}</text>`;}).join('')}${dots.map(p=>`<circle class="timeline-dot" cx="${X(p.date)+p.jitter}" cy="${Y(p.valueExact)}" r="6" role="button" tabindex="0" aria-label="Achiziție ${date(p.date)}, ${esc(money(p.valueExact))}" data-action="direct-point" data-id="${s.supplierId}" data-record="${p.refId}"/>`).join('')}<text class="chart-axis" text-anchor="middle" x="${w/2}" y="${h-4}">${mobile?'Data finalizării':state.fullHistory?'Istoricul achizițiilor cu acest furnizor':'Data finalizării · fereastra detectată este evidențiată'}</text></svg>`;
}
function renderDirect(){
 const s=data.slices.find(s=>s.supplierId===state.slice),e=data.evidence[s.supplierId];
 return `<div class="direct-toolbar"><div><h2>Achiziții apropiate în timp</h2><p>Șapte grupuri de verificat. Alege un furnizor și urmărește sursele.</p></div><label>Grup de achiziții<select id="slice-select">${[valuro,...data.slices.filter(x=>x!==valuro)].map(x=>`<option value="${x.supplierId}" ${x.supplierId===s.supplierId?'selected':''}>${esc(clean(x.supplierName))} · ${x.n} achiziții</option>`).join('')}</select></label></div>
 <section class="workspace b-timeline"><div class="workspace-heading"><div><h2>${s.n} achiziții, ${s.d0===s.d1?'în aceeași zi':`în ${Math.round((Date.parse(s.d1)-Date.parse(s.d0))/86400000)+1} zile`}</h2><p>${esc(clean(s.supplierName))} · ${esc(s.cpvName)} · ${date(s.d0)}${s.d0===s.d1?'':`–${date(s.d1)}`}</p></div><button class="quiet" data-action="timeline-range">${state.fullHistory?'Revino la intervalul de verificat':'Vezi întregul istoric'} ${icon('arrow')}</button></div>
 <dl class="direct-facts"><div><dt>Valoarea celor ${s.n} achiziții</dt><dd>${money(e.totalExact)}</dd></div><div><dt>Plafon de referință</dt><dd>${n(s.ceiling)} lei</dd></div><div><dt>Tip dedus din CPV</dt><dd>${s.purchaseType==='works'?'Lucrări':'Produse / servicii'}</dd></div></dl>
 <div class="chart-area" role="region" tabindex="0" aria-label="Achizițiile în timp; graficul se poate derula orizontal pe mobil">${timeline(s)}</div>
 <div class="direct-source-bar"><p>Banda aurie arată intervalul detectat. Fiecare punct deschide achiziția.<br><span class="muted">Suma peste plafon este o pistă de verificare, nu o concluzie juridică.</span></p><button class="primary" data-action="direct" data-id="${s.supplierId}">Verifică cele ${s.n} surse ${icon('arrow')}</button></div></section><p class="metric-note">Tipul a fost dedus din CPV pentru ${s.typeInferredCount} achiziții. Punctele din aceeași zi și cu aceeași valoare sunt ușor decalate pentru a putea fi selectate. Datele exacte apar în surse.</p>`;
}
function renderB(){document.querySelector('#content').innerHTML=`<nav class="tabs" aria-label="Perspective de explorare" style="margin-top:23px">${[['suppliers','Furnizori'],['lots','Loturi'],['direct','Achiziții directe']].map(([id,label])=>`<button aria-pressed="${state.tab===id}" data-action="btab" data-id="${id}">${label}${id==='direct'?'<span class="count">7</span>':''}</button>`).join('')}</nav><div class="b-tab-panel">${state.tab==='suppliers'?renderSuppliers():state.tab==='lots'?renderLots():renderDirect()}</div>`;}
function render(){variant==='a'?renderA():renderB();}
function openDrawer(title,subtitle,body){document.querySelector('#drawer-title').textContent=title;document.querySelector('#drawer-subtitle').textContent=subtitle;document.querySelector('#drawer-body').innerHTML=body;const drawer=document.querySelector('#sources');if(!drawer.open)drawer.showModal();drawer.scrollTop=0;}
function directSources(id,record){const s=data.slices.find(s=>s.supplierId===id),e=data.evidence[id];openDrawer(`${e.records.length} achiziții de verificat`,`${clean(s.supplierName)} · ${date(s.d0)}${s.d0===s.d1?'':`–${date(s.d1)}`}`,`<div class="drawer-context">Acestea sunt exact achizițiile folosite în calcul. Aceeași clasă CPV și proximitatea în timp nu demonstrează singure o divizare ilegală. Tipul a fost dedus din CPV pentru ${s.typeInferredCount} înregistrări.</div><div class="drawer-total"><span>Valoarea cumulată</span><strong>${money(e.totalExact)}</strong></div>${e.records.map(r=>`<article class="source-record ${r.refId===record?'highlight':''}" id="record-${r.refId}"><div class="meta"><span>${esc(r.daCode)}</span><span>${date(r.date)}</span><span>CPV ${esc(r.cpvCode)}</span></div><h3>${appLink(`/achizitii/${r.refId}`,esc(r.title),'')}</h3><div class="record-foot"><strong>${money(r.valueExact)}</strong><a href="https://e-licitatie.ro/pub/direct-acquisition/view/${r.refId}" target="_blank" rel="noopener noreferrer">Verifică în SEAP ${icon('external')}</a></div></article>`).join('')}<div class="drawer-actions">${appLink(`/entitati/2146146/radiografie/surse?tip=slicing&furnizor=${s.supplierId}`,'Selecția în aplicație','button')}</div>`);if(record)requestAnimationFrame(()=>document.querySelector(`#record-${record}`)?.scrollIntoView({block:'center'}));}
function contractRecords(ids){return [...new Set(ids)].map(id=>{const c=data.contracts[id];if(!c)return '';const r=Object.values(data.families).flatMap(f=>f.rows).find(r=>r.contractId===id);return `<article class="source-record"><div class="meta"><span>${esc(c.contract_no||`Contract ${c.external}`)}</span><span>${date(r.d)}</span></div><h3>${appLink(`/contracte/${c.external}`,esc(c.title),'')}</h3><div class="record-foot"><strong>${money(r.vFull)}</strong><a href="https://e-licitatie.ro/pub/notices/ca-notices/view-c/${c.notice_id}" target="_blank" rel="noopener noreferrer">Anunțul SEAP ${icon('external')}</a></div><p class="small">Valoarea integrală a contractului, o singură dată pentru asociere.</p></article>`;}).join('');}
function patternSources(){const rows=data.families[oyl.cpvClass].rows.filter(r=>oyl.notices.includes(r.notice)&&oyl.memberIds.includes(r.supplierId));const ids=[...new Set(rows.map(r=>r.contractId))];openDrawer('Contractele tiparului OYL','CPV 4523 · 2018–2024',`<div class="drawer-context">Tipar în 6 dintre cele 125 de proceduri cu cel puțin trei loturi. O repetare nu dovedește o înțelegere. Numărul ofertelor este necunoscut pentru acest tipar.</div><div class="drawer-total"><span>${ids.length} contracte distincte</span></div>${contractRecords(ids)}<div class="drawer-actions">${appLink(`/entitati/2146146/radiografie/surse?tip=pattern&tipar=${oyl.id}&fingerprint=${oyl.fingerprint}`,'Selecția verificabilă în aplicație','button')}</div>`);}
function capacity(){openDrawer('ESTA: ce compară aceste cifre?','Contract semnat în 2023 · alocare estimată',`<div class="drawer-context">289,7 milioane lei reprezintă o treime estimată din valoarea contractului de 869,2 milioane lei, atribuit unei asocieri cu trei membri. Cota reală nu este stabilită de acest calcul.</div><div class="comparison"><div><small>Cotă estimată în contract</small><strong>289,7 mil. lei</strong><small>1/3 din valoarea integrală</small></div><div><small>Cifră de afaceri 2023</small><strong>3,9 mil. lei</strong><small>${money(esta.turnWin)} în date</small></div></div><div class="explain"><h3>Comparația are limite</h3><p>Un contract se poate executa pe mai mulți ani. Cifra de afaceri din anul semnării nu este aceeași măsură cu valoarea contractuală și nu reprezintă numerarul încasat.</p><h3>Ce merită verificat</h3><p>Participația fiecărui asociat, calendarul execuției, subcontractarea și situațiile financiare din anii relevanți.</p></div>${contractRecords(['982697'])}`);}
let queryTimer;
document.addEventListener('click',event=>{
 const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const a=button.dataset.action,id=button.dataset.id;
 if(a==='supplier'&&Date.now()<suppressPointClick)return;
 if(a==='zoom-in'||a==='zoom-out'){changeZoom(a==='zoom-in'?1.6:1/1.6);return;}
 if(a==='zoom-reset'){state.zoom={k:1,x:0,y:0};refreshZoom();return;}
 if(a==='theme'){const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('rx-mock-theme',theme);}catch{}return;}
 if(a==='close'){document.querySelector('#sources').close();return;}
 if(a==='direct'){directSources(id,button.dataset.record);return;}
 if(a==='direct-point'){const e=data.evidence[id];if(e.records.some(r=>r.refId===button.dataset.record))directSources(id,button.dataset.record);else window.open(`${APP}/achizitii/${button.dataset.record}`,'_blank','noopener');return;}
 if(a==='capacity'){capacity();return;}if(a==='pattern'){patternSources();return;}
 if(a==='atype'){state.aType=id;renderA();document.querySelector(`.tabs [data-id="${id}"]`)?.focus({preventScroll:true});return;}
 if(a==='all-direct'){state.showAll=!state.showAll;renderA();return;}
 if(a==='btab'){state.tab=id;renderB();document.querySelector(`[data-action="btab"][data-id="${id}"]`)?.focus({preventScroll:true});return;}
 if(a==='supplier'){const wasPoint=button.matches('.point');state.selected=id;renderB();document.querySelector(`${wasPoint?'.point':'.ranking button'}[data-id="${id}"]`)?.focus({preventScroll:true});document.querySelector(`#supplier-detail`)?.setAttribute('tabindex','-1');if(matchMedia('(max-width:760px)').matches)document.querySelector('#supplier-detail').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='jump-table'){document.querySelector('#supplier-table').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='reset-suppliers'){state.query='';state.zoom={k:1,x:0,y:0};renderB();return;}
 if(a==='matrix'){state.matrixSelection={notice:button.dataset.notice,winner:button.dataset.winner};const old=document.querySelector('.matrix-scroll');const pos={left:old.scrollLeft,top:old.scrollTop};renderB();const box=document.querySelector('.matrix-scroll');box.scrollLeft=pos.left;box.scrollTop=pos.top;document.querySelector(`[data-action="matrix"][data-notice="${CSS.escape(state.matrixSelection.notice)}"][data-winner="${CSS.escape(state.matrixSelection.winner)}"]`)?.focus({preventScroll:true});return;}
 if(a==='matrix-next'||a==='matrix-prev'){state.matrixPage+=a==='matrix-next'?1:-1;state.matrixSelection=null;renderB();return;}
 if(a==='lot-all-years'){state.period='all';renderB();return;}
 if(a==='matrix-sources'){const {cols,winners}=matrixData(),c=cols.find(c=>c.id===state.matrixSelection.notice),w=winners.find(w=>w.id===state.matrixSelection.winner),ids=c.cells.get(w.id);openDrawer(`${ids.length} contracte selectate`,`${w.name} · ${c.id}`,`<div class="drawer-context">${ids.length} din ${c.contracts.length} loturi ale procedurii. Asocierile sunt un singur câștigător. Sumele reprezintă contractele integrale, nu cote adunate per membru.</div>${contractRecords(ids)}`);return;}
 if(a==='slice'){state.slice=id;state.fullHistory=false;renderB();return;}
 if(a==='timeline-range'){state.fullHistory=!state.fullHistory;renderB();return;}
});
document.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)&&event.target.matches('svg [role=button]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.addEventListener('input',event=>{
 if(event.target.id==='supplier-query'){const value=event.target.value;clearTimeout(queryTimer);queryTimer=setTimeout(()=>{state.query=value;state.zoom={k:1,x:0,y:0};renderB();const input=document.querySelector('#supplier-query');input.focus({preventScroll:true});},180);}
 if(event.target.id==='cpv-search'){const term=fold(event.target.value);for(const option of document.querySelector('#cpv-select').options)option.hidden=!fold(option.textContent).includes(term);}
});
document.addEventListener('change',event=>{
 if(event.target.id==='slice-select'){state.slice=event.target.value;state.fullHistory=false;renderB();document.querySelector('#slice-select').focus({preventScroll:true});}
 if(event.target.id==='supplier-limit'){state.limit=Number(event.target.value);state.zoom={k:1,x:0,y:0};renderB();}
 if(event.target.id==='cpv-select'){state.class=event.target.value;state.matrixPage=1;state.matrixSelection=null;renderB();}
 if(event.target.id==='lot-period'){state.period=event.target.value;state.matrixPage=1;state.matrixSelection=null;renderB();}
});
let drag=null,suppressPointClick=0;
function plotPosition(viewport,event){const r=viewport.querySelector('svg').getBoundingClientRect();return {x:Math.max(0,Math.min(1,(event.clientX-r.left-r.width*62/700)/(r.width*613/700))),y:Math.max(0,Math.min(1,(event.clientY-r.top-r.height*68/370)/(r.height*250/370)))};}
document.addEventListener('wheel',event=>{const viewport=event.target.closest('#supplier-viewport');if(!viewport||!(event.ctrlKey||event.metaKey))return;event.preventDefault();const p=plotPosition(viewport,event);changeZoom(Math.exp(-event.deltaY*.003),p.x,p.y);},{passive:false});
document.addEventListener('pointerdown',event=>{const viewport=event.target.closest('#supplier-viewport');if(!viewport||event.button!==0)return;const r=viewport.getBoundingClientRect();drag={viewport,id:event.pointerId,cx:event.clientX,cy:event.clientY,x:state.zoom.x,y:state.zoom.y,w:r.width*613/700,h:r.width*250/700,moved:false};});
document.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.id)return;const dx=event.clientX-drag.cx,dy=event.clientY-drag.cy;if(!drag.moved&&Math.hypot(dx,dy)<5)return;drag.moved=true;drag.viewport.setPointerCapture(event.pointerId);drag.viewport.classList.add('dragging');state.zoom.x=Math.max(0,Math.min(1-1/state.zoom.k,drag.x-dx/drag.w/state.zoom.k));state.zoom.y=Math.max(0,Math.min(1-1/state.zoom.k,drag.y-dy/drag.h/state.zoom.k));refreshZoom();});
function endDrag(event){if(!drag||event.pointerId!==drag.id)return;if(drag.moved)suppressPointClick=Date.now()+250;drag.viewport.classList.remove('dragging');if(drag.viewport.hasPointerCapture(event.pointerId))drag.viewport.releasePointerCapture(event.pointerId);drag=null;}
document.addEventListener('pointerup',endDrag);document.addEventListener('pointercancel',endDrag);
document.addEventListener('keydown',event=>{if(event.target.id!=='supplier-viewport')return;const z=state.zoom;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();if(event.key==='0'){state.zoom={k:1,x:0,y:0};refreshZoom();}else if(['+','=','-'].includes(event.key))changeZoom(event.key==='-'?1/1.6:1.6);else {const dx=event.key==='ArrowRight'?.12:event.key==='ArrowLeft'?-.12:0,dy=event.key==='ArrowDown'?.12:event.key==='ArrowUp'?-.12:0;z.x=Math.max(0,Math.min(1-1/z.k,z.x+dx/z.k));z.y=Math.max(0,Math.min(1-1/z.k,z.y+dy/z.k));refreshZoom();}}});
shell();
