'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const format=n=>new Intl.NumberFormat('ro-RO').format(n);
const initial={min:50,max:70,daily:false,limit:1000,time:'05:00'};
let config={...initial},mode='live',paused=false,left=41,interval=60,requestCount=867,successCount=864,recordCount=128640,queueCount=4186,filter='all',toastTimer,sequence=20;
const pausedStreams=new Set();
const paths={da:'/api-pub/DirectAcquisitionCommon/GetDirectAcquisitionList/',tenders:'/api-pub/NoticeCommon/GetCNoticeList/',awards:'/api-pub/NoticeCommon/GetCANoticeList/',files:'/api-pub/files/noticedoc/{identificator-temporar}'};
const logs=[
 {id:6,time:'14:32:08',kind:'da',title:'Achiziții directe',context:'Municipiul Buzău · 1 iul. – 25 sept.',status:200,result:'128 înregistrări',duration:'1,2 s',method:'POST'},
 {id:5,time:'14:31:04',kind:'awards',title:'Anunțuri de atribuire',context:'10 martie 2026 · pagina 1',status:200,result:'100 înregistrări',duration:'0,8 s',method:'POST'},
 {id:4,time:'14:30:12',kind:'files',title:'Verificare pentru un document',context:'Solicitat de un utilizator · pas 3 din 4',status:200,result:'Fișier disponibil',duration:'0,4 s',method:'POST'},
 {id:3,time:'14:29:10',kind:'da',title:'Achiziții directe',context:'Interval prea mare · necesită împărțire',status:200,result:'Limită de rezultate',duration:'1,5 s',method:'POST'},
 {id:2,time:'11:08:24',kind:'awards',title:'Anunțuri de atribuire',context:'Colectare oprită atunci · reluată manual la 11:20',status:429,result:'Prea multe cereri',duration:'0,2 s',method:'POST'},
 {id:1,time:'09:45:30',kind:'da',title:'Achiziții directe',context:'Încercare eșuată · păstrată pentru verificare',status:503,result:'Serviciu indisponibil',duration:'2,0 s',method:'POST'},
 {id:0,time:'08:12:18',kind:'da',title:'Achiziții directe',context:'Încercare eșuată · păstrată pentru verificare',status:504,result:'Timp de răspuns depășit',duration:'30 s',method:'POST'}
];
function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function draft(){return {min:Number($('#delay-min').value),max:Number($('#delay-max').value),daily:$('#daily-enabled').checked,limit:Number($('#daily-limit').value),time:$('#maintenance-time').value};}
function errorFor(d){if(!Number.isInteger(d.min)||!Number.isInteger(d.max)||d.min<1||d.max>3600||d.max<d.min)return 'Alege un interval între 1 și 3.600 secunde, cu minimum ≤ maximum.';if(d.daily&&(!Number.isInteger(d.limit)||d.limit<1))return 'Limita zilnică trebuie să fie un număr întreg pozitiv.';if(!d.time)return 'Alege ora procesării.';return '';}
function changed(d){return d.min!==config.min||d.max!==config.max||d.daily!==config.daily||(d.daily&&d.limit!==config.limit)||d.time!==config.time;}
function edit(){const d=draft(),error=errorFor(d),dirty=changed(d);$('#daily-field').hidden=!d.daily;$('#daily-limit').disabled=!d.daily;$('#settings-error').hidden=!error;$('#settings-error').textContent=error;$('#apply').disabled=!!error||!dirty||mode==='offline';$('#apply').textContent=mode==='offline'?'Conexiune indisponibilă':dirty?'Aplică modificările':'Setările sunt la zi';$('#discard').hidden=!dirty;$('#settings-diff').hidden=!dirty||!!error;let message=`Interval: ${config.min}–${config.max} → ${d.min}–${d.max} sec. `;if(d.time!==config.time)message+=`Procesare: ${config.time} → ${d.time}. `;if(d.daily)message+=`Limită: ${format(d.limit)} cereri/zi. `;else if(config.daily)message+='Limita zilnică va fi dezactivată. ';if(d.min<config.min)message+='Ritmul poate crește; pauza în curs se păstrează.';$('#settings-diff').textContent=message;$('#rate-estimate').textContent=error?'Interval nevalid':`≈ ${format(Math.round(7200/(d.min+d.max)))} cereri / oră`;$('#rate-note').textContent=d.min<50?'Mai rapid decât intervalul convenit de 50–70 sec.':'La ritm continuu, fără mentenanță.';$$('.preset').forEach(b=>b.classList.toggle('selected',Number(b.dataset.min)===d.min&&Number(b.dataset.max)===d.max));}
function fillForm(){for(const [selector,value] of [['#delay-min',config.min],['#delay-max',config.max],['#daily-limit',config.limit],['#maintenance-time',config.time]])$(selector).value=value;$('#daily-enabled').checked=config.daily;edit();}
function addChange(message){const li=document.createElement('li');const time=new Date().toLocaleTimeString('ro-RO',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Bucharest'});li.innerHTML=`<time>${time}</time><span>${escape(message)}</span><span class="subtle">simulat</span>`;$('#changes').prepend(li);}
function renderLog(){const rows=logs.filter(r=>filter==='all'||filter==='errors'&&r.status>=400||r.kind===filter);$('#log-empty').hidden=rows.length>0;$('#log-rows').innerHTML=rows.slice(0,10).map(r=>`<tr><td>${r.time}</td><td>${escape(r.title)}<small>${escape(r.context)}</small></td><td><span class="result ${r.status>=400?'error':''}">${r.status} · ${escape(r.result)}</span></td><td>${r.duration}</td><td><button class="icon-button log-toggle" data-id="${r.id}" aria-expanded="false" aria-controls="detail-${r.id}" aria-label="Detalii cerere ${r.time}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button></td></tr><tr class="log-detail" id="detail-${r.id}" hidden><td colspan="5"><p><b>${r.method}</b> <code>${paths[r.kind]}</code></p><p>${r.kind==='files'?'Identificatorul temporar al fișierului nu este afișat. Fără cookie-uri sau tokenuri în jurnal.':'Parametri demonstrativi. Cererea nu a fost trimisă.'}</p>${r.kind==='files'?'':`<pre>${escape(JSON.stringify(r.kind==='da'?{finalizationDateStart:'2026-07-01',finalizationDateEnd:'2026-09-25',pageIndex:0,pageSize:2000,contractingAuthority:'Municipiul Buzău (exemplu)'}:{startPublicationDate:'2026-03-10',endPublicationDate:'2026-03-10',pageIndex:0,pageSize:100},null,2))}</pre>`}${r.status>=400?'<p><b>Încercare numărată în buget. Nicio reîncercare automată.</b></p>':''}</td></tr>`).join('');}
function activeKind(){return ['da','tenders','awards'].find(k=>!pausedStreams.has(k));}
function renderState(){const capped=config.daily&&requestCount>=config.limit,idle=!activeKind(),running=mode==='live'&&!paused&&!capped&&!idle;let title='Colectăm, în ritmul stabilit.',copy='Un singur buget pentru date și documente. Nicio cerere în paralel.',notice='',label='Următoarea cerere în',display=`${left}<span> sec</span>`,button='Pune pe pauză',hint='Progresul se păstrează.',task={da:'Achiziții directe · Municipiul Buzău',tenders:'Participare · următoarea zi de verificat',awards:'Atribuiri · următoarea zi de verificat'}[activeKind()]||'Toate cele trei fluxuri sunt pe pauză.';
 if(paused){title='Colectarea este pe pauză.';copy='Nicio cerere nouă. Datele salvate și poziția în coadă se păstrează.';display='Pauză';label='Colectare oprită manual';button='Reia colectarea';}
 if(idle&&!paused){title='Toate fluxurile sunt pe pauză.';display='Pauză';label='Reia un flux de mai jos';}
 if(capped){title='Limita zilnică a fost atinsă.';copy=`${format(requestCount)} încercări din limita de ${format(config.limit)}. Nu mai pornim cereri astăzi.`;label='Reluare automată la';display='00:00';notice='Poți modifica limita din setări. Încercările eșuate sunt incluse în bugetul zilnic.';}
 if(mode==='blocked'){title='SEAP ne cere să așteptăm.';copy='Ultimul răspuns: 429 · Prea multe cereri. Coada comună s-a oprit.';label='Reluare automată';display='Oprită';button='Reia simularea';notice='Nicio cerere nouă, inclusiv pentru documente. Verifică răspunsul sursei și termenul Retry-After înainte de reluarea manuală.';hint='Doar în acest mock-up.';task='Ultima încercare · răspuns 429';}
 if(mode==='offline'){title='Nu mai primim statusul serverului.';copy='Valorile afișate sunt ultima stare cunoscută. Colectarea poate continua pe server.';label='Ultima actualizare';display='acum 2 min';notice='Conexiunea de raportare este întreruptă. Comenzile sunt indisponibile până la reconectare.';button='Conexiune pierdută';hint='Nu presupunem că s-a oprit.';task='Așteptăm reconectarea';}
 if(mode==='maintenance'||mode==='failure'){title=mode==='failure'?'Procesarea s-a oprit. Site-ul rămâne în mentenanță.':'Procesăm lotul. Site-ul este în mentenanță.';copy='Colectarea este oprită; păstrăm aceeași versiune până la verificarea noului lot.';label='Cereri SEAP';display='Oprite';button='Colectare oprită';hint='Coada și progresul se păstrează.';task=mode==='failure'?'Eroare la verificarea totalurilor':'Procesare incrementală · lotul de la 05:00';if(mode==='failure')notice='Verificarea totalurilor a eșuat. Nu publicăm lotul și nu redeschidem site-ul automat. Urmează investigarea erorii sau restaurarea copiei verificate.';}
 $('#collection').dataset.state=mode==='live'?(running?'live':'paused'):mode;$('#state-title').textContent=title;$('#state-copy').textContent=copy;$('#task-name').textContent=task;$('#task-label').textContent=mode==='live'?'Urmează':'Stare';$('#countdown-label').textContent=label;$('#countdown').innerHTML=display;$('#countdown').style.fontSize=mode==='offline'?'22px':'';$('#countdown-fill').style.transform=`scaleX(${running?Math.min(1,left/interval):0})`;$('#active-delay').textContent=`Interval aleator: ${config.min}–${config.max} sec`;$('#pause span').textContent=button;$('#pause').disabled=['offline','maintenance','failure'].includes(mode)||capped||idle;$('#pause-hint').textContent=hint;$('#status-notice').textContent=notice;$('#status-notice').hidden=!notice;$('#connection').classList.toggle('stale',mode==='offline');$('#connection').innerHTML=mode==='offline'?'<i></i> Status neactualizat · acum 2 min':'<i></i> Actualizare live · simulată';
 $('#requests').textContent=format(requestCount);$('#successes').textContent=format(successCount);$('#records').textContent=format(recordCount);$('#pending').textContent=format(recordCount);$('#queued').textContent=format(queueCount);$('#publish-time').textContent=config.time;$('#publication-badge').textContent=mode==='maintenance'?'În procesare':mode==='failure'?'Necesită intervenție':'Programat';$('#publication-badge').className='badge '+(['maintenance','failure'].includes(mode)?'warning':'neutral');$('#publication-copy').textContent=mode==='maintenance'?'Lot fixat: 128.640 înregistrări. Normalizarea este în curs; nicio publicare parțială.':mode==='failure'?'Lot nepublicat. Ultima etapă: verificarea totalurilor. Mentenanța rămâne activă.':'Datele colectate așteaptă aici. Devin vizibile după procesare și verificare.';
 $$('.pipeline li').forEach((li,i)=>{li.className=(i===0||mode==='failure'&&i===1)?'done':(mode==='maintenance'&&i===1||mode==='failure'&&i===2)?'current':'';});
 $$('.stream').forEach(s=>{const stopped=pausedStreams.has(s.dataset.stream);s.dataset.paused=String(stopped);const badge=s.querySelector('.badge');badge.textContent=stopped?'Pe pauză':!running?'În așteptare':s.dataset.stream===activeKind()?'În curs':'În coadă';badge.className='badge '+(stopped?'warning':running&&s.dataset.stream===activeKind()?'':'neutral');const b=s.querySelector('button');b.disabled=mode==='offline';b.setAttribute('aria-pressed',String(stopped));b.setAttribute('aria-label',`${stopped?'Reia':'Pune pe pauză'} ${s.querySelector('h3').textContent.toLowerCase()}`);b.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${stopped?'m8 5 11 7-11 7Z':'M8 5v14M16 5v14'}"/></svg>`;});
}
$('#settings-form').addEventListener('input',edit);
$('#settings-form').addEventListener('submit',e=>{e.preventDefault();const d=draft();if(errorFor(d)||mode==='offline')return;const old={...config};config=d;left=Math.max(left,config.min);interval=Math.max(interval,left);addChange(`Administrator · interval ${old.min}–${old.max} → ${config.min}–${config.max} sec; procesare ${config.time}; ${config.daily?'limită '+format(config.limit)+'/zi':'fără limită zilnică'}.`);edit();renderState();toast('Setări aplicate în simulare. Serverul real nu a fost modificat.');});
$('#discard').onclick=fillForm;
$$('.preset').forEach(b=>b.onclick=()=>{$('#delay-min').value=b.dataset.min;$('#delay-max').value=b.dataset.max;edit();});
$('#pause').onclick=()=>{if(mode==='blocked'){$('#scenario').value='live';mode='live';paused=false;left=config.max;interval=left;}else paused=!paused;addChange(paused?'Administrator · colectare pusă pe pauză.':'Administrator · colectare reluată.');renderState();toast(paused?'Colectarea simulată este pe pauză.':'Colectarea simulată se reia după pauza afișată.');};
$$('.stream-toggle').forEach(b=>b.onclick=()=>{const s=b.closest('.stream'),key=s.dataset.stream;if(pausedStreams.has(key))pausedStreams.delete(key);else pausedStreams.add(key);renderState();addChange(`${s.querySelector('h3').textContent} · ${pausedStreams.has(key)?'pus pe pauză':'reluat'}.`);});
$('#scenario').onchange=e=>{mode=e.target.value;paused=false;left=41;interval=60;renderState();edit();};
$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderLog();});
$('#log-rows').onclick=e=>{const b=e.target.closest('.log-toggle');if(!b)return;const row=$(`#detail-${b.dataset.id}`),open=b.getAttribute('aria-expanded')==='true';row.hidden=open;b.setAttribute('aria-expanded',String(!open));};
$('#export').onclick=()=>{const data={demonstration:true,sourceRequestsSent:0,config,requests:logs};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jurnal-colectare-SIMULARE.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Jurnalul demonstrativ a fost exportat.');};
$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('#theme').setAttribute('aria-label',dark?'Activează tema luminoasă':'Activează tema întunecată');};
$('#reset').onclick=()=>location.reload();
setInterval(()=>{if(mode!=='live'||paused||!activeKind()||config.daily&&requestCount>=config.limit)return;if(document.hidden)return;left--;if(left<=0){const kind=activeKind();requestCount++;successCount++;recordCount+=128;queueCount=Math.max(0,queueCount-1);interval=Math.floor(config.min+Math.random()*(config.max-config.min+1));left=interval;logs.unshift({id:sequence++,time:new Date().toLocaleTimeString('ro-RO',{timeZone:'Europe/Bucharest'}),kind,title:{da:'Achiziții directe',tenders:'Anunțuri de participare',awards:'Anunțuri de atribuire'}[kind],context:'Răspuns simulat · 128 înregistrări salvate',status:200,result:'128 înregistrări',duration:'0,9 s',method:'POST'});renderLog();}renderState();},1000);
fillForm();renderLog();renderState();
