import {mkdir,writeFile} from 'node:fs/promises';
const out='docs/implementation/previews/admin-collection';await mkdir(out,{recursive:true});
const target=await(await fetch('http://127.0.0.1:9237/json/new?about:blank',{method:'PUT'})).json();
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let serial=0;const pending=new Map(),checks=[],errors=[],external=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Network.requestWillBeSent'&&/^https?:/.test(m.params.request.url)&&!/^http:\/\/(127\.0\.0\.1|localhost):/.test(m.params.request.url))external.push(m.params.request.url)};
const cmd=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
const ev=async expression=>{const r=await cmd('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
const pause=ms=>new Promise(r=>setTimeout(r,ms)),assert=(x,label)=>{if(!x)throw Error(label);checks.push(label)};
const click=s=>ev(`document.querySelector(${JSON.stringify(s)}).click()`);
const scenario=async value=>{await ev(`document.querySelector('#scenario').value=${JSON.stringify(value)};document.querySelector('#scenario').dispatchEvent(new Event('change'))`);};
async function width(w){await cmd('Emulation.setDeviceMetricsOverride',{width:w,height:1000,deviceScaleFactor:1,mobile:false});await pause(100);assert(await ev('document.documentElement.scrollWidth<=innerWidth'),'No page overflow at '+w)}
async function shot(name){await ev("document.querySelector('#toast').hidden=true");await ev('document.fonts.ready');await ev('scrollTo(0,0)');await pause(120);const {cssContentSize:s}=await cmd('Page.getLayoutMetrics');const r=await cmd('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:s.width,height:s.height,scale:1}});await writeFile(`${out}/${name}.png`,Buffer.from(r.data,'base64'));}
try{await cmd('Runtime.enable');await cmd('Network.enable');await cmd('Page.enable');await cmd('Page.navigate',{url:'http://127.0.0.1:3112/admin/'});await pause(500);await width(1440);await shot('desktop');await width(390);await shot('mobile');await width(320);await width(768);await width(1440);
 assert(await ev("document.querySelector('#state-title').textContent.includes('Colectăm')"),'Active initial state');await click('#pause');assert(await ev("document.querySelector('#state-title').textContent.includes('pauză')"),'Pause collector');await click('#pause');
 await click('[data-min="90"]');assert(await ev("document.querySelector('#rate-estimate').textContent.includes('34')&&document.querySelector('#active-delay').textContent.includes('50–70')"),'Draft rate changes without modifying active policy');await click('#apply');assert(await ev("document.querySelector('#active-delay').textContent.includes('90–120')&&document.querySelector('#changes').children.length===4"),'Apply policy records an audit event');
 await ev("document.querySelector('#delay-min').value=200;document.querySelector('#delay-min').dispatchEvent(new Event('input',{bubbles:true}))");assert(await ev("document.querySelector('#apply').disabled&&!document.querySelector('#settings-error').hidden"),'Invalid interval blocked with explanation');await click('#discard');
 await click('#daily-enabled');await ev("document.querySelector('#daily-limit').value=100;document.querySelector('#daily-limit').dispatchEvent(new Event('input',{bubbles:true}))");await click('#apply');assert(await ev("document.querySelector('#state-title').textContent.includes('Limita zilnică')"),'Daily cap stops simulated requests');await click('#daily-enabled');await click('#apply');
 await click('[data-stream="da"] .stream-toggle');assert(await ev("document.querySelector('#task-name').textContent.includes('Participare')"),'Pausing a stream selects another');await click('[data-stream="da"] .stream-toggle');
 await click('[data-filter="errors"]');assert(await ev("document.querySelectorAll('#log-rows .log-toggle').length===3"),'Error filter includes all three failed attempts');await click('.log-toggle');assert(await ev("document.querySelector('.log-toggle').getAttribute('aria-expanded')==='true'&&!document.querySelector('.log-detail').hidden"),'Request details expand inline');await click('[data-filter="all"]');
 await scenario('blocked');await shot('blocked');assert(await ev("document.querySelector('#status-notice').textContent.includes('Retry-After')"),'429 state explains global stop');await click('#pause');assert(await ev("document.querySelector('#scenario').value==='live'"),'Explicit resume works in simulation');
 await scenario('maintenance');assert(await ev("document.querySelector('#pause').disabled&&document.querySelector('#publication-badge').textContent==='În procesare'"),'Maintenance pauses collection');await scenario('failure');await shot('failed-publication');assert(await ev("document.querySelector('#status-notice').textContent.includes('nu redeschidem')"),'Failed publication keeps maintenance');
 await scenario('offline');assert(await ev("document.querySelector('#pause').disabled&&document.querySelector('#apply').disabled&&document.querySelector('#state-title').textContent.includes('statusul')"),'Stale status does not claim collector stopped');await scenario('live');await click('#theme');await shot('dark');await click('#theme');
 await click('[data-min="50"]');await click('#apply');await ev("document.querySelector('#toast').hidden=true");await shot('desktop');await width(390);await shot('mobile');await width(1440);
 await cmd('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert(await ev("getComputedStyle(document.querySelector('#countdown-fill')).transitionDuration==='0s'"),'Reduced motion supported');
 assert(errors.length===0,'No runtime exceptions');assert(external.length===0,'No external HTTP requests');await writeFile(out+'/verification.json',JSON.stringify({checks,errors,externalRequests:external,scope:'Standalone simulated mock-up; no backend or SEAP integration'},null,2));console.log(JSON.stringify({checks:checks.length,errors,externalRequests:external}));
}finally{ws.close();}
