"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import type { PatternRow, RxData } from "@/lib/radiografie";
import { lotColumns, fold, rxDate } from "@/lib/radiografie-view";
import { shortName } from "@/lib/radiografie-fmt";
import { formatRon } from "@/lib/format";
import RadiografieSources, { LotSources } from "./RadiografieSources";
const KIND: Record<PatternRow["kind"], string> = { rotatie: "Câștigători care reapar împreună", impartire: "Împărțire repetată între câștigători", maturare: "Același câștigător în toate loturile", consortiu: "Asociere repetată" };
export default function LotMatrix({ families, patterns, familiesWithLots, familiesTotal, authorityId }: {
    families: RxData["families"];
    patterns: PatternRow[];
    familiesWithLots: number;
    familiesTotal: number;
    authorityId: string;
}) {
    const options = Object.keys(families).sort((a, b) => families[b]!.rows.length - families[a]!.rows.length), [family, setFamily] = useState(options[0] ?? ""), [query, setQuery] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [page, setPage] = useState(0), [selection, setSelection] = useState<{
        notice: string;
        winner: string;
    } | null>(null), [sources, setSources] = useState(false), [pattern, setPattern] = useState<PatternRow | null>(null), [patternPage, setPatternPage] = useState(0);
    const rows = families[family]?.rows ?? [], years = [...new Set(rows.map(r => r.d.slice(0, 4)).filter(y => /^\d{4}$/.test(y)))].sort();
    const all = useMemo(() => lotColumns(rows, from ? Number(from) : undefined, to ? Number(to) : undefined), [rows, from, to]);
    const currentPage = Math.min(page, Math.max(0, Math.ceil(all.length / 8) - 1)), columns = all.slice(currentPage * 8, currentPage * 8 + 8), winners = [...new Map(columns.flatMap(c => [...c.cells.entries()])).values()];
    const column = columns.find(c => c.notice === selection?.notice && c.cells.has(selection.winner)) ?? columns[0], cell = (column && selection ? column.cells.get(selection.winner) : undefined) ?? column?.cells.values().next().value;
    const pats = patterns.filter(p => p.cpvClass === family), patPage = Math.min(patternPage, Math.max(0, Math.ceil(pats.length / 5) - 1));
    function reset() { setPage(0); setSelection(null); }
    if (!options.length)
        return <div className="rv-empty"><h2>Niciun tipar repetat de loturi în datele disponibile</h2><p>{familiesWithLots} clase cu proceduri de cel puțin trei contracte, din {familiesTotal} clase CPV. Lipsa unui tipar nu confirmă absența unei probleme.</p></div>;
    return <><div className="rv-toolbar"><label>Domeniul CPV<input aria-label="Caută un domeniu CPV" type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Caută un domeniu…"/><select aria-label="Domeniul CPV" value={family} onChange={e => { setFamily(e.target.value); setFrom(""); setTo(""); setQuery(""); setPatternPage(0); reset(); }}>{options.filter(k => k === family || fold(`${k} ${families[k]!.name}`).includes(fold(query))).map(k => <option key={k} value={k}>{families[k]!.name} · {k}</option>)}</select>{query && !options.some(k => fold(`${k} ${families[k]!.name}`).includes(fold(query))) && <small>Niciun domeniu găsit. Se păstrează selecția actuală.</small>}</label><div className="rv-period"><label>Din anul<select aria-label="Din anul" value={from} onChange={e => { setFrom(e.target.value); reset(); }}><option value="">Toți anii</option>{years.map(y => <option key={y}>{y}</option>)}</select></label><label>Până în anul<select aria-label="Până în anul" value={to} onChange={e => { setTo(e.target.value); reset(); }}><option value="">Toți anii</option>{years.map(y => <option key={y}>{y}</option>)}</select></label></div></div>
 <section className="rv-workspace"><div className="rv-workspace-heading"><h2>Cine câștigă loturile?</h2><p>{families[family]?.name} · {all.length} proceduri cu cel puțin trei contracte în interval. Asocierile apar împreună.</p></div>
 {all.length === 0 ? <div className="rv-empty"><p>{from && to && Number(from) > Number(to) ? "Anul de început trebuie să fie anterior sau egal cu anul de sfârșit." : "Nicio procedură în intervalul ales."}</p><button onClick={() => { setFrom(""); setTo(""); reset(); }}>Vezi toți anii</button></div> : <><div className="rv-matrix-wrap"><p className="rv-small">Verde închis: toate contractele procedurii. Fracția arată contractele câștigate / totalul.</p><div className="rv-matrix-scroll" role="region" tabIndex={0} aria-label="Matricea loturilor, derulare orizontală"><table className="rv-matrix"><thead><tr><th scope="col">Furnizor / asociere</th>{columns.map(c => <th scope="col" key={c.notice}>{rxDate(c.date)}<small>{c.notice}</small><small>{c.contracts.length} contracte</small></th>)}</tr></thead><tbody>{winners.map(w => <tr key={w.key}><th scope="row">{w.names.map(shortName).join(" + ")}{w.ids.length > 1 && <small>asociere</small>}</th>{columns.map(c => { const found = c.cells.get(w.key); return <td key={c.notice}>{found ? <button className={found.contracts.length === c.contracts.length ? "all" : ""} aria-pressed={column?.notice === c.notice && cell?.key === w.key} aria-label={`${w.names.join(" + ")} · ${c.notice} · ${found.contracts.length} din ${c.contracts.length} contracte`} onClick={() => setSelection({ notice: c.notice, winner: w.key })}>{found.contracts.length}/{c.contracts.length}</button> : <span aria-label="Niciun contract">—</span>}</td>; })}</tr>)}</tbody></table></div><nav className="rv-pager" aria-label="Paginarea procedurilor"><button disabled={currentPage === 0} onClick={() => { setPage(currentPage - 1); setSelection(null); }}>Anterior</button><span>Procedurile {currentPage * 8 + 1}–{Math.min(currentPage * 8 + 8, all.length)} din {all.length}</span><button disabled={(currentPage + 1) * 8 >= all.length} onClick={() => { setPage(currentPage + 1); setSelection(null); }}>Următor</button></nav></div>
 {cell && column && <div className="rv-matrix-selection" aria-live="polite"><div><h3>{cell.names.map(shortName).join(" + ")}</h3><p>{column.notice} · {cell.contracts.length} din {column.contracts.length} contracte · {formatRon(cell.contracts.reduce((a, r) => a + r.vFull, 0))}</p><p className="rv-small">Oferte cunoscute pentru {cell.contracts.filter(r => r.tr != null).length} din {cell.contracts.length} contracte. Detaliile sunt în surse.</p></div><button className="rv-primary" onClick={() => setSources(true)}>Verifică aceste contracte</button></div>}</>}
 </section><p className="rv-note">Contractele distincte dintr-un anunț reprezintă loturile în această vizualizare. Culoarea nu indică numărul ofertelor. Catalogul include cele {options.length} clase CPV cu tipare repetate detectate, din {familiesWithLots} clase cu loturi; nu este întregul catalog CPV.</p>
 <details className="rv-details rv-patterns"><summary>Tipare repetate în acest domeniu · {pats.length}</summary><p>Tiparele privesc întregul istoric disponibil, independent de intervalul matricei. Repetarea nu dovedește o înțelegere; asocierile sunt câștigători distincți de membrii lor.</p>{pats.slice(patPage * 5, patPage * 5 + 5).map(p => <article key={p.id}><h3>{KIND[p.kind]}</h3><p>{p.memberNames.join(" + ")}</p><p>{p.reps} repetări · {p.y0}–{p.y1} · {formatRon(p.value)} · {p.known ? `${p.single} loturi cu ofertant unic din ${p.known} cunoscute` : "Numărul ofertelor este necunoscut"}</p>{p.sharedAdmin && <p>Administrator comun în datele ONRC: {p.sharedAdmin}. Necesită verificare în documentele actuale.</p>}<button onClick={() => setPattern(p)}>Verifică sursele tiparului</button>{p.elsewhere.length > 0 && <details><summary>Același grup la alte {p.elsewhere.length} autorități</summary><ul>{p.elsewhere.map(a => <li key={a.authorityId}><Link href={`/entitati/${a.authorityId}`} target="_blank" rel="noopener">{a.authorityName}</Link> · {a.n} proceduri · {formatRon(a.value)} · {a.y0}–{a.y1}</li>)}</ul></details>}</article>)}{pats.length > 5 && <nav className="rv-pager" aria-label="Paginarea tiparelor"><button disabled={!patPage} onClick={() => setPatternPage(patPage - 1)}>Anterior</button><span>{patPage + 1} / {Math.ceil(pats.length / 5)}</span><button disabled={(patPage + 1) * 5 >= pats.length} onClick={() => setPatternPage(patPage + 1)}>Următor</button></nav>}</details>
 {sources && cell && <LotSources rows={cell.contracts} onClose={() => setSources(false)}/>}{pattern && <RadiografieSources authorityId={authorityId} pattern={pattern} onClose={() => setPattern(null)}/>}</>;
}
