import {afterAll,beforeEach,describe,it,expect} from 'vitest';
import {createDb,runCollectionRequest,CollectionSuspendedError,type DbSql} from '@seap/db';
import {changeCollection,collectionStatus} from './collection';
const url=process.env.TEST_DATABASE_URL;
if(url&&!/^seap_test_[a-z0-9_]+$/.test(new URL(url).pathname.slice(1)))throw Error('Dedicated test database required');
const connection=url?createDb(url):null;
afterAll(async()=>{await connection?.sql.end();});
const info={stream:'da' as const,worker:'fixture',method:'POST',url:'https://www.e-licitatie.ro/api-pub/DirectAcquisitionCommon/GetDirectAcquisitionList/',parameters:{pageSize:2000,Cookie:'must-not-log'}};
const actor={id:'fixture-admin',name:'Administrator de test'};
describe.skipIf(!connection)('admin collection control and global transport (isolated DB, no network)',()=>{
 let q:DbSql;
 beforeEach(async()=>{q=connection!.sql;await q`truncate app.collection_requests,app.collection_audit,app.collection_workers`;await q`insert into app.collection_control(id) values(1) on conflict do nothing`;await q`update app.collection_control set revision=1,min_seconds=1,max_seconds=1,daily_limit=null,processing_time='05:00',paused=false,paused_streams='[]',blocked_reason=null,blocked_until=null,next_allowed_at=null,last_file_at=null,maintenance=false where id=1`;});
 async function request(work:(signal:AbortSignal)=>Promise<any>=async()=>({value:'ok',status:200,records:2}),patch:Partial<typeof info>&{fileDownload?:boolean}={}){const c=await q.reserve();try{return await runCollectionRequest(c,{...info,...patch},work);}finally{c.release();}}
 it('serializes two workers and persists next request time across sessions',async()=>{let active=0,max=0;const starts:number[]=[];const work=async()=>{starts.push(Date.now());max=Math.max(max,++active);await new Promise(r=>setTimeout(r,200));active--;return {value:'ok',status:200};};await Promise.all([request(work),request(work)]);expect(max).toBe(1);expect(starts[1]!-starts[0]!).toBeGreaterThanOrEqual(1000);const rows=await q`select * from app.collection_requests`;expect(rows).toHaveLength(2);expect(rows.every(r=>r.outcome==='success')).toBe(true);expect(rows[0]!.parameters).toEqual({pageSize:2000});},10000);
 it('pause and maintenance stop before any attempt is counted',async()=>{for(const field of ['paused','maintenance']){await q`update app.collection_control set paused=${field==='paused'},maintenance=${field==='maintenance'}`;await expect(request()).rejects.toBeInstanceOf(CollectionSuspendedError);}expect((await q`select count(*)::int n from app.collection_requests`)[0]!.n).toBe(0);});
 it('stream pause does not permit its pending requests',async()=>{await q`update app.collection_control set paused_streams='["da"]'`;await expect(request()).rejects.toBeInstanceOf(CollectionSuspendedError);expect((await q`select count(*)::int n from app.collection_requests`)[0]!.n).toBe(0);});
 it('per-stream commands store JSON and audit both pause and resume',async()=>{await changeCollection(actor,{action:'stream',revision:1,stream:'da',paused:true},q);expect((await q`select paused_streams from app.collection_control`)[0]!.paused_streams).toEqual(['da']);await changeCollection(actor,{action:'stream',revision:2,stream:'da',paused:false},q);expect((await q`select paused_streams from app.collection_control`)[0]!.paused_streams).toEqual([]);expect((await q`select * from app.collection_audit`)).toHaveLength(2);});
 it('daily budget includes failed attempts',async()=>{await q`update app.collection_control set daily_limit=1`;await request(async()=>({value:'error',status:503}));await expect(request()).rejects.toThrow('Limita zilnică');const s=await collectionStatus(q);expect(s.today.attempts).toBe(1);expect(s.today.failed).toBe(1);});
 it('429 blocks all streams and respects Retry-After during manual resume',async()=>{await expect(request(async()=>({value:'error',status:429,retryAfter:'120'}))).rejects.toBeInstanceOf(CollectionSuspendedError);await expect(request(undefined,{stream:'documents' as 'da'})).rejects.toBeInstanceOf(CollectionSuspendedError);await expect(changeCollection(actor,{action:'unblock',acknowledged:true,revision:1},q)).rejects.toThrow('așteptare');expect((await q`select count(*)::int n from app.collection_requests`)[0]!.n).toBe(1);});
 it('interrupted workers fail closed without a replacement request',async()=>{await q`insert into app.collection_requests(stream,worker,method,endpoint) values('da','lost','POST','/api-pub/example')`;await expect(request()).rejects.toThrow('întreruptă');const [c]=await q`select blocked_reason,blocked_until from app.collection_control`;expect(c!.blocked_reason).toBeTruthy();expect(c!.blocked_until).toBeTruthy();expect((await q`select count(*)::int n from app.collection_requests`)[0]!.n).toBe(1);});
 it('settings are atomic, versioned and audited; a faster change does not shorten the pause',async()=>{await q`update app.collection_control set min_seconds=50,max_seconds=70,next_allowed_at=now()+interval '60 seconds'`;const [old]=await q`select next_allowed_at from app.collection_control`;await changeCollection(actor,{action:'settings',revision:1,minSeconds:10,maxSeconds:20,dailyLimit:1000,processingTime:'06:00'},q);const [c]=await q`select * from app.collection_control`;expect(c!.revision).toBe(2);expect(c!.next_allowed_at).toEqual(old!.next_allowed_at);await expect(changeCollection(actor,{action:'pause',revision:1,paused:true},q)).rejects.toThrow('între timp');expect((await q`select * from app.collection_audit`)).toHaveLength(1);});
 it('file retrieval retains the minimum sixty-second gap',async()=>{await q`update app.collection_control set last_file_at=clock_timestamp()-interval '59 seconds'`;const [before]=await q`select last_file_at from app.collection_control`;await request(undefined,{fileDownload:true});const [after]=await q`select last_file_at from app.collection_control`;expect(new Date(after!.last_file_at).getTime()-new Date(before!.last_file_at).getTime()).toBeGreaterThanOrEqual(60000);},10000);
 it('HTTP200 challenge blocks before later requests',async()=>{await expect(request(async()=>({value:'html',status:200,challenge:true}))).rejects.toThrow('verificare suplimentară');expect((await q`select outcome from app.collection_requests`)[0]!.outcome).toBe('failed');});
 it('transport exception is recorded and globally stops further attempts',async()=>{await expect(request(async()=>{throw Error('fixture private detail');})).rejects.toThrow();const [row]=await q`select * from app.collection_requests`;expect(row!.error).not.toContain('private');await expect(request()).rejects.toBeInstanceOf(CollectionSuspendedError);});
});
