import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {parseEnv} from 'node:util';
import {createHmac,randomUUID,randomBytes} from 'node:crypto';
import {chromium} from 'playwright-core';
import {createDb} from '@seap/db';
const url=process.env.TEST_DATABASE_URL;
if(!url||!/^seap_test_[a-z0-9_]+$/.test(new URL(url).pathname.slice(1)))throw Error('Dedicated test database required');
const base=process.env.ADMIN_TEST_BASE??'http://localhost:3115';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw Error('Local preview only');
const env=parseEnv(await readFile('.env.local','utf8')),secret=process.env.BETTER_AUTH_SECRET??env.BETTER_AUTH_SECRET;
if(!secret)throw Error('Local auth configuration missing');
const {sql:q}=createDb(url),browser=await chromium.connectOverCDP('http://localhost:9237');
const out='../../docs/implementation/previews/admin-collection-live';await mkdir(out,{recursive:true});
const checks:string[]=[],errors:string[]=[],external:string[]=[],users:string[]=[];
const assert=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label);};
async function context(role:string){const ctx=await browser.newContext(),user='admin-collection-'+randomUUID(),token=randomBytes(32).toString('hex');users.push(user);await q`insert into auth.users(id,name,email,email_verified,role) values(${user},'Verificare administrare',${user+'@example.test'},true,${role})`;await q`insert into auth.sessions(id,token,user_id,expires_at) values(${randomUUID()},${token},${user},now()+interval '1 hour')`;const signed=token+'.'+createHmac('sha256',secret!).update(token).digest('base64');await ctx.addCookies([{name:'better-auth.session_token',value:encodeURIComponent(signed),url:base}]);return ctx;}
const admin=await context('admin'),member=await context('watchdog'),anon=await browser.newContext();
const page=await admin.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!['localhost','127.0.0.1'].includes(new URL(r.url()).hostname))external.push(r.url());});
async function screenshot(name:string,width:number){await page.setViewportSize({width,height:1000});await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${out}/${name}.png`,fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No overflow at ${width}px`);}
try{
 await q`truncate app.collection_requests,app.collection_audit,app.collection_workers`;await q`insert into app.collection_control(id) values(1) on conflict do nothing`;await q`update app.collection_control set revision=1,min_seconds=50,max_seconds=70,daily_limit=null,processing_time='05:00',paused=true,paused_streams='[]',blocked_reason=null,blocked_until=null,next_allowed_at=null,last_file_at=null,maintenance=false where id=1`;
 assert((await anon.request.get(base+'/api/admin/collection')).status()===403,'Anonymous cannot read status');assert((await member.request.get(base+'/api/admin/collection')).status()===403,'Non-admin cannot read status');
 assert((await member.request.post(base+'/api/admin/collection',{data:{action:'pause',paused:false,revision:1},headers:{Origin:base}})).status()===403,'Non-admin cannot change controls');
 assert((await admin.request.post(base+'/api/admin/collection',{data:{action:'pause',paused:false,revision:1},headers:{Origin:'https://example.invalid'}})).status()===403,'Cross-origin mutation rejected');
 await page.goto(base+'/admin');await page.getByText('Setările sunt la zi',{exact:true}).waitFor();await screenshot('empty-desktop',1440);
 assert(await page.getByText('Nu există încă cereri în noul jurnal.',{exact:false}).isVisible(),'Empty journal is truthful');
 await page.locator('#delay-min').fill('90');await page.locator('#delay-max').fill('120');assert(await page.getByText('≈ 34 cereri / oră').isVisible(),'Draft displays new hourly estimate');assert(await page.getByText('Interval aleator: 50–70 sec').isVisible(),'Draft does not change active policy');await page.locator('#apply').click();await page.getByText('Interval aleator: 90–120 sec').waitFor();await page.reload();await page.getByText('Interval aleator: 90–120 sec').waitFor();assert(await page.locator('#delay-min').inputValue()==='90','Policy persists across reload');
 let data=await(await admin.request.get(base+'/api/admin/collection')).json();assert(data.audit.length===1&&data.audit[0].actor_name==='Verificare administrare','Settings audit retains actor');
 assert((await admin.request.post(base+'/api/admin/collection',{data:{action:'pause',paused:false,revision:1},headers:{Origin:base}})).status()===409,'Outdated revision rejected');
 await page.locator('#delay-min').fill('120');await page.locator('#delay-max').fill('180');await page.locator('#maintenance-time').fill('06:00');
 await page.locator('#pause').click();await page.getByText('Colectorul nu este pornit.',{exact:true}).waitFor();assert(true,'Resume without worker does not claim live collection');assert(await page.locator('#delay-min').inputValue()==='120'&&await page.locator('#maintenance-time').inputValue()==='06:00','Global pause/resume preserves unapplied draft');
 const streamReply=page.waitForResponse(r=>r.url().endsWith('/api/admin/collection')&&r.request().method()==='POST');await page.locator('[aria-label="Pune pe pauză Achiziții directe"]').click();const streamResponse=await streamReply;if(streamResponse.status()!==200)throw Error('Stream control: '+await streamResponse.text());await page.locator('[aria-label="Reia Achiziții directe"]').waitFor();assert(true,'Per-stream control persists');assert(await page.locator('#delay-max').inputValue()==='180'&&await page.locator('#maintenance-time').inputValue()==='06:00','Stream control preserves unapplied draft');assert(await page.locator('#apply').isEnabled(),'Own pause revisions do not invalidate draft');await page.locator('#apply').click();await page.getByText('Interval aleator: 120–180 sec').waitFor();assert(await page.locator('#publish-time').textContent()==='06:00','Preserved draft applies successfully');
 await page.locator('#delay-min').fill('150');data=await(await admin.request.get(base+'/api/admin/collection')).json();const competing=await admin.request.post(base+'/api/admin/collection',{data:{action:'settings',revision:data.control.revision,minSeconds:120,maxSeconds:180,dailyLimit:null,processingTime:'05:00'},headers:{Origin:base}});assert(competing.status()===200,'Second administrator change accepted at latest revision');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.getByText('Alt administrator a modificat setările.',{exact:false}).waitFor();assert(await page.locator('#delay-min').inputValue()==='150'&&await page.locator('#apply').isDisabled(),'Competing change preserves draft and blocks overwrite');await page.getByRole('button',{name:'Reîncarcă setările salvate'}).click();assert(await page.locator('#delay-min').inputValue()==='120'&&await page.locator('#maintenance-time').inputValue()==='05:00','Explicit reload adopts competing settings');
 await q`insert into app.collection_workers(id,kind,state) values('test-browser','ingestion','waiting')`;
 await q`insert into app.collection_requests(stream,worker,method,endpoint,parameters,status,outcome,records,bytes,started_at,finished_at) values('da','test-browser','POST','/api-pub/DirectAcquisitionCommon/GetDirectAcquisitionList/','{"pageSize":2000,"pageIndex":0}',200,'success',128,12000,now()-interval '70 seconds',now()-interval '69 seconds'),('awards','test-browser','POST','/api-pub/NoticeCommon/GetCANoticeList/','{"pageSize":100}',503,'failed',null,200,now()-interval '140 seconds',now()-interval '139 seconds')`;
 await page.reload();await page.getByText('Coada SEAP este pregătită.').waitFor();await page.getByRole('button',{name:'Erori',exact:true}).click();assert(await page.locator('.log-toggle').count()===1,'Error filter reflects real ledger');await page.locator('.log-toggle').click();assert(await page.locator('.log-detail code').textContent()==='/api-pub/NoticeCommon/GetCANoticeList/','Request details expose actual endpoint');await page.getByRole('button',{name:'Toate',exact:true}).click();
 const exported=await admin.request.get(base+'/api/admin/collection?export=1');const exportedData=await exported.json();assert(exported.status()===200&&exportedData.requests.length===2,'Authenticated export contains ledger rows');assert((await anon.request.get(base+'/api/admin/collection?export=1')).status()===403,'Anonymous export denied');
 await screenshot('desktop',1440);await screenshot('mobile',390);await screenshot('narrow',320);await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await screenshot('dark',1440);await page.evaluate(()=>document.documentElement.dataset.theme='light');
 await q`update app.collection_control set blocked_reason='SEAP a răspuns cu 429.',blocked_until=now()+interval '60 seconds'`;await page.reload();await page.getByText('Colectarea așteaptă verificarea sursei.').waitFor();await page.getByRole('button',{name:'Verifică și reia'}).click();await page.getByRole('checkbox',{name:/Am verificat/}).check();assert(await page.getByRole('button',{name:'Confirmă reluarea'}).isDisabled(),'UI respects Retry-After');await screenshot('blocked',1440);
 await q`update app.collection_control set maintenance=true,blocked_reason=null,blocked_until=null`;
 assert((await anon.request.get(base+'/metodologie')).status()===503,'Public pages gated during maintenance');assert((await anon.request.get(base+'/api/documents/not-a-real-id')).status()===503,'Public API gated during maintenance');assert((await admin.request.get(base+'/api/admin/collection')).status()===200,'Admin status remains available during maintenance');assert((await anon.request.get(base+'/api/health')).status()===200,'Health independent of publication availability');await page.reload();await page.getByText('Site-ul este în mentenanță.').waitFor();assert(await page.locator('#pause').isDisabled(),'Maintenance cannot be bypassed with resume');await screenshot('maintenance-admin',1440);
 await q`update app.collection_control set maintenance=false`;
 await page.reload();await page.getByText('Coada SEAP este pregătită.').waitFor();await page.route('**/api/admin/collection',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"test offline"}'}));await page.getByText('Nu mai primim statusul serverului.').waitFor({timeout:15000});assert(await page.locator('#pause').isDisabled(),'Stale connection disables commands');assert(await page.locator('#countdown').textContent()==='—'&&await page.getByText('Stare necunoscută',{exact:true}).isVisible(),'Reporting loss does not claim stopped requests');await screenshot('offline',1440);await page.unroute('**/api/admin/collection');
 assert(errors.length===0,'No browser runtime errors');assert(external.length===0,'No external requests');await writeFile(`${out}/verification.json`,JSON.stringify({checks,errors,externalRequests:external,scope:'Isolated seap_test_collection database; synthetic private account and request fixtures, no actual SEAP traffic'},null,2));console.log(JSON.stringify({checks:checks.length,errors,externalRequests:external}));
}finally{await q`update app.collection_control set maintenance=false,paused=true`;for(const u of users)await q`delete from auth.users where id=${u}`;await admin.close();await member.close();await anon.close();await browser.close();await q.end();}
