import { TYPES } from './metadata.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>new Intl.NumberFormat('ro-RO',{maximumFractionDigits:2}).format(n);
const money=n=>new Intl.NumberFormat('ro-RO',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' lei';
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${{moon:'<path d="M20 14a8 8 0 0 1-10-10 8 8 0 1 0 10 10Z"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',left:'<path d="m14 5-7 7 7 7"/>',right:'<path d="m10 5 7 7-7 7"/>'}[name]}</svg>`;
const groups=[['Praguri și calendar',['da_split','da_round','da_rapid','da_year_end']],['Concentrarea achizițiilor',['da_concentration','da_dependence','award_concentration','award_dependence']],['Proceduri și oferte',['award_no_competition','award_single_bid']],['Firme și legături',['fin_tiny_staff','fin_public_reliance','net_shared_admin']]];
const criteria={authority:['Posibilă fracționare sub prag','Concentrare pe un furnizor','Achiziții concentrate în decembrie','Finalizare rapidă','Valoare aproape de prag'],supplier:['Posibilă fracționare sub prag','Dependență de o autoritate','Finalizare rapidă','Valoare aproape de prag']};
const q=new URLSearchParams(location.search);
const state={code:TYPES.some(t=>t.code===q.get('tip'))?q.get('tip'):'da_split',role:q.get('rol')==='supplier'?'supplier':'authority',county:['Alba','Buzău','Cluj','Ilfov'].includes(q.get('jud'))?q.get('jud'):'',page:Math.max(0,Number(q.get('p'))||0),view:q.get('view')==='cri'?'cri':'signals',open:null,scenario:'normal',band:q.has('cri')?Number(q.get('cri')):null,sort:q.get('sort')==='name'?'name':'cri',sourcePage:0};
const viewMemory={signals:{page:state.page,role:state.role,county:state.county},cri:{page:0,role:state.role,county:state.county,band:state.band}};
const places=['Valea Frasinului','Poiana Cerbului','Lunca Stejarului','Dealul Mierlei','Izvorul Alb','Câmpul Soarelui','Valea Teiului','Poiana Salciei'];
const firms=['Atelierul Civic SRL','Drumuri de Mâine SRL','Lumina Satului SRL','Proiect Local SRL','Materiale și Lucrări SRL','Servicii pentru Comunitate SRL'];
const counties=['Buzău','Cluj','Alba','Ilfov'];
const fixtures=Array.from({length:32},(_,i)=>({id:i,authority:`Comuna ${places[i%8]}${['',' de Sus',' de Jos',' Nouă'][Math.floor(i/8)]}`,supplier:firms[i%6].replace(' SRL','')+' '+places[Math.floor(i/6)]+' SRL',county:counties[i%4],supplierCounty:counties[(i+1)%4],year:2025-i%4,n:8+i%7,total:Math.round((1845600-i*19170)*100)/100,cpv:'4523',ceiling:900400,criteria:i%6}));
const meta=()=>TYPES.find(t=>t.code===state.code);
function syncRole(){const wanted=meta().subject;if(['authority','supplier'].includes(wanted)&&state.view==='signals'&&wanted!==state.role){state.role=wanted;$('#role-message').textContent=`Acest semnal se calculează pentru ${wanted==='supplier'?'firme':'autorități'}. Selecția a fost actualizată.`;return true}return false}
function setUrl(){const u=new URLSearchParams({tip:state.code,rol:state.role});if(state.county)u.set('jud',state.county);if(state.page)u.set('p',state.page);if(state.view==='cri'){u.set('view','cri');if(state.band!==null)u.set('cri',state.band);if(state.sort==='name')u.set('sort','name')}if(location.search!=='?'+u)history.pushState(null,'','?'+u)}
function subset(){if(state.scenario==='empty')return [];return fixtures.filter(r=>!state.county||(state.role==='authority'?r.county:r.supplierCounty)===state.county)}
function metrics(r){const c=state.code;let total=r.total,obs='',note='',period=String(r.year),count=r.n;
 if(c==='da_split'){obs=`${r.n} achiziții sub prag, ${number(r.total)} lei cumulat`;note=`Aceeași clasă CPV ${r.cpv} · plafon de referință ${number(r.ceiling)} lei`}
 if(c==='da_round'){total=270119-r.id*170;count=1;obs=`Cu ${number(270120-total)} lei sub plafon`;note='Plafon de referință: 270.120 lei · produse / servicii'}
 if(c==='da_rapid'){count=1;total=38000+r.id*1300;obs=`Finalizată în ${3+r.id%8} minute`;note='Interval între publicare și finalizare în SEAP'}
 if(c==='da_year_end'){obs=`${42+r.id%21}% din valoarea anuală, în decembrie`;note='Pondere în achizițiile directe finalizate'}
 if(c.includes('concentration')){period='Întreaga perioadă';obs=`${73+r.id%20}% din valoare la un furnizor`;note=c.startsWith('award')?'Contracte prin proceduri · cote estimate pentru consorții':'Achiziții directe · arhiva disponibilă'}
 if(c.includes('dependence')){period='Întreaga perioadă';obs=`${76+r.id%20}% din valoare de la o autoritate`;note=c.startsWith('award')?'Contracte prin proceduri, nu venituri încasate':'Achiziții directe, nu toate veniturile firmei'}
 if(c==='award_no_competition'){total=r.total+2500000;count=1;obs='Negociere fără publicare prealabilă';note='Motivul alegerii procedurii trebuie verificat'}
 if(c==='award_single_bid'){total=r.total+2500000;count=2;obs='1 ofertă raportată la un lot TED';note='Observația privește lotul identificat; valoarea este a anunțului'}
 if(c==='fin_tiny_staff'){total=r.total+2200000;obs=`${r.id%5+1} salariați · ${number(total)} lei în achiziții`;note='Număr mediu din bilanțul aceluiași an'}
 if(c==='fin_public_reliance'){period='Întreaga perioadă';obs=`${82+r.id%40}% față de cifra de afaceri`;note='Valori înregistrate, nu încasări din contracte'}
 if(c==='net_shared_admin'){period='Întreaga perioadă';count=2;obs='2 firme cu un reprezentant legal comun';note='Achiziții la aceeași autoritate · situația ONRC disponibilă'}
 return {total,obs,note,period,count,label:c.startsWith('award_')&&meta().subject==='award'?'valoarea anunțului':'valoare înregistrată'};
}
function rows(){let a=subset();if(state.view==='signals')return a.sort((x,y)=>metrics(y).total-metrics(x).total||x.id-y.id);const n=criteria[state.role].length;a=a.map(r=>({...r,score:r.criteria%(n+1)})).filter(r=>state.band===null||r.score===state.band);return a.sort(state.sort==='name'?(a,b)=>entity(a).localeCompare(entity(b),'ro'):(a,b)=>b.score-a.score||a.id-b.id)}
const entity=r=>state.role==='authority'?r.authority:r.supplier;
const county=r=>state.role==='authority'?r.county:r.supplierCounty;
function pager(total){const pages=Math.max(1,Math.ceil(total/10));return `<nav class="pager" aria-label="Pagini de rezultate"><button class="page-arrow" data-page="${state.page-1}" aria-label="Pagina anterioară" ${state.page===0?'disabled':''}>${icon('left')}</button>${Array.from({length:pages},(_,i)=>`<button data-page="${i}" class="${i===state.page?'selected':''}" ${i===state.page?'aria-current="page"':''}>${i+1}</button>`).join('')}<button class="page-arrow" data-page="${state.page+1}" aria-label="Pagina următoare" ${state.page===pages-1?'disabled':''}>${icon('right')}</button></nav>`}
function toolbar(total,bottom=false){return `<div class="results-toolbar ${bottom?'bottom-toolbar':''}"><div class="result-total"><strong>${total?state.page*10+1:0}–${Math.min(total,(state.page+1)*10)}</strong> din ${total} ${state.view==='cri'?'entități':'apariții'}<span>${state.view==='cri'?'Minimum 10 achiziții directe':'După valoare · date demonstrative'}</span></div>${pager(total)}</div>`}
function sourceButton(id,cls='source-link',label='Înregistrările sursă'){return `<button class="${cls}" data-source="${id}">${label}</button>`}
function inline(r){const m=metrics(r);return `<div class="expanded" id="explanation-${r.id}"><div class="detail-grid"><div><h3>Ce a declanșat semnalul</h3><p>${esc(m.obs)}. ${esc(m.note)}.</p><p style="margin-top:10px">${esc(meta().description)}</p></div><div><h3>Ce merită verificat</h3><p>${esc(state.code==='da_split'?'Verifică dacă achizițiile răspund aceleiași nevoi, cum a fost estimată valoarea și dacă documentele explică achizițiile separate.':meta().rationale)}</p><p style="margin-top:10px">${esc(state.code==='da_split'?'O clasă CPV comună nu dovedește o nevoie unică; achizițiile recurente pot fi legitime.':meta().caveat.split('. ')[0]+'.')}</p><details class="detail-limits"><summary>Limitele acestui semnal</summary><p>${esc(meta().caveat)}</p></details></div></div><div class="detail-footer"><small>Perioada calculului: ${m.period}.<br>Exemplu fictiv, fără constatări despre entități reale.</small>${sourceButton(r.id,'primary','Vezi înregistrările sursă')}</div></div>`}
function signalRow(r){const m=metrics(r),isOpen=state.open===r.id;const partner=state.role==='authority'?r.supplier:r.authority;return `<article class="result"><div class="result-row"><div class="entity"><div class="entity-name">${esc(entity(r))}</div><div class="partner">${state.role==='authority'?'Furnizor':'Autoritate'}: ${esc(partner)}</div><div class="meta"><span>${county(r)}</span><span>${m.period}</span></div></div><div class="observation">${esc(m.obs)}<small>${esc(m.note)}</small></div><div class="amount"><strong>${money(m.total)}</strong><small>${m.label}</small></div><div class="row-actions"><button class="verify" data-expand="${r.id}" aria-expanded="${isOpen}" ${isOpen?`aria-controls="explanation-${r.id}"`:''}>${isOpen?'Închide':'Verifică'}<span class="chevron"></span></button>${sourceButton(r.id)}</div></div>${isOpen?inline(r):''}</article>`}
function criRow(r){const n=criteria[state.role].length,isOpen=state.open===r.id;return `<article class="result"><div class="result-row cri-row"><div class="entity"><div class="entity-name">${esc(entity(r))}</div><div class="meta"><span>${county(r)}</span><span>Întreaga perioadă disponibilă</span></div></div><div class="observation"><div class="cri-label"><strong>${(r.score/n).toFixed(2).replace('.',',')}</strong> CRI</div><div class="criteria">${r.score} din ${n} criterii îndeplinite</div></div><div class="amount"><strong>${40+r.id*7}</strong><small>achiziții directe</small></div><div class="row-actions"><button class="verify" data-expand="${r.id}" aria-expanded="${isOpen}">${isOpen?'Închide':'Criterii'}<span class="chevron"></span></button></div></div>${isOpen?`<div class="expanded"><h3>Criteriile acestui exemplu</h3><p>${criteria[state.role].map((c,i)=>`${i<r.score?'Îndeplinit':'Neîndeplinit'}: ${c}`).join('<br>')}</p><p style="margin-top:12px">Criteriile ilustrate sunt fictive. Scorul nu include toate cele 13 tipuri de semnale și nu exprimă o probabilitate de corupție.</p><div class="detail-footer"><a href="http://localhost:3000/metodologie#indice" target="_blank" rel="noopener">Cum se calculează CRI ↗</a></div></div>`:''}</article>`}
function renderContext(){if(state.view==='signals'){$('#context').innerHTML=`<div class="context-heading"><div><h2>${meta().title}</h2><p>${meta().short}</p></div><a href="http://localhost:3000/metodologie#${state.code}" target="_blank" rel="noopener">Criterii și limite ↗</a></div>`;return}
 const n=criteria[state.role].length,eligible=subset(),counts=Array.from({length:n+1},(_,i)=>eligible.filter(r=>r.criteria%(n+1)===i).length),max=Math.max(...counts,1);
 $('#context').innerHTML=`<div class="context-heading"><div><h2>Câte criterii apar împreună?</h2><p>CRI sintetizează ${n} criterii din achizițiile directe. Nu este o probabilitate de corupție.</p></div><a href="http://localhost:3000/metodologie#indice" target="_blank" rel="noopener">Cum se calculează ↗</a></div><div class="cri-overview"><div><h3>${eligible.length} ${state.role==='authority'?'autorități':'firme'} în exemplu</h3><p>Minimum 10 achiziții directe. Întreaga perioadă disponibilă la calcul. Selectează o bară pentru a restrânge lista.</p></div><div class="histogram" aria-label="Distribuția criteriilor CRI">${counts.map((v,i)=>`<button data-band="${i}" class="${state.band===i?'selected':''}" aria-pressed="${state.band===i}" aria-label="${i} din ${n} criterii, ${v} entități"><span>${v}</span><span class="bar" style="height:${v/max*65}px"></span><span>${i}/${n}</span></button>`).join('')}</div></div><div class="cri-controls"><span>${state.band===null?'Toate valorile CRI':`${state.band} din ${n} criterii · <button id="reset-band">Arată toate</button>`}</span><label>Ordonează <select id="cri-sort"><option value="cri">După CRI</option><option value="name">După nume</option></select></label></div>`;$('#cri-sort').value=state.sort;
}
function syncControls(){syncRole();$('#selected-type').textContent=meta().title;$$('[data-role]').forEach(b=>{b.classList.toggle('selected',b.dataset.role===state.role);b.setAttribute('aria-pressed',b.dataset.role===state.role)});$('#county-label').textContent=state.role==='authority'?'Județul autorității':'Județul firmei';$('#county').value=state.county;$$('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view===state.view);if(b.dataset.view===state.view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('.type-field').hidden=state.view==='cri';$('#filter-count').textContent=state.county?'1':'';setUrl()}
function renderResults(){const all=rows();state.page=Math.min(state.page,Math.max(0,Math.ceil(all.length/10)-1));setUrl();if(state.scenario==='error'){$('#results-body').innerHTML='<div class="state-message" role="alert"><h3>Rezultatele nu s-au încărcat</h3><p>Selecția ta este păstrată. Încearcă din nou pentru a vedea lista.</p><button class="primary" id="retry">Reîncearcă</button></div>';return}if(!all.length){$('#results-body').innerHTML='<div class="state-message"><h3>Nicio apariție pentru această selecție</h3><p>În acest exemplu nu există rezultate care să corespundă filtrelor. Poți extinde căutarea la toate județele.</p><button class="primary" id="reset-filters">Resetează filtrele</button></div>';return}
 const cri=state.view==='cri';$('#results-body').innerHTML=toolbar(all.length)+`<div class="list-head" aria-hidden="true"><span>${state.role==='authority'?'AUTORITATE':'FIRMĂ'}${cri?'':' ȘI PARTENER'}</span><span>${cri?'INDICE ȘI CRITERII':'OBSERVAȚIA DIN DATE'}</span><span>${cri?'ACHIZIȚII DIRECTE':'VALOARE · LEI'}</span><span></span></div>`+all.slice(state.page*10,state.page*10+10).map(cri?criRow:signalRow).join('')+toolbar(all.length,true);$('#status').textContent=`${all.length} ${cri?'entități':'apariții'}. Pagina ${state.page+1}.`;
}
let loadId=0;function update({loading=true,scroll=false}={}){const id=++loadId;syncControls();renderContext();if(!loading){renderResults();return}$('#results').setAttribute('aria-busy','true');$('#status').textContent='Se încarcă rezultatele…';$('#results-body').innerHTML='<div class="loading-strip"><span class="spinner" aria-hidden="true"></span>Se încarcă rezultatele…</div>'+Array.from({length:10},()=>'<div class="skeleton" aria-hidden="true"><span></span><span></span><span></span></div>').join('');setTimeout(()=>{if(id!==loadId)return;$('#results').removeAttribute('aria-busy');renderResults();if(scroll){$('#results').scrollIntoView({block:'start'});$('#results').focus({preventScroll:true})}},380)}
function chooseType(){const query=$('#type-search').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let html='';for(const [group,codes] of groups){const matches=codes.map(c=>TYPES.find(t=>t.code===c)).filter(t=>(t.title+' '+t.short).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query));if(!matches.length)continue;html+=`<p class="option-group">${group}</p>`+matches.map(t=>`<button class="type-option" data-type="${t.code}" aria-pressed="${state.code===t.code}"><strong>${t.title}</strong><small>${t.subject==='supplier'?'Firme':t.subject==='authority'?'Autorități':'Autorități și firme'} · ${t.code.startsWith('da_')?'achiziții directe':t.code.startsWith('award_')?'proceduri':t.code.startsWith('fin_')?'achiziții și bilanțuri':'achiziții și ONRC'}</small></button>`).join('')};$('#type-options').innerHTML=html||'<p class="option-group">Niciun tip găsit. Încearcă „prag” sau „oferte”.</p>'}
let sourceRow;function sources(id){sourceRow=fixtures.find(r=>r.id===id);state.sourcePage=0;renderSources();$('#sources-dialog').showModal()}
function renderSources(){if(state.scenario==='missing'){$('#source-content').innerHTML='<div class="source-summary"><strong>Lista exactă de surse nu este disponibilă</strong><p>Această versiune a semnalului nu a păstrat înregistrările folosite în calcul. O listă mai largă de achiziții nu ar verifica același rezultat.</p></div><p class="source-note">Stare demonstrativă. Semnalul necesită recalculare în aplicație; acest mockup nu pornește procesări.</p>';return}const r=sourceRow,m=metrics(r),c=state.code;let records=[],totalLabel='';if(c==='award_single_bid'){records=[{name:'Contract demonstrativ · lot 1',detail:'TED: 1 ofertă raportată · referință fictivă',value:m.total*.4}];totalLabel='Valoarea anunțului include și alte loturi. Doar lotul 1 ilustrează observația.'}
 else if(c.startsWith('fin_')){records=[{name:`Bilanț demonstrativ · ${r.year}`,detail:c==='fin_tiny_staff'?`Număr mediu de salariați: ${r.id%5+1}`:'Cifră de afaceri: reper distinct de valoarea achizițiilor',value:null},{name:'Achiziții înregistrate · selecție demonstrativă',detail:'Acest mockup nu furnizează o listă oficială de contracte.',value:m.total}];totalLabel='Bilanțurile și valorile contractate sunt mărimi distincte, nu dovezi ale unor încasări.'}
 else if(c==='net_shared_admin'){records=[{name:r.supplier,detail:'Reprezentant legal: Persoană demonstrativă A',value:null},{name:firms[(r.id+1)%firms.length],detail:'Același reprezentant în registrul demonstrativ',value:null}];totalLabel='Reprezentant comun nu înseamnă automat proprietar sau beneficiar real comun.'}
 else {const cents=Math.round(m.total*100),part=Math.floor(cents/m.count);records=Array.from({length:m.count},(_,i)=>({name:`${c.startsWith('award')?'Înregistrare':'Achiziție'} demonstrativă ${i+1}`,detail:`${r.year} · ${c.startsWith('award')?'procedură demonstrativă':(c==='da_round'?'Produse / servicii · plafon 270.120 lei':`CPV ${r.cpv} · lucrări`)}`,value:(i===m.count-1?cents-part*(m.count-1):part)/100}));totalLabel=`${records.length} înregistrări demonstrative · total ${money(m.total)}. Suma acestui exemplu se reconciliază.`}
 $('#source-content').innerHTML=`<div class="source-summary"><strong>${esc(entity(r))}</strong><p>${meta().title} · ${m.period}</p><p>${totalLabel}</p></div>${records.slice(state.sourcePage*10,state.sourcePage*10+10).map(x=>`<div class="source-record"><div>${esc(x.name)}<small>${esc(x.detail)}</small></div><strong>${x.value===null?'—':money(x.value)}</strong></div>`).join('')}${records.length>10?`<div class="results-toolbar"><span>Pagina ${state.sourcePage+1} din ${Math.ceil(records.length/10)}</span><div class="pager"><button data-source-page="${state.sourcePage-1}" ${!state.sourcePage?'disabled':''} aria-label="Sursele anterioare">${icon('left')}</button><button data-source-page="${state.sourcePage+1}" ${(state.sourcePage+1)*10>=records.length?'disabled':''} aria-label="Sursele următoare">${icon('right')}</button></div></div>`:''}<p class="source-note">Aceste înregistrări sunt fictive. În aplicația reală, fiecare sursă disponibilă va avea legătura sa către detaliile contractului și SEAP / TED. Aici nu inventăm linkuri oficiale și nu pornim descărcări.</p>`;
}
$('#theme').innerHTML=icon('moon');$$('.close').forEach(b=>{b.innerHTML=icon('close');b.addEventListener('click',()=>b.closest('dialog').close())});$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';$('#theme').setAttribute('aria-label',dark?'Activează tema întunecată':'Activează tema luminoasă')};if(matchMedia('(prefers-color-scheme: dark)').matches)document.documentElement.dataset.theme='dark';
$('#choose-type').onclick=()=>{$('#type-search').value='';chooseType();$('#type-dialog').showModal();$('#type-search').focus()};$('#type-search').oninput=chooseType;
$('#county').onchange=e=>{state.county=e.target.value;state.page=0;state.open=null;update()};
$('#mobile-filters').onclick=()=>{$('#mobile-role').value=state.role;$('#mobile-county').value=state.county;$('#mobile-county-label').textContent=state.role==='authority'?'Județul autorității':'Județul firmei';$('#filters-dialog').showModal()};$('#mobile-role').onchange=e=>$('#mobile-county-label').textContent=e.target.value==='authority'?'Județul autorității':'Județul firmei';
function roleChange(role){state.role=role;state.band=null;const m=meta();if(state.view==='signals'&&['authority','supplier'].includes(m.subject)&&m.subject!==role){state.code=role==='authority'?'da_concentration':'da_dependence';$('#role-message').textContent='Tipul semnalului a fost schimbat pentru rolul ales.'}}
$('#mobile-form').onsubmit=e=>{e.preventDefault();roleChange($('#mobile-role').value);state.county=$('#mobile-county').value;state.page=0;state.open=null;$('#filters-dialog').close();update()};
$('#scenario').onchange=e=>{state.scenario=e.target.value;state.page=0;state.open=null;update()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.type){state.code=b.dataset.type;state.page=0;state.open=null;$('#role-message').textContent='';syncRole();$('#type-dialog').close();update()}
 if(b.dataset.role){$('#role-message').textContent='';roleChange(b.dataset.role);state.page=0;state.open=null;update()}
 if(b.dataset.view&&b.dataset.view!==state.view){viewMemory[state.view]={page:state.page,role:state.role,county:state.county,band:state.band};state.view=b.dataset.view;const previous=viewMemory[state.view],sameScope=previous.role===state.role&&previous.county===state.county;state.page=sameScope?previous.page:0;state.open=null;state.band=state.view==='cri'&&sameScope?previous.band??null:null;$('#role-message').textContent='';update()}
 if(b.dataset.page!==undefined){state.page=Number(b.dataset.page);state.open=null;update({scroll:true})}
 if(b.dataset.expand!==undefined){const id=Number(b.dataset.expand);state.open=state.open===id?null:id;renderResults();$(`[data-expand="${id}"]`)?.focus({preventScroll:true})}
 if(b.dataset.source!==undefined)sources(Number(b.dataset.source));
 if(b.dataset.sourcePage!==undefined){state.sourcePage=Number(b.dataset.sourcePage);renderSources()}
 if(b.dataset.band!==undefined){state.band=state.band===Number(b.dataset.band)?null:Number(b.dataset.band);state.page=0;state.open=null;update()}
 if(b.id==='reset-band'){state.band=null;state.page=0;update()}
 if(b.id==='reset-filters'||b.id==='retry'){state.scenario='normal';$('#scenario').value='normal';if(b.id==='reset-filters')state.county='';update()}
});document.addEventListener('change',e=>{if(e.target.id==='cri-sort'){state.sort=e.target.value;state.page=0;update()}});
window.addEventListener('popstate',()=>{const p=new URLSearchParams(location.search);state.code=TYPES.some(t=>t.code===p.get('tip'))?p.get('tip'):'da_split';state.role=p.get('rol')==='supplier'?'supplier':'authority';state.county=counties.includes(p.get('jud'))?p.get('jud'):'';state.view=p.get('view')==='cri'?'cri':'signals';state.page=Math.max(0,Number(p.get('p'))||0);state.band=p.has('cri')?Number(p.get('cri')):null;state.sort=p.get('sort')==='name'?'name':'cri';state.open=null;update({loading:false})});
update({loading:false});
