const $ = selector => document.querySelector(selector);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = value => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const storageKey = 'cinecastiga:document-mock:v1';
const docs = [...window.DOCUMENT_FIXTURES];
let saved = [], active = null, pageIndex = 0, selection = null, view = 'documents', storageAvailable = true;
try { const stored = JSON.parse(localStorage.getItem(storageKey) || '[]'); if(Array.isArray(stored)) saved = stored.filter(x=>x&&typeof x.id==='string'&&typeof x.quote==='string'&&docs.some(d=>d.id===x.documentId)&&Number.isInteger(x.page)).slice(0,100); } catch { storageAvailable = false; }
function announce(text){ $('#status').textContent = text; }
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(saved));return true}catch{storageAvailable=false;return false}}
function words(){return norm($('#search').value.trim()).split(/\s+/).filter(Boolean)}
function matches(text){return words().every(word=>norm(text).includes(word))}
function highlight(text){const tokens=words();if(!tokens.length)return esc(text);const normalized=norm(text),ranges=[];for(const token of tokens){let index=0;while((index=normalized.indexOf(token,index))!==-1){ranges.push([index,index+token.length]);index+=token.length}}ranges.sort((a,b)=>a[0]-b[0]);let html='',at=0;for(const [start,end] of ranges){if(start<at)continue;html+=esc(text.slice(at,start))+'<mark>'+esc(text.slice(start,end))+'</mark>';at=end}return html+esc(text.slice(at))}
function counts(){$('#document-count').textContent=docs.length;$('#saved-count').textContent=saved.length}
function showView(next){view=next;$('#library').hidden=next!=='documents';$('#reader').hidden=next!=='reader';$('#evidence').hidden=next!=='evidence';document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===(next==='reader'?'documents':next))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(next==='documents')renderList();if(next==='evidence')renderSaved();counts()}
function renderList(){
 const q=$('#search').value.trim();$('#clear-search').hidden=!q;
 const readable=docs.filter(d=>d.state==='ready'),unindexed=docs.filter(d=>d.state!=='ready');
 const found=readable.map(doc=>({doc,hits:doc.pages.flatMap((page,p)=>page.paragraphs.flatMap((text,i)=>q&&matches(text)?[{text,p,i}]:[]))})).filter(({doc,hits})=>!q||matches(doc.title)||hits.length);
 const hitCount=found.reduce((n,r)=>n+r.hits.length,0);
 $('#coverage').textContent=q?`${hitCount} ${hitCount===1?'pasaj':'pasaje'} în ${found.length} documente · text disponibil pentru ${readable.length} din ${docs.length} documente.`:`${docs.length} documente · ${readable.length} cu text căutabil · ${unindexed.length} fără text disponibil.`;
 let html=found.map(({doc,hits})=>`<article class="document-row"><div><div class="doc-meta">${esc(doc.kind)} · ${esc(doc.date)} · ${doc.pages.length} ${doc.pages.length===1?'pagină':'pagini'}</div><h3><button class="title-button" data-open="${doc.id}">${highlight(doc.title)}</button></h3><span class="availability">${esc(doc.extraction)} · copie demonstrativă disponibilă</span>${hits.length?`<div class="matches">${hits.map(hit=>`<button class="match" data-open="${doc.id}" data-page="${hit.p}" data-paragraph="${hit.i}"><small>Pagina ${hit.p+1} · deschide pasajul în context</small>${highlight(hit.text)}</button>`).join('')}</div>`:`<p class="subtle">${esc(doc.source)}</p>`}</div><button class="row-action" data-open="${doc.id}">Deschide documentul</button></article>`).join('');
 if(!found.length)html=`<div class="empty"><h3>Nu am găsit acest text în documentele căutabile.</h3><p>Încearcă un termen mai scurt, de exemplu „utilaje”. Documentele fără text disponibil nu pot fi verificate prin această căutare.</p><button id="try-search">Caută „utilaje”</button></div>`;
 if(unindexed.length)html+=`<div style="margin-top:25px"><h3>Documente fără text căutabil</h3><p class="subtle">${q?'Nu sunt incluse în rezultatele căutării.':'Le poți verifica separat.'}</p>${unindexed.map(doc=>`<article class="document-row"><div><h3>${esc(doc.title)}</h3><span class="availability">${doc.state==='link'?'Doar link · fișierul nu este arhivat':'Text indisponibil · extragere neimplementată în machetă'}</span><p class="subtle">${esc(doc.source)}</p></div><button class="row-action" data-open="${doc.id}">${doc.state==='link'?'Vezi proveniența':'Vezi documentul'}</button></article>`).join('')}</div>`;
 $('#documents').innerHTML=html;counts();
}
function openDoc(id,p=0,i=null){active=docs.find(d=>d.id===id);if(!active)return;pageIndex=Math.min(Math.max(p,0),Math.max(0,active.pages.length-1));selection=null;showView('reader');renderReader(i);$('#reader-title').focus();window.scrollTo({top:$('#reader').offsetTop-20,behavior:'instant'})}
function readerCommon(){return `<button class="text-button" id="back-results">Înapoi la documente${$('#search').value?' și rezultate':''}</button><div class="reader-heading"><h2 id="reader-title" tabindex="-1">${esc(active.title)}</h2><p class="subtle">${esc(active.contract)} · ${esc(active.date)}</p></div>`}
function renderReader(focusParagraph=null){
 let html=readerCommon();
 if(active.state!=='ready'){
  html+=`<div class="notice"><h3>${active.state==='link'?'Avem o referință, nu și fișierul.':'Documentul nu are încă text căutabil.'}</h3><p>${active.state==='link'?'În aplicație, aici va fi linkul oficial găsit în sursă. Acest exemplu fictiv nu are un anunț SEAP real.':'În machetă nu rulează extragerea textului sau OCR. Pentru a încerca citirea și salvarea pasajelor, deschide unul dintre cele două documente demonstrative.'}</p><p><strong>Proveniență:</strong> ${esc(active.source)}</p>${active.localUrl?`<a class="button" href="${esc(active.localUrl)}" target="_blank" rel="noopener">Deschide PDF-ul ales</a>`:''}<div class="actions"><button id="open-example">Deschide caietul demonstrativ</button><button id="missing-task">Pregătește o notă de verificare</button></div><div id="missing-note" hidden><label for="missing-text">Notă de copiat în lista „De verificat”</label><textarea id="missing-text" rows="4">Obține și verifică documentul: ${esc(active.title)}. Sursa declarată: ${esc(active.source)}. Nu este încă disponibil pentru căutare în aplicație.</textarea><p class="subtle">Text pregătit în machetă; nu creează o sarcină în aplicația reală.</p></div></div>`;
  $('#reader').innerHTML=html;return;
 }
 const page=active.pages[pageIndex];
 html+=`<div class="reader-toolbar"><div class="page-control"><button id="prev-page" aria-label="Pagina precedentă" ${pageIndex===0?'disabled':''}>Înapoi</button><label for="page-select">Pagina</label><select id="page-select">${active.pages.map((_,i)=>`<option value="${i}" ${i===pageIndex?'selected':''}>${i+1} din ${active.pages.length}</option>`).join('')}</select><button id="next-page" aria-label="Pagina următoare" ${pageIndex===active.pages.length-1?'disabled':''}>Înainte</button></div><a class="button" id="original" href="fixtures/${active.filename}#page=${pageIndex+1}" target="_blank" rel="noopener">Verifică PDF-ul · p. ${pageIndex+1}</a></div>`;
 if(active.ocr)html+=`<p class="ocr-note"><strong>Text extras din scan · stare ilustrativă.</strong> În produs, OCR-ul poate greși litere sau cifre. Verifică pagina originală; corecturile vor fi păstrate separat de textul extras. PDF-ul acestei machete este generat digital.</p>`;
 html+=`<div class="reader-layout"><div><article class="page" aria-label="Textul paginii ${pageIndex+1}"><div class="doc-stamp"><span>Document fictiv · text pentru citire</span><span>Pagina ${pageIndex+1} / ${active.pages.length}</span></div><h3>${esc(page.title)}</h3>${page.paragraphs.map((text,i)=>`<div class="passage-block ${i===focusParagraph?'selected':''}" data-paragraph-block="${i}"><p>${highlight(text)}</p><button class="text-button" data-select="${i}">Alege acest paragraf</button></div>`).join('')}</article><p class="subtle">Poți selecta și doar câteva cuvinte din text. PDF-ul rămâne referința pentru citare.</p><a class="button mobile-save" href="#save-panel">Mergi la salvarea pasajului</a></div><aside><form class="save-panel" id="save-panel"><h3>Păstrează un pasaj</h3><p id="selection-hint">Alege un paragraf sau selectează textul din pagină.</p><blockquote class="selected-quote" id="selected-quote" hidden></blockquote><div id="selection-fields" hidden><label>Leagă de o întrebare<select id="question"><option value="">Fără întrebare asociată</option><option>Cerințele permit participarea mai multor firme?</option><option>Ce servicii au fost efectiv recepționate?</option></select></label><label>Nota ta <span class="subtle">(opțional)</span><textarea id="note" placeholder="Ce merită verificat în acest pasaj?" maxlength="2000"></textarea></label>${active.ocr?'<label><input id="ocr-check" type="checkbox"> Am verificat pasajul în PDF</label>':''}<button class="primary" type="submit">Păstrează în ancheta demo</button><p class="subtle">Se păstrează local documentul de referință, pagina și textul selectat.</p></div></form><section class="source-details"><h3>Documentul din spatele citatului</h3><dl><dt>Proveniență</dt><dd>${esc(active.source)}</dd><dt>Fișier</dt><dd>${esc(active.filename)} · versiunea demo 1</dd><dt>Legătură cu achiziția</dt><dd>${esc(active.contract)}</dd><dt>Text disponibil</dt><dd>${esc(active.extraction)}</dd></dl><details class="limits"><summary>Identitatea fișierului</summary><p>Amprenta identifică exact copia folosită. Nu certifică autenticitatea documentului.</p><code id="file-hash">Se citește amprenta…</code></details></section></aside></div>`;
 $('#reader').innerHTML=html;
 const hashDoc=active;loadHash(hashDoc).then(hash=>{if(active===hashDoc&&$('#file-hash'))$('#file-hash').textContent=hash||'Amprenta nu a putut fi citită.'});
 if(focusParagraph!==null)selectText(page.paragraphs[focusParagraph],focusParagraph);
}
async function loadHash(doc){if(doc.hash)return doc.hash;try{const response=await fetch('fixtures/'+doc.filename);if(!response.ok)throw Error();const bytes=await response.arrayBuffer();doc.hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');return doc.hash}catch{return null}}
function selectText(text,paragraph){selection={text,page:pageIndex+1,paragraph};$('#selection-hint').textContent=`Pagina ${pageIndex+1} · pasaj selectat`;$('#selected-quote').textContent=text;$('#selected-quote').hidden=false;$('#selection-fields').hidden=false;document.querySelectorAll('.passage-block').forEach(el=>el.classList.toggle('selected',Number(el.dataset.paragraphBlock)===paragraph));}
function renderSaved(){
 $('#export-evidence').hidden=!saved.length;
 $('#saved-list').innerHTML=saved.length?saved.map(item=>{const doc=docs.find(d=>d.id===item.documentId);return `<article class="saved-item"><h3>${esc(doc.title)}</h3><div class="source-line">Pagina ${item.page} · versiunea demo 1 · ${esc(item.date)}${item.ocr?' · '+(item.verified?'Verificat în PDF de cititor':'OCR neverificat'):''}</div><blockquote>„${esc(item.quote)}”</blockquote>${item.question?`<p><strong>Întrebare:</strong> ${esc(item.question)}</p>`:''}${item.note?`<p class="note"><strong>Nota ta:</strong> ${esc(item.note)}</p>`:''}<div class="actions"><button data-saved-open="${esc(item.id)}">Revino la pasaj · p. ${item.page}</button><a class="button" href="fixtures/${doc.filename}#page=${item.page}" target="_blank" rel="noopener">Verifică PDF-ul</a><button class="text-button" data-remove="${esc(item.id)}">Elimină din machetă</button></div></article>`}).join(''):`<div class="empty"><h3>Primul pasaj începe cu o întrebare.</h3><p>Caută „utilaje”, deschide un rezultat și păstrează cerința care merită verificată. Documentul și pagina vor rămâne lângă citat.</p><button id="start-search" class="primary">Caută în documente</button></div>`;
}
document.addEventListener('click',event=>{
 const button=event.target.closest('button');if(!button)return;
 if(button.dataset.view){announce('');showView(button.dataset.view);return}
 if(button.dataset.open){openDoc(button.dataset.open,Number(button.dataset.page||0),button.dataset.paragraph===undefined?null:Number(button.dataset.paragraph));return}
 if(button.dataset.select!==undefined){selectText(active.pages[pageIndex].paragraphs[Number(button.dataset.select)],Number(button.dataset.select));if(matchMedia('(max-width:700px)').matches){$('#save-panel').scrollIntoView({block:'start',behavior:'instant'});$('#note').focus({preventScroll:true})}return}
 if(button.dataset.savedOpen){const item=saved.find(s=>s.id===button.dataset.savedOpen);openDoc(item.documentId,item.page-1,item.paragraph);selectText(item.quote,item.paragraph);return}
 if(button.dataset.remove){const item=saved.find(s=>s.id===button.dataset.remove);saved=saved.filter(s=>s.id!==item.id);persist();counts();renderSaved();announce('Pasaj eliminat din machetă.');return}
 switch(button.id){
 case 'back-results':showView('documents');$('#search').focus();break;
 case 'clear-search':$('#search').value='';renderList();$('#search').focus();break;
 case 'try-search':case 'start-search':$('#search').value='utilaje';showView('documents');$('#search').focus();break;
 case 'add-document':$('#upload-form').hidden=false;$('#file').focus();break;
 case 'cancel-upload':$('#upload-form').hidden=true;$('#add-document').focus();break;
 case 'open-example':openDoc('caiet');break;
 case 'missing-task':$('#missing-note').hidden=false;$('#missing-text').focus();$('#missing-text').select();break;
 case 'prev-page':case 'next-page':pageIndex+=button.id==='next-page'?1:-1;selection=null;renderReader();$('#page-select').focus();break;
 case 'theme':{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';button.textContent=dark?'Temă luminoasă':'Temă întunecată';break}
 case 'export-evidence':{const blob=new Blob([JSON.stringify({demo:true,notice:'Date fictive; salvare locală. Fișierele PDF nu sunt incluse în acest export de note.',passages:saved},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pasaje-demonstrative.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);break}
 }
});
$('#search-form').addEventListener('submit',event=>{event.preventDefault();renderList()});
let timer;$('#search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(renderList,140)});
document.addEventListener('change',event=>{if(event.target.id==='page-select'){pageIndex=Number(event.target.value);selection=null;renderReader();$('#page-select').focus()}});
function selectedFromPage(){if(view!=='reader'||active.state!=='ready')return;const native=getSelection();if(!native||native.isCollapsed||!native.rangeCount)return;const range=native.getRangeAt(0),container=$('.page');if(!container.contains(range.startContainer)||!container.contains(range.endContainer))return;const para=(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement).closest('.passage-block');const text=native.toString().trim();if(!text||!para)return;const startNode=range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement;const endNode=range.endContainer.nodeType===1?range.endContainer:range.endContainer.parentElement;const sourceParagraph=para.querySelector('p');if(startNode.closest('p')!==sourceParagraph||endNode.closest('p')!==sourceParagraph||!sourceParagraph.textContent.includes(text))return;selectText(text,Number(para.dataset.paragraphBlock));}
document.addEventListener('mouseup',selectedFromPage);document.addEventListener('keyup',event=>{if(event.key.startsWith('Arrow')||event.key==='Shift')selectedFromPage()});
document.addEventListener('submit',async event=>{
 if(event.target.id!=='save-panel')return;event.preventDefault();if(!selection)return;const button=event.target.querySelector('[type=submit]');button.disabled=true;
 const doc=active,chosen={...selection},note=$('#note').value,question=$('#question').value,verified=$('#ocr-check')?.checked||false;const sourceParagraph=doc.pages[chosen.page-1]?.paragraphs[chosen.paragraph];if(!chosen.text||!sourceParagraph?.includes(chosen.text)){announce('Pasajul nu corespunde textului documentului. Selectează din nou textul din pagină.');button.disabled=false;return}const hash=await loadHash(doc);
 if(!hash){announce('PDF-ul demonstrativ nu a putut fi citit. Reîncearcă salvarea după ce verifici linkul PDF.');button.disabled=false;return}
 saved.unshift({id:crypto.randomUUID(),documentId:doc.id,filename:doc.filename,sha256:hash,page:chosen.page,paragraph:chosen.paragraph,quote:chosen.text,note,question,ocr:!!doc.ocr,verified,source:doc.source,contract:doc.contract,version:1,date:new Date().toLocaleDateString('ro-RO')});const stored=persist();showView('evidence');announce(stored?'Pasaj păstrat în acest browser, cu pagina și referința PDF.':'Pasaj disponibil doar în această sesiune: browserul nu permite salvarea locală. Descarcă notele înainte să închizi.');$('#evidence-title').setAttribute('tabindex','-1');$('#evidence-title').focus();
});
$('#upload-form').addEventListener('submit',event=>{event.preventDefault();const file=$('#file').files[0];if(!file||!file.name.toLowerCase().endsWith('.pdf')){$('#upload-error').textContent='Alege un fișier PDF pentru această machetă.';return}docs.push({id:'local-'+crypto.randomUUID(),title:file.name,kind:'Document adăugat',date:new Date().toLocaleDateString('ro-RO'),source:$('#provenance').value.trim(),state:'pending',contract:'Asociere de demonstrat în aplicație',pages:[],localUrl:URL.createObjectURL(file)});$('#upload-form').reset();$('#upload-form').hidden=true;renderList();announce('Document adăugat temporar în listă. Fișierul nu a fost încărcat pe un server; textul nu este extras în machetă.')});
counts();renderList();if(!storageAvailable)announce('Browserul nu permite salvarea locală. Poți descărca notele din secțiunea „Pasaje păstrate”.');
