/** Read-only application-independent acceptance of the fictional document prototype. */
import {mkdir,writeFile} from 'node:fs/promises';
const dir='docs/implementation/previews/batch5-documents';await mkdir(dir,{recursive:true});
const target=await(await fetch('http://127.0.0.1:9237/json/new?http://127.0.0.1:3112/documents/',{method:'PUT'})).json();
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let serial=0;const pending=new Map(),checks=[],errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)};
const cmd=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
const ev=async expression=>{const r=await cmd('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value};
const pause=ms=>new Promise(r=>setTimeout(r,ms));const assert=(v,m)=>{if(!v)throw Error(m);checks.push(m)};
async function until(expression){for(let n=0;n<100;n++){if(await ev(expression))return;await pause(100)}throw Error('Timed out: '+expression)}
async function click(selector){await ev(`document.querySelector(${JSON.stringify(selector)}).click()`)}
async function search(value){await ev(`document.querySelector('#search').value=${JSON.stringify(value)};document.querySelector('#search-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))`)}
async function width(width){await cmd('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<700});await pause(50);assert(!await ev('document.documentElement.scrollWidth>innerWidth'),'No overflow at '+width+'px')}
async function shot(name){await ev('window.scrollTo(0,0);document.fonts.ready');await pause(250);const metrics=await cmd('Page.getLayoutMetrics');const size=metrics.cssContentSize;const r=await cmd('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:size.width,height:size.height,scale:1}});await writeFile(`${dir}/${name}.png`,Buffer.from(r.data,'base64'))}
try{
 await cmd('Runtime.enable');await cmd('Page.enable');await until("!!document.querySelector('.document-row')");await ev("localStorage.removeItem('cinecastiga:document-mock:v1')");await cmd('Page.reload');await until("!!document.querySelector('.document-row')");await ev('document.fonts.ready');await width(1440);await shot('library-desktop');
 await search('utilaje');assert(await ev("document.querySelectorAll('.match').length===4"),'Search finds four passages across two documents');await shot('search-desktop');
 await search('spatii verzi');assert(await ev("document.querySelectorAll('.match').length===2"),'Romanian diacritic-insensitive phrase search');
 await search('xyz-nonexistent');assert(await ev("!!document.querySelector('.empty')&&document.querySelectorAll('[data-open=link]').length===1"),'Empty search retains visibility of unindexed documents');
 await search('utilaje');await click('.match[data-paragraph="1"]');assert(await ev("document.querySelector('#page-select').value==='1'&&document.querySelector('#original').href.endsWith('#page=2')"),'Search opens exact PDF page 2');await until("document.querySelector('#file-hash').textContent.length===64");await shot('reader-desktop');
 await ev("document.querySelector('#note').value='Verifică dacă cerința a fost interpretată la fel pentru toți ofertanții.';document.querySelector('#question').selectedIndex=1");await click('#save-panel [type=submit]');await until("!document.querySelector('#evidence').hidden");assert(await ev("document.querySelector('.saved-item').textContent.includes('Pagina 2')&&document.querySelector('.saved-item .note').textContent.includes('Verifică')"),'Save retains exact page, note and question');
 const record=await ev("JSON.parse(localStorage.getItem('cinecastiga:document-mock:v1'))[0]");assert(record.sha256.length===64&&record.quote.includes('minimum 3 utilaje'),'Saved passage binds PDF hash and exact quote');
 await cmd('Page.reload');await until("!!document.querySelector('.document-row')");await click('[data-view=evidence]');assert(await ev("document.querySelectorAll('.saved-item').length===1"),'Saved evidence survives reload');await width(390);await shot('saved-mobile');await click('[data-saved-open]');await until("document.querySelector('#file-hash').textContent.length===64");await shot('reader-mobile');
 await width(800);await width(320);await width(1440);await click('#theme');await shot('reader-dark');await click('#theme');
 await ev("(()=>{const p=document.querySelector('[data-paragraph-block=\"1\"] p');const text=[...p.childNodes].find(n=>n.nodeType===3&&n.textContent.length>25);const range=document.createRange();range.setStart(text,0);range.setEnd(text,20);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));})()");assert(await ev("document.querySelector('#selected-quote').textContent.length===20"),'Native selection chooses exact subparagraph quote');
 await ev("(()=>{const block=document.querySelector('[data-paragraph-block=\"1\"]');const range=document.createRange();range.setStart(block.querySelector('p').firstChild,0);range.setEnd(block.querySelector('button').firstChild,12);getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));})()");assert(await ev("document.querySelector('#selected-quote').textContent.length===20&&!document.querySelector('#selected-quote').textContent.includes('Alege')"),'Selection spanning helper label cannot become a source quote');
 await click('#next-page');assert(await ev("document.querySelector('#page-select').value==='2'&&document.querySelector('#selection-fields').hidden"),'Page navigation clears stale selection');await click('#back-results');await search('utilaje');await click('[data-open=clarificare]');assert(await ev("!!document.querySelector('.ocr-note')&&document.querySelector('#ocr-check')!==null"),'OCR state explicitly disclosed with verification control');
 await click('[data-select="2"]');await click('#save-panel [type=submit]');await until("!document.querySelector('#evidence').hidden");assert(await ev("document.querySelector('.saved-item').textContent.includes('OCR neverificat')"),'Unverified OCR status preserved in evidence');
 await click('[data-view=documents]');await click('[data-open=link]');assert(await ev("document.querySelector('.notice').textContent.includes('nu și fișierul')&&!document.querySelector('#original')"),'Link-only record never presents unavailable original');await click('#missing-task');assert(await ev("!document.querySelector('#missing-note').hidden"),'Missing-document note can be prepared without false server save');await click('#back-results');
 await click('#add-document');const root=await cmd('DOM.getDocument');const field=await cmd('DOM.querySelector',{nodeId:root.root.nodeId,selector:'#file'});await cmd('DOM.setFileInputFiles',{nodeId:field.nodeId,files:[process.cwd()+'/mockups/documents/fixtures/caiet-de-sarcini-exemplu.pdf']});await ev("document.querySelector('#provenance').value='Fișier demonstrativ ales pentru verificare' ");await click('#upload-form [type=submit]');assert(await ev("document.querySelector('#document-count').textContent==='5'&&document.querySelector('#status').textContent.includes('nu a fost încărcat')"),'Local PDF addition is disclosed as metadata-only, not server upload');
 await click('[data-view=evidence]');await click('[data-remove]');assert(await ev("document.querySelectorAll('.saved-item').length===1"),'Demo passage removal works');
 await width(390);await click('[data-view=documents]');await search('utilaje');await shot('search-mobile');await width(1440);await cmd('Page.reload');await until("!!document.querySelector('.document-row')");await search('utilaje');assert(!errors.length,'No browser runtime exceptions');
 await writeFile(dir+'/verification.json',JSON.stringify({status:'passed',checkedAt:new Date().toISOString(),applicationWrites:false,checks,errors,screens:['library-desktop','search-desktop','reader-desktop','saved-mobile','reader-mobile','reader-dark','search-mobile']},null,2));console.log(JSON.stringify({status:'passed',checks:checks.length,screens:7,target:target.id}));
}catch(error){console.error(error);await writeFile(dir+'/verification.json',JSON.stringify({status:'failed',error:String(error),checks,errors},null,2));process.exitCode=1}finally{ws.close()}
