window.DOCUMENT_FIXTURES = [
 {id:'caiet',title:'Caiet de sarcini · întreținerea spațiilor verzi',kind:'Caiet de sarcini',date:'12 martie 2025',source:'Documentație de atribuire · exemplu fictiv',filename:'caiet-de-sarcini-exemplu.pdf',state:'ready',extraction:'Text din PDF',contract:'Contract demonstrativ CV-2025-014',pages:[
 {title:'Obiectul serviciilor',paragraphs:['Municipiul Exemplu — document demonstrativ. Acest document a fost creat exclusiv pentru testarea interfeței cinecâștigă?. Nu descrie o achiziție reală.','Serviciile includ cosirea gazonului, îngrijirea arborilor și întreținerea spațiilor verzi din domeniul public. Suprafața orientativă este de 18 hectare.','Intervențiile se fac pe baza comenzilor emise de autoritate. Situațiile de lucrări vor indica amplasamentul, suprafața și data fiecărei intervenții.']},
 {title:'Capacitate tehnică și utilaje',paragraphs:['Prestatorul trebuie să asigure personalul și utilajele necesare pentru fiecare tip de intervenție.','Operatorul va demonstra că dispune de minimum 3 utilaje pentru cosire. Utilajele pot fi deținute, închiriate sau puse la dispoziție printr-un angajament valabil pe durata contractului.','Experiența similară poate fi demonstrată prin unul sau mai multe contracte de servicii de întreținere a spațiilor verzi.','Pentru verificare, se prezintă documentele justificative și perioada în care resursele sunt disponibile. Cerința nu impune o anumită marcă de utilaj.']},
 {title:'Recepție și raportare',paragraphs:['Recepția lunară se consemnează într-un proces-verbal semnat de reprezentanții părților.','Fiecare situație de lucrări va include cantitățile executate, prețul unitar și valoarea rezultată. Fotografiile de teren se anexează raportului de activitate.','Înregistrarea valorii contractului nu reprezintă dovada efectuării unei plăți. Verificarea plăților necesită documente distincte.']}
 ]},
 {id:'clarificare',title:'Răspuns la clarificări · disponibilitatea utilajelor',kind:'Clarificare',date:'21 martie 2025',source:'Răspuns al autorității · exemplu fictiv',filename:'clarificare-exemplu.pdf',state:'ready',extraction:'Text OCR · de verificat',ocr:true,contract:'Contract demonstrativ CV-2025-014',pages:[
 {title:'Răspuns la solicitarea de clarificări',paragraphs:['Municipiul Exemplu — răspuns demonstrativ. Nu este un document al unei autorități reale.','Întrebare: se acceptă utilaje închiriate pentru îndeplinirea cerinței de capacitate tehnică?','Răspuns: da. Sunt acceptate utilaje închiriate sau puse la dispoziție printr-un angajament. Nu se solicită ca acestea să fie în proprietatea ofertantului.','Răspunsul se citește împreună cu pagina 2 a caietului de sarcini. Toate celelalte prevederi rămân neschimbate.']}
 ]},
 {id:'link',title:'Anunțul de atribuire · sursă externă',kind:'Anunț',date:'7 aprilie 2025',source:'Legătură spre anunț · exemplu fictiv',state:'link',contract:'Contract demonstrativ CV-2025-014',pages:[]},
 {id:'pending',title:'Proces-verbal de recepție · aprilie',kind:'Recepție',date:'5 mai 2025',source:'Adăugat de reporter · exemplu fictiv',state:'pending',contract:'Contract demonstrativ CV-2025-014',pages:[]}
];
