import { chromium } from '../../apps/web/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.STORIES_TEST_URL||'http://localhost:3000/ce-bate-la-ochi';
const out=new URL('../../.impeccable/review/ce-bate-la-ochi-real-story/',import.meta.url).pathname;
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const checks=[],errors=[];
try{
 for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]]){
  const context=await browser.newContext({viewport:{width,height}}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
  p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text());});
  await p.goto(base);await p.getByRole('heading',{name:'Ce bate la ochi.',exact:true}).waitFor();await p.evaluate(()=>document.fonts.ready);
  const shot=async state=>{await p.waitForTimeout(700);await p.screenshot({path:out+name+'-'+state+'.png',fullPage:state!=='sources',animations:'disabled'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name}/${state} overflow`);};
  await p.evaluate(()=>{const original=document.startViewTransition?.bind(document);window.storyTransitions=[];if(original)document.startViewTransition=(...a)=>{const t=original(...a);t.ready.then(()=>window.storyTransitions.push(document.getAnimations().map(a=>a.effect?.pseudoElement).filter(Boolean)));return t;};});
  assert.equal(await p.locator('.romania a').count(),42);assert.equal(await p.locator('.d-main-nav a[aria-current="page"]').innerText(),'Ce bate la ochi');assert.match(await p.locator('.editorial-banner').innerText(),/Date reale/);assert(await p.locator('meta[name=robots][content*=noindex]').count()>0);assert.equal(await p.locator('.stories-page').getByText('Trei contracte. Același drum. Ce le leagă?').count(),0);await shot('atlas');
  await p.locator('[data-county="bucuresti"]').click();await p.getByRole('heading',{name:'București.',exact:true}).waitFor();await shot('county');assert((await p.evaluate(()=>window.storyTransitions)).flat().includes('::view-transition-group(county-bucuresti)'));
  await p.getByRole('button',{name:'Educație și sport',exact:true}).click();assert.match(await p.locator('.featured-title').innerText(),/Școala 311/);await p.getByRole('button',{name:/Toate/}).click();await p.locator('.featured-title').click();await p.getByRole('heading',{level:1,name:/Școala 311:/}).waitFor();await shot('article');await p.locator('.chapter-nav a[href="#cronologie"]').click();await p.waitForTimeout(500);assert(await p.evaluate(()=>document.querySelector('#cronologie h2').getBoundingClientRect().top>=document.querySelector('.site-header').getBoundingClientRect().bottom),'chapter heading under header');if(width<760)assert(await p.evaluate(()=>document.querySelector('.chapter-nav').getBoundingClientRect().top>=document.querySelector('.site-header').getBoundingClientRect().bottom-1),'sticky chapters under header');await p.evaluate(()=>{history.replaceState(null,'',location.pathname);scrollTo({top:0,behavior:'instant'})});
  assert((await p.evaluate(()=>window.storyTransitions)).flat().includes('::view-transition-group(story-cover-scoala-311-sapte-achizitii)'));
  await p.reload();await p.getByRole('heading',{level:1,name:/Școala 311:/}).waitFor();
  await p.getByRole('button',{name:/Verifică cele 7 înregistrări/}).click();await p.locator('.stories-page dialog[open]').waitFor();assert.equal(await p.locator('.stories-page dialog .record').count(),10);assert.match(await p.locator('.drawer-total').innerText(),/919[. ]661,16/);const previousY=await p.evaluate(()=>scrollY);await shot('sources');
  const popup=p.waitForEvent('popup');await p.locator('.stories-page dialog a').filter({hasText:'Deschide fișa documentată'}).first().click();const source=await popup;await source.waitForLoadState();assert.match(await source.locator('.record-amount').innerText(),/199[. ]814,88/);await source.close();await p.keyboard.press('Escape');assert.equal(await p.locator('.stories-page dialog[open]').count(),0);assert.equal(await p.evaluate(()=>scrollY),previousY);
  await p.locator('.chapter-nav a[href="#surse"]').click();await p.waitForTimeout(500);assert.match(p.url(),/poveste\/scoala-311-sapte-achizitii#surse$/);await p.goBack();await p.waitForTimeout(500);assert.match(p.url(),/poveste\/scoala-311-sapte-achizitii$/);
  await p.locator('.article-topline .back-link').click();await p.getByRole('heading',{name:'București.',exact:true}).waitFor();await p.waitForTimeout(700);await p.locator('.back-link').click();await p.getByRole('heading',{name:'Ce bate la ochi.',exact:true}).waitFor();await p.waitForTimeout(700);
  const search=p.getByRole('searchbox',{name:'Unde vrei să te uiți?'});await search.fill('buzau');assert.equal(await p.locator('#story-county-results a').count(),1);await search.press('ArrowDown');await p.keyboard.press('Enter');await p.getByRole('heading',{name:'Buzău.',exact:true}).waitFor();
  await p.goto(base+'/judet/alba');await p.getByRole('heading',{name:'Aici povestea încă nu a început.'}).waitFor();await shot('empty');
  await p.goto(base+'/poveste/scoala-311-sapte-achizitii');await p.locator('.theme-btn').click();await shot('dark');
  await p.emulateMedia({reducedMotion:'reduce'});await p.goto(base);await p.locator('[data-county="bucuresti"]').focus();await p.keyboard.press('Enter');await p.getByRole('heading',{name:'București.',exact:true}).waitFor();
  checks.push(`${name}: map, counts, active header, named county/art transitions, filters, SSR reload, source drawer and exact total, standalone source tab, Escape/scroll restoration, section anchors, county search, empty state, dark mode, keyboard/reduced motion; no overflow.`);
  await context.close();
 }
 const p=await browser.newPage({viewport:{width:320,height:700}});await p.goto(base);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px overflow');await p.goto('http://localhost:3000/');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'home 320px overflow');
 await p.goto(base+'/poveste/scoala-311-sapte-achizitii');await p.getByRole('button',{name:/Verifică cele 7 înregistrări/}).click();assert.match(await p.locator('.stories-page dialog .record').last().innerText(),/Sursă de context — nu este inclusă în total/);assert.match(await p.locator('.stories-page dialog .record').last().innerText(),/AQUANELL/);await p.keyboard.press('Escape');
 const invalid=await p.goto(base+'/poveste/does-not-exist');await p.getByRole('heading',{name:'Nu am găsit această pagină.',exact:true}).waitFor();assert.equal(await p.locator('.article-hero,.document-page,.atlas-layout').count(),0);assert(await p.locator('meta[name=robots][content*=noindex]').count()>0);checks.push(`Invalid route: Next not-found UI and noindex, no story payload; HTTP ${invalid.status()} (streamed App Router response).`);
 await p.close();assert.deepEqual(errors,[]);await fs.writeFile(out+'checks.json',JSON.stringify({checks,additional:'320px story/home header, context purchase outside seven-record total, real preview noindex, no fictional stories, invalid-route not-found/noindex',errors},null,2));console.log(checks.join('\n'));
}finally{await browser.close();}
