'use client';
import {useEffect,useId,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import DiscoveryIcon from '../DiscoveryIcon';
import {formatExactDecimal,formatInt,cleanName} from '@/lib/format';
import {parseTopicScope,topicParams,fold,PAGE_SIZE,type TopicScope,type TopicResult,type Place,type SearchTab} from '@/lib/topic-search/shared';

const defaults:TopicScope={q:'',place:'',from:'',to:'',type:'all',match:'words',tab:'all',page:1,role:''};
const TABS:{id:SearchTab;label:string}[]=[{id:'all',label:'Toate'},{id:'acquisitions',label:'Achiziții'},{id:'documents',label:'Documente'},{id:'entities',label:'Instituții și firme'}];
function Highlight({text,query}:{text:string;query:string}){
 const words=fold(query).split(/[^\p{L}\p{N}]+/u).filter(Boolean),normal=fold(text),ranges:[number,number][]=[];
 for(const word of words){let at=normal.indexOf(word);while(at>=0){ranges.push([at,at+word.length]);at=normal.indexOf(word,at+word.length);}}
 ranges.sort((a,b)=>a[0]-b[0]);const merged:[number,number][]=[];for(const r of ranges){const last=merged.at(-1);if(last&&r[0]<=last[1])last[1]=Math.max(last[1],r[1]);else merged.push([...r]);}
 let cursor=0;const parts:React.ReactNode[]=[];for(const [a,b] of merged){parts.push(text.slice(cursor,a),<mark key={a}>{text.slice(a,b)}</mark>);cursor=b;}parts.push(text.slice(cursor));return <>{parts}</>;
}
function PlacePicker({value,selected,onChange}:{value:string;selected:Place|null;onChange:(place:Place|null)=>void}){
 const id=useId(),box=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 const [term,setTerm]=useState(''),[open,setOpen]=useState(false),[active,setActive]=useState(-1),[items,setItems]=useState<Place[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setTerm(selected?.name??'');},[selected?.name,value]);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setLoading(true);setError('');setActive(-1);
 const timer=setTimeout(()=>{void fetch(`/api/topic-search/places?q=${encodeURIComponent(term)}`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!abort.signal.aborted)setItems(d.places);}).catch(e=>{if(!abort.signal.aborted){setItems([]);setError(e.message);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});},160);
 return()=>{abort.abort();clearTimeout(timer);};},[term,open]);
 const dismiss=()=>{setOpen(false);setTerm(selected?.name??'');};
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!box.current?.contains(e.target as Node)){setOpen(false);setTerm(selected?.name??'');}};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[selected]);
 useEffect(()=>{if(open&&active>=0)document.getElementById(`${id}-${active}`)?.scrollIntoView({block:'nearest'});},[open,active,id]);
 const choose=(p:Place|null)=>{onChange(p);setTerm(p?.name??'');setOpen(false);input.current?.focus();};
 return <div className="topic-place" ref={box} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))dismiss();}}>
  <label htmlFor={id}>Unde cauți?</label><div className="topic-place-input"><DiscoveryIcon name="pin"/><input ref={input} id={id} value={term} placeholder="Toată țara" autoComplete="off" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={`${id}-options`} aria-activedescendant={open&&active>=0?`${id}-${active}`:undefined} onFocus={()=>setOpen(true)} onChange={e=>{setTerm(e.target.value);setOpen(true);}} onKeyDown={e=>{
   if(e.key==='Escape'){e.preventDefault();dismiss();}else if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setOpen(true);setActive(a=>e.key==='ArrowDown'?Math.min(a+1,loading?0:items.length):Math.max(0,a-1));}else if(e.key==='Enter'&&open){e.preventDefault();if(active===0)choose(null);else if(!loading&&active>0&&items[active-1])choose(items[active-1]!);}
  }}/>{value&&<button type="button" aria-label="Șterge filtrul de localitate" onClick={()=>choose(null)}><DiscoveryIcon name="close"/></button>}</div>
  {open&&<div className="topic-options"><p className="topic-help" role="status">{loading?'Se caută localități…':error||'Alege un județ, oraș sau o comună.'}</p><ul id={`${id}-options`} role="listbox" aria-label="Județe și localități" aria-busy={loading}>
   <li role="option" id={`${id}-0`} aria-selected={active===0} onPointerDown={e=>e.preventDefault()}><button type="button" tabIndex={-1} onClick={()=>choose(null)}>Toată țara</button></li>
   {!loading&&items.map((p,i)=><li role="option" id={`${id}-${i+1}`} key={p.id} aria-selected={active===i+1} onPointerDown={e=>e.preventDefault()}><button type="button" tabIndex={-1} onClick={()=>choose(p)}><strong>{p.name}</strong><small>{p.detail}</small></button></li>)}
  </ul>{!loading&&!items.length&&!error&&<p className="topic-help">Nicio localitate găsită. Încearcă alt nume.</p>}</div>}
 </div>;
}
function PeriodPicker({scope,onChange}:{scope:TopicScope;onChange:(patch:Partial<TopicScope>)=>void}){
 const [open,setOpen]=useState(false),[from,setFrom]=useState(scope.from),[to,setTo]=useState(scope.to),[error,setError]=useState('');const box=useRef<HTMLDivElement>(null),button=useRef<HTMLButtonElement>(null),id=useId();
 useEffect(()=>{setFrom(scope.from);setTo(scope.to);setError('');},[scope.from,scope.to,open]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!box.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 const apply=()=>{try{parseTopicScope(new URLSearchParams({from,to}));if(!from||!to)throw Error('Completează ambii ani sau alege „Toți anii”.');onChange({from,to});setOpen(false);button.current?.focus();}catch(e){setError((e as Error).message);}};
 return <div className="topic-period" ref={box} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);button.current?.focus();}}}><label htmlFor={id}>Perioada</label><button ref={button} id={id} type="button" aria-label={`Perioada: ${scope.from?scope.from===scope.to?scope.from:`${scope.from}–${scope.to}`:'Toți anii'}`} className="topic-control" aria-expanded={open} aria-controls={`${id}-panel`} onClick={()=>setOpen(!open)}>{scope.from?scope.from===scope.to?scope.from:`${scope.from}–${scope.to}`:'Toți anii'}<DiscoveryIcon name="calendar"/></button>
 {open&&<div className="topic-period-panel" id={`${id}-panel`}><h3>Alege intervalul</h3><div className="topic-year-pair"><label>Din anul<input type="number" min={1900} max={new Date().getFullYear()+1} value={from} onChange={e=>setFrom(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();apply();}}}/></label><label>Până în anul<input type="number" min={1900} max={new Date().getFullYear()+1} value={to} onChange={e=>setTo(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();apply();}}}/></label></div><p className="topic-help">Sunt incluși ambii ani.</p>{error&&<p role="alert" className="topic-error">{error}</p>}<button type="button" className="topic-primary" onClick={apply}>Aplică intervalul</button><button type="button" className="topic-text-button" onClick={()=>{onChange({from:'',to:''});setOpen(false);button.current?.focus();}}>Toți anii</button></div>}
 </div>;
}
export default function TopicSearch(){
 const router=useRouter(),params=useSearchParams(),url=params.toString();
 const [scope,setScope]=useState<TopicScope>(defaults),[query,setQuery]=useState(''),[place,setPlace]=useState<Place|null>(null),[data,setData]=useState<TopicResult|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[copied,setCopied]=useState('');
 const resultBox=useRef<HTMLDivElement>(null),[minHeight,setMinHeight]=useState(400);
 useEffect(()=>{let next:TopicScope;try{next=parseTopicScope(new URLSearchParams(url));}catch(e){setError((e as Error).message);setLoading(false);return;}
 setScope(next);setQuery(next.q);setCopied('');setError('');setLoading(true);setMinHeight(Math.max(400,resultBox.current?.offsetHeight??400));
 const abort=new AbortController();void fetch(`/api/topic-search?${topicParams(next)}`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!abort.signal.aborted){setData(d);setPlace(d.place);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();
 },[url,retry]);
 const update=(patch:Partial<TopicScope>)=>{const next={...scope,...patch,page:patch.page??1},target=topicParams(next).toString();setMinHeight(Math.max(400,resultBox.current?.offsetHeight??400));setLoading(true);if(target===url)setRetry(n=>n+1);else router.push(`/cauta?${target}`,{scroll:false});};
 const tab=(id:SearchTab)=>update({tab:id,role:''});
 const resultScope=data?.scope??scope,total=resultScope.tab==='all'?0:data?.[resultScope.tab]?.total??0;
 const retained=Boolean(loading||error);
 const resultDescription=[`„${resultScope.q}”`,data?.place?.name??'toată țara',resultScope.from?`${resultScope.from}–${resultScope.to}`:'toți anii',resultScope.type==='da'?'achiziții directe':resultScope.type==='contracts'?'contracte din proceduri':'toate tipurile',resultScope.match==='phrase'?'expresia în ordine':'toate cuvintele',TABS.find(t=>t.id===resultScope.tab)?.label,resultScope.role==='authority'?'doar instituții':resultScope.role==='supplier'?'doar furnizori':'',resultScope.tab!=='all'?`pagina ${resultScope.page}`:''].filter(Boolean).join(' · ');
 const count=(id:SearchTab)=>id==='all'?null:data?.[id]?.total;
 const countLabel=(n:number)=>formatInt(n);
 const isShown=(id:SearchTab)=>resultScope.tab==='all'||resultScope.tab===id;
 const sectionHead=(id:SearchTab,title:string,n:number)=> <div className="topic-section-head"><h2>{title} <span>{countLabel(n)}</span></h2>{resultScope.tab==='all'&&n>0&&<button type="button" className="topic-text-button" disabled={retained} onClick={()=>tab(id)}>Vezi {id==='documents'?'toate documentele':id==='entities'?'toate entitățile':'toate achizițiile'} <DiscoveryIcon name="arrow"/></button>}</div>;
 const copy=async()=>{try{await navigator.clipboard.writeText(new URL(`/cauta?${topicParams(resultScope)}`,window.location.origin).href);setCopied('Link copiat');}catch{setCopied('Nu am putut copia linkul. Copiază adresa din browser.');}};
 return <div className="topic-page">
 <nav className="topic-breadcrumb" aria-label="Perspective de explorare"><Link href="/">Descoperă</Link><span aria-hidden="true">/</span><span>Caută</span><Link href="/intreaba">Construiește o întrebare <DiscoveryIcon name="arrow"/></Link></nav>
 <header className="topic-intro"><h1>Caută un fir de urmărit.</h1><p>Un subiect, o instituție, o firmă. De aici ajungi la achiziții și la documentele din spatele lor.</p></header>
 <div className="topic-filter-surface"><form className="topic-query" role="search" onSubmit={e=>{e.preventDefault();update({q:query.trim(),tab:'all',role:''});}}><label className="d-sr-only" htmlFor="topic-query">Ce te interesează?</label><DiscoveryIcon name="search"/><input id="topic-query" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="De exemplu: locuri de joacă, iluminat, o firmă…" minLength={2} maxLength={150} required/><button className="topic-primary" type="submit">Caută <DiscoveryIcon name="arrow"/></button></form>
 <div className="topic-filters"><PlacePicker value={scope.place} selected={place} onChange={p=>{setPlace(p);update({place:p?.id??''});}}/><PeriodPicker scope={scope} onChange={update}/><label>Tipul achiziției<select value={scope.type} onChange={e=>update({type:e.target.value as TopicScope['type']})}><option value="all">Toate tipurile</option><option value="da">Achiziții directe</option><option value="contracts">Contracte din proceduri</option></select></label><label>Potrivirea<select value={scope.match} onChange={e=>update({match:e.target.value as TopicScope['match']})}><option value="words">Toate cuvintele</option><option value="phrase">Expresia în ordine</option></select></label></div>
 </div>
 <div className="topic-status" role="status" aria-live="polite">{loading?<><span className="topic-spinner" aria-hidden="true"/>Căutăm în achiziții și documente…</>:error?'Căutarea nu s-a încheiat.':scope.q?<>Rezultate pentru <strong>„{scope.q}”</strong>{place?` · ${place.name}`:''}{scope.from?` · ${scope.from}–${scope.to}`:' · toți anii'}</>:'Alege un subiect pentru a începe.'}</div>
 {error&&<div className="topic-error" role="alert"><p>{error}</p><button type="button" className="topic-control" onClick={()=>setRetry(n=>n+1)}>Reîncearcă</button> <Link href="/cauta">Resetează filtrele</Link></div>}
 <div ref={resultBox} className={`topic-results${loading?' is-loading':''}`} style={{minHeight:loading?minHeight:400}} aria-busy={loading}>
 {data?.scope.q?<>{(loading||error)&&<p className="topic-help">Rezultatele afișate mai jos sunt din ultima căutare încheiată: {resultDescription}.</p>}<nav className="topic-tabs" aria-label="Tipuri de rezultate">{TABS.map(t=><button type="button" key={t.id} aria-current={resultScope.tab===t.id?'page':undefined} disabled={retained} onClick={()=>tab(t.id)}>{t.label}{count(t.id)!=null&&<span>{countLabel(count(t.id)!)}</span>}</button>)}</nav>
 <div className="topic-result-layout"><div className="topic-records">
 {isShown('acquisitions')&&<section aria-label="Achiziții găsite">{sectionHead('acquisitions','În titlurile disponibile',data.acquisitions.total)}<p className="topic-help">Fiecare contract apare o singură dată, inclusiv când are mai mulți furnizori.</p>{data.acquisitions.hits.map(a=><article key={a.id} className="topic-record"><div className="topic-record-meta"><span>{a.kind==='da'?'Achiziție directă':'Contract din procedură'}</span>{a.date&&<span>{a.date.slice(0,10).split('-').reverse().join('.')}</span>}{a.county&&<span>{a.county}</span>}</div><h3><a href={a.href} target="_blank" rel="noopener noreferrer"><Highlight text={a.title} query={resultScope.q}/></a></h3><div className="topic-parties">{a.authorityId?<Link prefetch={false} href={`/entitati/${a.authorityId}`}>{cleanName(a.authorityName)}</Link>:<span>{a.authorityName??'Instituție neprecizată'}</span>}<span aria-hidden="true"> → </span><span>{a.suppliers.map(cleanName).join(', ')||'Furnizor neprecizat'}</span></div><div className="topic-record-bottom"><span><strong>{formatExactDecimal(a.value)}{a.value!=null?' lei':''}</strong><small>valoare înregistrată · nu plăți</small></span><a href={a.sourceUrl} target="_blank" rel="noopener noreferrer">Verifică în SEAP <DiscoveryIcon name="arrow"/></a></div></article>)}{!data.acquisitions.total&&<p className="topic-empty">Niciun titlu disponibil nu se potrivește acestor condiții. Unele importuri istorice nu păstrează titlul achiziției; poți continua căutând instituția sau firma.</p>}</section>}
 {isShown('documents')&&<section aria-label="Documente găsite">{sectionHead('documents','În documentele pregătite',data.documents.total)}<p className="topic-help">Potriviri în textul extras. Documentele aparțin procedurii și pot privi mai multe loturi.</p>{data.documents.hits.map(d=><article className="topic-record topic-document" key={d.id}><div className="topic-record-meta"><DiscoveryIcon name="bookOpen"/><span>{d.method==='ocr'?'Text OCR':'Text extras din PDF'} · pagina {d.page}</span></div><h3><a href={`/contracte/${d.contractId}?document=${d.id}&page=${d.page}&highlight=${encodeURIComponent(resultScope.q)}#fisiere`} target="_blank" rel="noopener noreferrer">{d.filename}</a></h3><blockquote><Highlight text={d.text} query={resultScope.q}/></blockquote><p className="topic-help">{d.noticeNo} · {d.noticeTitle}</p><div className="topic-document-pages"><span>Pagini găsite:</span>{d.pages.map(p=><a key={p} aria-label={`Deschide pagina ${p} din ${d.filename}`} href={`/contracte/${d.contractId}?document=${d.id}&page=${p}&highlight=${encodeURIComponent(resultScope.q)}#fisiere`} target="_blank" rel="noopener noreferrer">{p}</a>)}</div><div className="topic-record-bottom"><a href={`/contracte/${d.contractId}?document=${d.id}&page=${d.page}&highlight=${encodeURIComponent(resultScope.q)}#fisiere`} target="_blank" rel="noopener noreferrer">Citește și păstrează pasajul <DiscoveryIcon name="arrow"/></a><a href={`/api/documents/${d.id}/file?kind=pdf#page=${d.page}`} target="_blank" rel="noopener noreferrer">PDF la pagina {d.page}</a></div></article>)}{!data.documents.total&&<p className="topic-empty">{data.coverage.ready?'Nu am găsit cuvintele în documentele pregătite din această selecție.':'Nu avem încă documente cu text pregătit în această selecție.'} Absența unui rezultat nu înseamnă că cerința nu există în documentele originale.</p>}</section>}
 {isShown('entities')&&<section aria-label="Instituții și firme găsite">{sectionHead('entities','Instituții și firme',data.entities.total)}{resultScope.tab==='entities'&&<label className="topic-role">Arată<select disabled={retained} value={resultScope.role} onChange={e=>update({role:e.target.value as TopicScope['role'],tab:'entities'})}><option value="">Instituții și firme</option><option value="authority">Doar instituții</option><option value="supplier">Doar furnizori</option></select></label>}<p className="topic-help">{resultScope.place||resultScope.from||resultScope.type!=='all'?'Nume sau CUI, cu activitate în achizițiile din selecție.':'Potriviri după nume sau CUI.'}</p>{data.entities.hits.map(e=><article className="topic-record topic-entity" key={e.id}><div className="topic-record-meta"><span>{e.roles.map(r=>r==='authority'?'Instituție':'Furnizor').join(' · ')}</span>{e.cui&&<span>CUI {e.cui}</span>}{e.county&&<span>{e.county}</span>}</div><h3><Link prefetch={false} href={`/entitati/${e.id}`}><span><Highlight text={cleanName(e.name)} query={resultScope.q}/></span><DiscoveryIcon name="arrow"/></Link></h3></article>)}{!data.entities.total&&<p className="topic-empty">Nicio instituție sau firmă cu acest nume în selecție.</p>}</section>}
 {resultScope.tab!=='all'&&resultScope.page>Math.max(1,Math.ceil(total/PAGE_SIZE))&&!loading&&<p className="topic-empty">Această pagină nu mai are rezultate. <button type="button" className="topic-text-button" disabled={retained} onClick={()=>update({page:1})}>Înapoi la prima pagină</button></p>}
 {resultScope.tab!=='all'&&total>PAGE_SIZE&&<nav className="topic-pagination" aria-label="Paginarea rezultatelor"><button type="button" className="topic-control" disabled={resultScope.page<=1||retained} onClick={()=>update({page:resultScope.page-1})}>Înapoi</button><span>Pagina {resultScope.page} din {formatInt(Math.ceil(total/PAGE_SIZE))}</span><button type="button" className="topic-control" disabled={resultScope.page*PAGE_SIZE>=total||retained||resultScope.page>=1000} onClick={()=>update({page:resultScope.page+1})}>Înainte</button></nav>}
 </div><aside className="topic-context"><h2>Ce poți verifica aici</h2><p>Titlurile te duc la achiziție. Un pasaj te duce la pagina exactă din document.</p><div className="topic-coverage"><strong>{data.coverage.ready} din {data.coverage.known}</strong><span>fișiere cunoscute în selecție au text pregătit</span><progress value={data.coverage.ready} max={Math.max(1,data.coverage.known)} aria-label="Acoperirea documentelor pregătite"/><p>{data.coverage.pages} pagini căutabile. Nu sunt toate documentele din SEAP.</p></div><p>Poți păstra un pasaj într-o anchetă după ce îl deschizi și îl verifici în original.</p><button type="button" className="topic-control" onClick={()=>void copy()}><DiscoveryIcon name="link"/>Copiază căutarea</button>{copied&&<p role="status">{copied}</p>}<details><summary>Cum funcționează căutarea</summary><p>În arhivă, {formatInt(data.titleCoverage.searchable)} din {formatInt(data.titleCoverage.total)} de achiziții au titlu căutabil. Unele importuri istorice nu păstrează titlul; achizițiile lor rămân accesibile din profilurile instituțiilor și firmelor.</p><p>În titluri și documente căutăm cuvinte complete, fără diferențe între litere mari, mici sau diacritice. „Expresia în ordine” păstrează ordinea cuvintelor; punctuația nu schimbă potrivirea. În nume și CUI sunt acceptate și fragmente.</p><p>Perioada folosește data achiziției sau contractului, inclusiv ambii ani. Geografia folosește instituțiile asociate localității în catalog; instituțiile fără asociere pot lipsi.</p><p>Documentele sunt căutate doar când există o legătură verificată cu o procedură din selecție. Textul OCR poate avea erori.</p>{data.builtAt&&<p>Index de titluri actualizat la {new Date(data.builtAt).toLocaleString('ro-RO')}.</p>}</details><Link href="/intreaba" className="topic-next">Vrei clasamente sau comparații?<br/><strong>Construiește o întrebare <DiscoveryIcon name="arrow"/></strong></Link></aside></div>
 </>:!loading&&!error?<div className="topic-start"><DiscoveryIcon name="search"/><h2>Ce vrei să urmărești?</h2><p>Caută ce te interesează, apoi restrânge după loc și perioadă. Poți porni și de la numele unei firme sau al unei instituții.</p><div>{['locuri de joacă','iluminat','Municipiul Buzău'].map(q=><button type="button" className="topic-control" key={q} onClick={()=>update({q})}>{q}<DiscoveryIcon name="arrow"/></button>)}</div></div>:!data&&loading?<div className="topic-start" aria-hidden="true"><div className="topic-placeholder"/><div className="topic-placeholder"/><div className="topic-placeholder"/></div>:null}
 </div></div>;
}
